<?php

namespace DoctrineORMModule\Proxy\__CG__\HangHoa\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class HoaDon extends \HangHoa\Entity\HoaDon implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'HangHoa\\Entity\\HoaDon' . "\0" . 'idHoaDon', '' . "\0" . 'HangHoa\\Entity\\HoaDon' . "\0" . 'maHoaDon', '' . "\0" . 'HangHoa\\Entity\\HoaDon' . "\0" . 'ngayXuat', '' . "\0" . 'HangHoa\\Entity\\HoaDon' . "\0" . 'idDoiTac', '' . "\0" . 'HangHoa\\Entity\\HoaDon' . "\0" . 'idUserNv');
        }

        return array('__isInitialized__', '' . "\0" . 'HangHoa\\Entity\\HoaDon' . "\0" . 'idHoaDon', '' . "\0" . 'HangHoa\\Entity\\HoaDon' . "\0" . 'maHoaDon', '' . "\0" . 'HangHoa\\Entity\\HoaDon' . "\0" . 'ngayXuat', '' . "\0" . 'HangHoa\\Entity\\HoaDon' . "\0" . 'idDoiTac', '' . "\0" . 'HangHoa\\Entity\\HoaDon' . "\0" . 'idUserNv');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (HoaDon $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function setIdHoaDon($idHoaDon)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdHoaDon', array($idHoaDon));

        return parent::setIdHoaDon($idHoaDon);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdHoaDon()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getIdHoaDon();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdHoaDon', array());

        return parent::getIdHoaDon();
    }

    /**
     * {@inheritDoc}
     */
    public function setMaHoaDon($maHoaDon)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMaHoaDon', array($maHoaDon));

        return parent::setMaHoaDon($maHoaDon);
    }

    /**
     * {@inheritDoc}
     */
    public function getMaHoaDon()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMaHoaDon', array());

        return parent::getMaHoaDon();
    }

    /**
     * {@inheritDoc}
     */
    public function setNgayXuat($ngayXuat)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNgayXuat', array($ngayXuat));

        return parent::setNgayXuat($ngayXuat);
    }

    /**
     * {@inheritDoc}
     */
    public function getNgayXuat()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNgayXuat', array());

        return parent::getNgayXuat();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdDoiTac($idDoiTac)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdDoiTac', array($idDoiTac));

        return parent::setIdDoiTac($idDoiTac);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdDoiTac()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdDoiTac', array());

        return parent::getIdDoiTac();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdUserNv($idUserNv)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdUserNv', array($idUserNv));

        return parent::setIdUserNv($idUserNv);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdUserNv()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdUserNv', array());

        return parent::getIdUserNv();
    }

}
