<?php

namespace DoctrineORMModule\Proxy\__CG__\HangHoa\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class PhieuNhap extends \HangHoa\Entity\PhieuNhap implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'HangHoa\\Entity\\PhieuNhap' . "\0" . 'idPhieuNhap', '' . "\0" . 'HangHoa\\Entity\\PhieuNhap' . "\0" . 'maPhieuNhap', '' . "\0" . 'HangHoa\\Entity\\PhieuNhap' . "\0" . 'ngayNhap', '' . "\0" . 'HangHoa\\Entity\\PhieuNhap' . "\0" . 'status', '' . "\0" . 'HangHoa\\Entity\\PhieuNhap' . "\0" . 'idDoiTac', '' . "\0" . 'HangHoa\\Entity\\PhieuNhap' . "\0" . 'ctPhieuNhaps', '' . "\0" . 'HangHoa\\Entity\\PhieuNhap' . "\0" . 'idUserNv');
        }

        return array('__isInitialized__', '' . "\0" . 'HangHoa\\Entity\\PhieuNhap' . "\0" . 'idPhieuNhap', '' . "\0" . 'HangHoa\\Entity\\PhieuNhap' . "\0" . 'maPhieuNhap', '' . "\0" . 'HangHoa\\Entity\\PhieuNhap' . "\0" . 'ngayNhap', '' . "\0" . 'HangHoa\\Entity\\PhieuNhap' . "\0" . 'status', '' . "\0" . 'HangHoa\\Entity\\PhieuNhap' . "\0" . 'idDoiTac', '' . "\0" . 'HangHoa\\Entity\\PhieuNhap' . "\0" . 'ctPhieuNhaps', '' . "\0" . 'HangHoa\\Entity\\PhieuNhap' . "\0" . 'idUserNv');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (PhieuNhap $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function onPrePersist()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'onPrePersist', array());

        return parent::onPrePersist();
    }

    /**
     * {@inheritDoc}
     */
    public function getCtPhieuNhaps()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCtPhieuNhaps', array());

        return parent::getCtPhieuNhaps();
    }

    /**
     * {@inheritDoc}
     */
    public function addCtPhieuNhaps($ctPhieuNhaps)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addCtPhieuNhaps', array($ctPhieuNhaps));

        return parent::addCtPhieuNhaps($ctPhieuNhaps);
    }

    /**
     * {@inheritDoc}
     */
    public function removeCtPhieuNhaps($ctPhieuNhaps)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeCtPhieuNhaps', array($ctPhieuNhaps));

        return parent::removeCtPhieuNhaps($ctPhieuNhaps);
    }

    /**
     * {@inheritDoc}
     */
    public function setIdPhieuNhap($idPhieuNhap)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdPhieuNhap', array($idPhieuNhap));

        return parent::setIdPhieuNhap($idPhieuNhap);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdPhieuNhap()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getIdPhieuNhap();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdPhieuNhap', array());

        return parent::getIdPhieuNhap();
    }

    /**
     * {@inheritDoc}
     */
    public function setMaPhieuNhap($maPhieuNhap)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMaPhieuNhap', array($maPhieuNhap));

        return parent::setMaPhieuNhap($maPhieuNhap);
    }

    /**
     * {@inheritDoc}
     */
    public function getMaPhieuNhap()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMaPhieuNhap', array());

        return parent::getMaPhieuNhap();
    }

    /**
     * {@inheritDoc}
     */
    public function setNgayNhap($ngayNhap)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNgayNhap', array($ngayNhap));

        return parent::setNgayNhap($ngayNhap);
    }

    /**
     * {@inheritDoc}
     */
    public function getNgayNhap()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNgayNhap', array());

        return parent::getNgayNhap();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdDoiTac($idDoiTac)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdDoiTac', array($idDoiTac));

        return parent::setIdDoiTac($idDoiTac);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdDoiTac()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdDoiTac', array());

        return parent::getIdDoiTac();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdUserNv($idUserNv)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdUserNv', array($idUserNv));

        return parent::setIdUserNv($idUserNv);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdUserNv()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdUserNv', array());

        return parent::getIdUserNv();
    }

    /**
     * {@inheritDoc}
     */
    public function setStatus($status = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStatus', array($status));

        return parent::setStatus($status);
    }

    /**
     * {@inheritDoc}
     */
    public function getStatus()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStatus', array());

        return parent::getStatus();
    }

}
