<?php

namespace DoctrineORMModule\Proxy\__CG__\HangHoa\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class DoiTac extends \HangHoa\Entity\DoiTac implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'HangHoa\\Entity\\DoiTac' . "\0" . 'idDoiTac', '' . "\0" . 'HangHoa\\Entity\\DoiTac' . "\0" . 'hoTen', '' . "\0" . 'HangHoa\\Entity\\DoiTac' . "\0" . 'diaChi', '' . "\0" . 'HangHoa\\Entity\\DoiTac' . "\0" . 'email', '' . "\0" . 'HangHoa\\Entity\\DoiTac' . "\0" . 'moTa', '' . "\0" . 'HangHoa\\Entity\\DoiTac' . "\0" . 'dienThoaiCoDinh', '' . "\0" . 'HangHoa\\Entity\\DoiTac' . "\0" . 'diDong', '' . "\0" . 'HangHoa\\Entity\\DoiTac' . "\0" . 'hinhAnh', '' . "\0" . 'HangHoa\\Entity\\DoiTac' . "\0" . 'website', '' . "\0" . 'HangHoa\\Entity\\DoiTac' . "\0" . 'twitter', '' . "\0" . 'HangHoa\\Entity\\DoiTac' . "\0" . 'loaiDoiTac', '' . "\0" . 'HangHoa\\Entity\\DoiTac' . "\0" . 'idKenhPhanPhoi', '' . "\0" . 'HangHoa\\Entity\\DoiTac' . "\0" . 'ngayDangKy');
        }

        return array('__isInitialized__', '' . "\0" . 'HangHoa\\Entity\\DoiTac' . "\0" . 'idDoiTac', '' . "\0" . 'HangHoa\\Entity\\DoiTac' . "\0" . 'hoTen', '' . "\0" . 'HangHoa\\Entity\\DoiTac' . "\0" . 'diaChi', '' . "\0" . 'HangHoa\\Entity\\DoiTac' . "\0" . 'email', '' . "\0" . 'HangHoa\\Entity\\DoiTac' . "\0" . 'moTa', '' . "\0" . 'HangHoa\\Entity\\DoiTac' . "\0" . 'dienThoaiCoDinh', '' . "\0" . 'HangHoa\\Entity\\DoiTac' . "\0" . 'diDong', '' . "\0" . 'HangHoa\\Entity\\DoiTac' . "\0" . 'hinhAnh', '' . "\0" . 'HangHoa\\Entity\\DoiTac' . "\0" . 'website', '' . "\0" . 'HangHoa\\Entity\\DoiTac' . "\0" . 'twitter', '' . "\0" . 'HangHoa\\Entity\\DoiTac' . "\0" . 'loaiDoiTac', '' . "\0" . 'HangHoa\\Entity\\DoiTac' . "\0" . 'idKenhPhanPhoi', '' . "\0" . 'HangHoa\\Entity\\DoiTac' . "\0" . 'ngayDangKy');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (DoiTac $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function setIdDoiTac($idDoiTac)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdDoiTac', array($idDoiTac));

        return parent::setIdDoiTac($idDoiTac);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdDoiTac()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getIdDoiTac();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdDoiTac', array());

        return parent::getIdDoiTac();
    }

    /**
     * {@inheritDoc}
     */
    public function setHoTen($hoTen)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHoTen', array($hoTen));

        return parent::setHoTen($hoTen);
    }

    /**
     * {@inheritDoc}
     */
    public function getHoTen()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHoTen', array());

        return parent::getHoTen();
    }

    /**
     * {@inheritDoc}
     */
    public function setDiaChi($diaChi)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDiaChi', array($diaChi));

        return parent::setDiaChi($diaChi);
    }

    /**
     * {@inheritDoc}
     */
    public function getDiaChi()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDiaChi', array());

        return parent::getDiaChi();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmail($email)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmail', array($email));

        return parent::setEmail($email);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmail()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmail', array());

        return parent::getEmail();
    }

    /**
     * {@inheritDoc}
     */
    public function setState($state)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setState', array($state));

        return parent::setState($state);
    }

    /**
     * {@inheritDoc}
     */
    public function getState()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getState', array());

        return parent::getState();
    }

    /**
     * {@inheritDoc}
     */
    public function setMoTa($moTa)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMoTa', array($moTa));

        return parent::setMoTa($moTa);
    }

    /**
     * {@inheritDoc}
     */
    public function getMoTa()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMoTa', array());

        return parent::getMoTa();
    }

    /**
     * {@inheritDoc}
     */
    public function setDienThoaiCoDinh($dienThoaiCoDinh)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDienThoaiCoDinh', array($dienThoaiCoDinh));

        return parent::setDienThoaiCoDinh($dienThoaiCoDinh);
    }

    /**
     * {@inheritDoc}
     */
    public function getDienThoaiCoDinh()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDienThoaiCoDinh', array());

        return parent::getDienThoaiCoDinh();
    }

    /**
     * {@inheritDoc}
     */
    public function setDiDong($diDong)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDiDong', array($diDong));

        return parent::setDiDong($diDong);
    }

    /**
     * {@inheritDoc}
     */
    public function getDiDong()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDiDong', array());

        return parent::getDiDong();
    }

    /**
     * {@inheritDoc}
     */
    public function setHinhAnh($hinhAnh)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHinhAnh', array($hinhAnh));

        return parent::setHinhAnh($hinhAnh);
    }

    /**
     * {@inheritDoc}
     */
    public function getHinhAnh()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHinhAnh', array());

        return parent::getHinhAnh();
    }

    /**
     * {@inheritDoc}
     */
    public function setWebsite($website)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setWebsite', array($website));

        return parent::setWebsite($website);
    }

    /**
     * {@inheritDoc}
     */
    public function getWebsite()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getWebsite', array());

        return parent::getWebsite();
    }

    /**
     * {@inheritDoc}
     */
    public function setTwitter($twitter)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTwitter', array($twitter));

        return parent::setTwitter($twitter);
    }

    /**
     * {@inheritDoc}
     */
    public function getTwitter()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTwitter', array());

        return parent::getTwitter();
    }

    /**
     * {@inheritDoc}
     */
    public function setLoaiDoiTac($loaiDoiTac)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLoaiDoiTac', array($loaiDoiTac));

        return parent::setLoaiDoiTac($loaiDoiTac);
    }

    /**
     * {@inheritDoc}
     */
    public function getLoaiDoiTac()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLoaiDoiTac', array());

        return parent::getLoaiDoiTac();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdKenhPhanPhoi($idKenhPhanPhoi)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdKenhPhanPhoi', array($idKenhPhanPhoi));

        return parent::setIdKenhPhanPhoi($idKenhPhanPhoi);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdKenhPhanPhoi()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdKenhPhanPhoi', array());

        return parent::getIdKenhPhanPhoi();
    }

    /**
     * {@inheritDoc}
     */
    public function setNgayDangKy($ngayDangKy)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNgayDangKy', array($ngayDangKy));

        return parent::setNgayDangKy($ngayDangKy);
    }

    /**
     * {@inheritDoc}
     */
    public function getNgayDangKy()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNgayDangKy', array());

        return parent::getNgayDangKy();
    }

}
