<?php $this->headTitle('Thông tin khách hàng'); ?>

<div class="row">
    <div class="col-md-2">
        <div class="h5a-sidebar affix">
            <span class="breadcrumb row">
                <a href="<?php echo $this->url('hang_hoa/crud',array('action'=>'index'));?>">/ Kho</a>
                <a href="<?php echo $this->url('kenh_phan_phoi');?>">/ Khách hàng</a>
                 / #xxx /
            </span>
            <ul class="nav h5a-sidenav nav-list accordion">
                <li>
                    <a href="<?php echo $this->url('kenh_phan_phoi/crud',array('action'=>'index'));?>">
                        <i class="glyphicon glyphicon-open"></i> Khách hàng
                    </a>
                </li> 
                <li>
                    <a href="<?php echo $this->url('kenh_phan_phoi/crud',array('action'=>'nhaCungCap'));?>">
                        <i class="glyphicon glyphicon-save"></i> Nhà cung cấp
                    </a>
                </li>               
                
            </ul>
        </div>
    </div>
    <div class="col-md-10" role="main">
        <div class="h5a-docs-section">
            
    </div>
</div>
<!-- /.container -->

<div class="container h5a-container gray">
    <div class="row">
        <div class="col-md-10 col-md-offset-2">
            <h1>
                <?php if($khachHang->getHinhAnh()){ ?>
                <img class="pull-left img-circle" width="40px" height="40px" src="<?php echo $this->basePath(); ?>/img/<?php echo $khachHang->getHinhAnh(); ?>" alt="Ảnh đại diện">
                <?php }else { ?>
                    <img class="pull-left img-circle" width="40px" height="40px" src="<?php echo $this->basePath(); ?>/img/photo_default.png" alt="Ảnh đại diện">
                <?php } ?>
                <?php echo $khachHang->getHoTen(); ?>
            </h1>
             <?php 
                    $flash=$this->flashMessenger();
                    $flash->setMessageOpenFormat('<div%s>
                     <button type="button" class="close" data-dismiss="alert" aria-hidden="true">
                         &times;
                     </button>
                     <ul><li>')
                     ->setMessageSeparatorString('</li><li>')
                     ->setMessageCloseString('</li></ul></div>');

                     echo $flash->render('error',   array('alert', 'alert-dismissable', 'alert-danger'));
                     echo $flash->render('info',    array('alert', 'alert-dismissable', 'alert-info'));
                     echo $flash->render('default', array('alert', 'alert-dismissable', 'alert-warning'));
                     echo $flash->render('success', array('alert', 'alert-dismissable', 'alert-success'));
            ?>
            <div class="btn-group pull-right">
                <a href="<?php echo $this->url('kenh_phan_phoi/crud', array('action'=>'xoaKhachHang','id'=>$khachHang->getIdDoiTac())); ?>" class="btn h5a-btn btn-danger btn-xs" onclick="return xacNhanXoa()"><i class="fa fa-times"></i> Xóa khách hàng</a> 
                <!-- <a class="btn h5a-btn btn-primary btn-xs"><i class="fa fa-refresh"></i> Refresh Item</a> -->
            </div>
            <p>
            
            </p>
            <div class="tabbable">
                <ul class="nav nav-tabs" role="tablist" id="myTab">
                    <li role="presentation" class="active">
                        <a href="#home" role="tab" data-toggle="tab">Xem chi tiết</a>
                    </li>
                    <li role="presentation">
                        <a href="#1" role="tab" data-toggle="tab">Cập nhật</a>
                    </li>
                    <li role="presentation">
                        <a href="#2" role="tab" data-toggle="tab">Lịch sử giao dịch</a>
                    </li>
                </ul>
                <div class="tab-content">
                    <div role="tabpanel" class="tab-pane active" id="home">
                        <div class="row">
                            <div class="col-md-6">
                                <div class="thumbnail">
                                    <?php if($khachHang->getHinhAnh()){ ?>
                                    <img class="img-responsive" src="<?php echo $this->basePath(); ?>/img/<?php echo $khachHang->getHinhAnh(); ?>" alt="Ảnh đại diện">
                                    <?php }else { ?>
                                        <img class="img-responsive" src="<?php echo $this->basePath(); ?>/img/photo_default.png" alt="Ảnh đại diện">
                                    <?php } ?>
                                    
                                </div>
                            </div>
                            <div class="col-md-6">
                                <h4>Khách hàng: <?php echo $khachHang->getHoTen(); ?></h4>
                                <p><?php echo $khachHang->getMoTa(); ?> </p>
                                <h4 class="underline">Thông tin chi tiết</h4>
                                <table class="item">
                                    <tbody>
                                        <tr>
                                            <td><i class="fa fa-user"></i> Họ Tên</td>
                                            <td><?php echo $khachHang->getHoTen(); ?></td>
                                        </tr>
                                        <tr>
                                            <td><i class="fa fa-home"></i>Địa chỉ</td>
                                            <td><?php echo $khachHang->getDiaChi(); ?></td>
                                        </tr>
                                        
                                        <tr>
                                            <td><i class="fa fa-mobile-phone"></i> Di động</td>
                                            <td class="green"><?php echo $khachHang->getDiDong(); ?></td>
                                        </tr>
                                        <tr>
                                            <td class="col-sm-4" ><i class="fa fa-phone"></i> Điện thoại cố định</td>
                                            <td><?php echo $khachHang->getDienThoaiCoDinh(); ?></td>
                                        </tr>
                                        <tr>
                                            <td><i class="fa fa-envelope-o fa-fw"></i> Email: </td>
                                            <td class="red"><?php echo $khachHang->getEmail(); ?></td>
                                        </tr>
                                        <tr>
                                            <td><i class="fa fa-twitter"></i>Twitter: </td>
                                            <td>
                                                <?php echo $khachHang->getTwitter(); ?>
                                            </td>
                                        </tr>
                                        
                                        <tr>
                                            <td><i class="fa fa-globe"></i> Website</td>
                                            <td><a href=""><?php echo $khachHang->getWebsite(); ?></a></td>
                                        </tr>                                        
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                    <div role="tabpanel" class="tab-pane" id="1">
                        <div class="row">
                            <div class="col-md-6">
                                <?php  
                                $form->setAttribute('action', $this->url('kenh_phan_phoi/crud', array('action' => 'chiTietKhachHang','id'=>$khachHang->getIdDoiTac())));
                                $form->setAttribute('role','form');
                                $form->prepare();
                                echo $this->form()->openTag($form);

                                $khachHangElement=$form->get('khach-hang');
                                echo $this->formHidden($khachHangElement->get('idDoiTac'));
                                ?>     
                                <input type="text" name="hoTenTruoc" value="<?php echo $khachHang->getHoTen(); ?>" hidden="true"/>    
                                    <h4 class="underline">More Info</h4>
                                    <table class="item">
                                        <tbody> 

                                            <tr>
                                                <td>Họ Tên</td>
                                                <td>
                                                <?php
                                                    $khachHangElement->get('hoTen')->setAttribute('class','form-control h5a-input');
                                                    echo $this->formElement($khachHangElement->get('hoTen'));
                                                ?>
                                                </td>
                                            </tr>
                                            <tr>
                                                <td>Địa chỉ</td>
                                                <td>
                                                <?php
                                                    $khachHangElement->get('hoTen')->setAttribute('class','form-control h5a-input');
                                                    echo $this->formElement($khachHangElement->get('diaChi'));
                                                ?>
                                                </td>
                                            </tr>
                                            <tr>
                                                <td>Mô tả</td>
                                                <td>
                                                <?php
                                                    $khachHangElement->get('moTa')->setAttribute('class','form-control h5a-input');
                                                     $khachHangElement->get('moTa')->setAttribute('id','editor');
                                                    $khachHangElement->get('moTa')->setAttribute('rows','6');
                                                    echo $this->formElement($khachHangElement->get('moTa'));
                                                ?> 
                                                </td>
                                            </tr>
                                            <tr>
                                                <td>Kênh phân phối</td>
                                                <td>
                                                <?php
                                                    $khachHangElement->get('idKenhPhanPhoi')->setAttribute('class','form-control h5a-input');
                                                    $khachHangElement->get('idKenhPhanPhoi')->setValueOptions($this->MakeArrayOptionTaxonomy($kenhPhanPhois));
                                                    echo $this->formElement($khachHangElement->get('idKenhPhanPhoi'));
                                                ?>
                                                </td>
                                            </tr>
                                            <tr>
                                                <td>Di động</td>
                                                <td>
                                                <?php
                                                    $khachHangElement->get('diDong')->setAttribute('class','form-control h5a-input');
                                                    echo $this->formElement($khachHangElement->get('diDong'));
                                                ?>
                                                </td>
                                            </tr>
                                            <tr>
                                                <td>Điện thoại cố định</td>
                                                <td>
                                                <?php
                                                    $khachHangElement->get('dienThoaiCoDinh')->setAttribute('class','form-control h5a-input');
                                                    echo $this->formElement($khachHangElement->get('dienThoaiCoDinh'));
                                                ?>
                                                </td>
                                            </tr>

                                            <tr>
                                                <td>Ảnh đại diện</td>
                                                <td>
                                                    <?php if($khachHang->getHinhAnh()){ ?>
                                                    <img  width="350px" height="350px" src="<?php echo $this->basePath(); ?>/img/<?php echo $khachHang->getHinhAnh(); ?>" alt="Ảnh đại diện">
                                                    <?php }else { ?>
                                                        <img  width="350px" height="350px" src="<?php echo $this->basePath(); ?>/img/photo_default.png" alt="Ảnh đại diện">
                                                    <?php } ?>                                                
                                                </td>
                                            </tr>
                                            <tr>
                                                <td>Đổi ảnh đại diện</td>
                                                <td>
                                                <?php
                                                    $khachHangElement->get('hinhAnh')->setAttribute('class','h5a-btn btn btn-primary');
                                                    $khachHangElement->get('hinhAnh')->setAttribute('placeholder','Tải ảnh đại diện');
                                                    echo $this->formElement($khachHangElement->get('hinhAnh'));
                                                ?>
                                                </td>
                                            </tr>

                                            <tr>
                                                <td>Email</td>
                                                <td>
                                                <?php
                                                    $khachHangElement->get('email')->setAttribute('class','form-control h5a-input');
                                                    echo $this->formElement($khachHangElement->get('email'));
                                                ?>
                                                </td>
                                            </tr>
                                            <tr>
                                                <td></td>
                                                <td>
                                                <?php
                                                if($coKiemTraTrung==1)
                                                {
                                                    echo '<span class="label label-warning">Email vừa nhập đã tồn tại</span>';
                                                }
                                                ?>
                                                </td>
                                            </tr>

                                            <tr>
                                                <td>Twitter</td>
                                                <td>
                                                <?php
                                                    $khachHangElement->get('twitter')->setAttribute('class','form-control h5a-input');
                                                    echo $this->formElement($khachHangElement->get('twitter'));
                                                ?>
                                                </td>
                                            </tr>


                                            <tr>
                                                <td>Website</td>
                                                <td>
                                                <?php
                                                    $khachHangElement->get('website')->setAttribute('class','form-control h5a-input');
                                                    echo $this->formElement($khachHangElement->get('website'));
                                                ?>
                                                </td>
                                            </tr>
                                            <tr>
                                                <td> </td>
                                                <td>                                                
                                                <input type="submit" class="full btn h5a-btn btn-success" value="Lưu Thay Đổi"/>
                                                </td>
                                            </tr>
                                        </tbody>
                                    </table>
                            <?php echo $this->form()->closeTag(); ?>
                            </div>
                            <div class="col-md-6">
                            </div>
                        </div>
                    </div>
                    <div role="tabpanel" class="tab-pane" id="2">
                        <div class="container">
                            <div class="row">
                                <table id="dataTables-example" class="">
                                    <thead>
                                        <th><input type="checkbox"/></th>
                                        <th>Ngày</th>
                                        <th>Giao dịch</th>
                                        <th>Diễn giải</th>
                                    </thead>
                                    <tbody>
                                <!-- mở cái này ra để xài theo lịch sử giao dịch
                                    <?php
                                    foreach ($lichSuGiaoDichs as $lichSuGiaoDich) 
                                    {
                                        if($lichSuGiaoDich->getIdHoaDon())
                                        {                                       
                                        
                                    ?>
                                       <tr>
                                            <td><input type="checkbox"/></td>
                                            <td><?php  echo $lichSuGiaoDich->getNgayXuat()->format('d/m/Y'); ?></td>
                                            <td>
                                                <?php                                                 
                                                    echo '<a href="'.$this->url('kenh_phan_phoi/crud', array('action'=>'chiTietDonHang', 'id'=>$lichSuGiaoDich->getIdHoaDon())).'">#'.$lichSuGiaoDich->getMaHoaDon(); 
                                                ?>
                                            </td>
                                            <td>Diễn giải</td>
                                        </tr>
                                    <?php } 
                                    }
                                    ?>
                                -->

                                    <?php
                                    foreach ($hoaDons as $hoaDon) { ?>
                                        <tr>
                                            <td><input type="checkbox"/></td>
                                            <td><?php  echo $hoaDon->getNgayXuat()->format('d/m/Y'); ?></td>
                                            <td>
                                                <?php                                                 
                                                    echo '<a href="'.$this->url('kenh_phan_phoi/crud', array('action'=>'chiTietDonHang', 'id'=>$hoaDon->getIdHoaDon())).'">#'.$hoaDon->getMaHoaDon(); 
                                                ?>
                                            </td>
                                            <td><span class="label label-warning">Mua hàng</span></td>
                                        </tr>
                                    <?php                                        
                                    }
                                    ?>

                                    <?php
                                    foreach ($phieuThus as $phieuThu) { ?>
                                        <tr>
                                            <td><input type="checkbox"/></td>
                                            <td><?php  echo $phieuThu->getNgayThanhToan()->format('d/m/Y'); ?></td>
                                            <td>
                                                <?php                                                 
                                                    echo /*'<a href="'.$this->url('cong_no/crud', array('action'=>'chiTietPhieuThu', 'id'=>$phieuThu->getIdPhieuThu())).'">'.*/$phieuThu->getSoTien(); 
                                                ?>
                                            </td>
                                            <td><span class="label label-success">Đã thanh toán</span></td>
                                        </tr>
                                    <?php                                        
                                    }
                                    ?>
                                        
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<!-- jQuery -->
<script src="<?php echo $this->basePath();?>/js/jquery.js"></script>

<!-- Bootstrap Core JavaScript -->
<script src="<?php echo $this->basePath();?>/js/bootstrap.min.js"></script>

<!-- DataTables JavaScript -->
<script src="<?php echo $this->basePath();?>/js/plugins/dataTables/jquery.dataTables.js"></script>

<!-- editor -->
<script src="<?php echo $this->basePath();?>/js/summernote.min.js"></script>

<script>
    $(document).ready(function() {
        $('#dataTables-example').dataTable({
            "pagingType": "simple",
            "bPaginate": true,
            "bLengthChange": true,
            "bFilter": true,
            "bInfo": true,
            "bAutoWidth": true
        });
    });
    $("#editor").summernote({height:150});
</script>

<script language="JavaScript">
    function xacNhanXoa() {
      var xacNhan=confirm("Bạn thật sự muốn xóa khách hàng này?");
      if(xacNhan==true)
      {
        return true;
      }
      return false;
    }
</script>

