<?php
    $this->headTitle('Chi tiết đơn hàng');
?>
<div class="container">
        <div class="row">
            <div class="col-md-2">
                <div class="h5a-sidebar affix">
                    <span class="breadcrumb row">
                        <a href="<?php echo $this->url('hang_hoa/crud',array('action'=>'index'));?>">/ Kho</a>                        
                        <a href="<?php echo $this->url('kenh_phan_phoi',array('action'=>'index'));?>">/ Khách hàng</a>
                         / Đơn hàng /
                    </span>
                    <ul class="nav h5a-sidenav nav-list accordion">
                        <li>
                            <a href="<?php echo $this->url('kenh_phan_phoi/crud',array('action'=>'donHang'));?>">
                                <i class="fa fa-cubes"></i> Đơn hàng
                            </a>
                        </li>
                        <li>
                            <a href="<?php echo $this->url('kenh_phan_phoi/crud',array('action'=>'doanhThu'));?>">
                                <i class="fa fa-flag-checkered"></i> Doanh thu
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
            <div class="col-md-10" role="main">
                <div class="h5a-docs-section">
                    <div class="page-header">
                        <div class="row">
                            <div class="col-sm-6">
                                <h2>Thông tin khách hàng</h2>
                            </div>
                            <div class="col-sm-6">
                                <div class="pull-right">
                                    <div class="btn-group ">
                                        <button type="button" class="h5a-btn btn btn-default btn-sm">
                                            <i class="fa fa-chevron-left"></i>
                                        </button>                                    
                                        <button type="button" class="h5a-btn btn btn-default btn-sm">
                                            <i class="fa fa-chevron-right"></i>
                                        </button>
                                    </div>
                                     <a href="<?php echo $this->url('kenh_phan_phoi/crud',array('action'=>'exportExcel'));?>"><button type="button" class="h5a-btn btn btn-default btn-sm">Export</button></a>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="box">   
                        
                        <table>
                            <tr>
                                <td>
                                    <b>Họ tên: </b>
                                </td>
                                <td>
                                    <?php echo $hoaDon->getIdDoiTac()->getHoTen(); ?>
                                </td>
                                <td>
                                    <b>Địa chỉ: </b>
                                </td>
                                <td>
                                    <?php echo $hoaDon->getIdDoiTac()->getDiaChi(); ?>
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    <b>Di động:</b> 
                                </td>
                                <td>
                                    <?php echo $hoaDon->getIdDoiTac()->getDiDong(); ?>
                                </td>
                                <td>
                                    <b>Điện thoại cố định: </b>
                                </td>
                                <td>
                                    <?php 
                                        if($hoaDon->getIdDoiTac()->getDienThoaiCoDinh()!=0)
                                            echo $hoaDon->getIdDoiTac()->getDienThoaiCoDinh(); 

                                    ?>
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    <b>Email:  </b>
                                </td>
                                <td>
                                    <?php echo $hoaDon->getIdDoiTac()->getEmail(); ?>
                                </td>
                                <td>
                                    
                                </td>
                                <td>
                                    
                                </td>
                            </tr>
                        </table>
                    </div>
                    <div>
                        <h2>Chi tiết đơn hàng</h2>
                    </div>
                    
                    <div class="box">                        
                        <div class="tab-content">
                            <div role="tabpanel" class="tab-pane active" id="home">
                                <div class="container">
                                    <div class="row">
                                        <table id="dataTables-example" class="">
                                            <thead>
                                                <th><input type="checkbox"/></th>
                                                <th>Tên sản phẩm</th>
                                                <th>Giá</th>
                                                <th>Số lượng</th>   
                                                <th>Thành tiền</th>                                                 
                                            </thead>
                                            <tbody>
                                                
                                            <?php
                                            foreach ($chiTietHoaDons as $chiTietHoaDon) {
                                                echo '<tr>';
                                                    echo '<td><input type="checkbox"/></td>';
                                                    echo '<td><a href="#">'.$chiTietHoaDon->getIdSanPham()->getTenSanPham().'</a></td>';
                                                    echo '<td>'.$chiTietHoaDon->getGia().'</td>';
                                                    echo '<td>'.$chiTietHoaDon->getSoLuong().'</td>';
                                                    echo '<td>'.$chiTietHoaDon->getGia()*$chiTietHoaDon->getSoLuong().'</td>';
                                                echo '</tr>';
                                            }
                                            ?>
                                            </tbody>
                                        </table>
                                    </div>
                                </div>
                            </div>
                            
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- /.container -->

    <!-- jQuery -->
    <script src="<?php echo $this->basePath();?>/js/jquery.js"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="<?php echo $this->basePath();?>/js/bootstrap.min.js"></script>

    <!-- DataTables JavaScript -->
    <script src="<?php echo $this->basePath();?>/js/plugins/dataTables/jquery.dataTables.js"></script>

    <!-- Page-Level Demo Scripts - Tables - Use for reference -->
    <script>
    $(document).ready(function() {
        $('#dataTables-example').dataTable({
            "pagingType": "simple",
            "bPaginate": true,
            "bLengthChange": true,
            "bFilter": true,
            "bInfo": true,
            "bAutoWidth": true
        });
    });
    </script>