<?php
    $this->headTitle('Chi tiết đơn hàng');
?>
<div class="container">
        <div class="row">
            <div class="col-md-2">
                <div class="h5a-sidebar affix">
                    <span class="breadcrumb row">
                        <a href="<?php echo $this->url('hang_hoa/crud',array('action'=>'index'));?>">/ Kho</a>                        
                        <a href="<?php echo $this->url('kenh_phan_phoi',array('action'=>'index'));?>">/ Khách hàng</a>
                         / Đơn hàng /
                    </span>
                    <ul class="nav h5a-sidenav nav-list accordion">
                        <li>
                            <a href="<?php echo $this->url('kenh_phan_phoi/crud',array('action'=>'donHang'));?>">
                                <i class="fa fa-cubes"></i> Đơn hàng
                            </a>
                        </li>
                        <li>
                            <a href="<?php echo $this->url('kenh_phan_phoi/crud',array('action'=>'doanhThu'));?>">
                                <i class="fa fa-flag-checkered"></i> Doanh thu
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
            <div class="col-md-10" role="main">
                <div class="h5a-docs-section">
                    <div class="page-header">
                        <div class="row">
                            <div class="col-sm-6">
                                <h1>Chi tiết đơn hàng</h1>
                            </div>
                            <div class="col-sm-6">
                                <div class="pull-right">
                                    <div class="btn-group ">
                                        <button type="button" class="h5a-btn btn btn-default btn-sm">
                                            <i class="fa fa-chevron-left"></i>
                                        </button>                                    
                                        <button type="button" class="h5a-btn btn btn-default btn-sm">
                                            <i class="fa fa-chevron-right"></i>
                                        </button>
                                    </div>
                                     <button type="button" class="h5a-btn btn btn-default btn-sm">Export</button>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-sm-6">
                        <p>
                            phan văn thanh
                        </p>
                    </div>
                    <div class="box">                        
                        <div class="tab-content">
                            <div role="tabpanel" class="tab-pane active" id="home">
                                <div class="container">
                                    <div class="row">
                                        <table id="dataTables-example" class="">
                                            <thead>
                                                <th><input type="checkbox"/></th>
                                                <th>Đơn hàng</th>
                                                <th>Ngày</th>
                                                <th>Khách hàng</th>
                                                <th>Thanh toán</th>
                                                <th>Tổng tiền</th>
                                            </thead>
                                            <tbody>
                                                <tr>
                                                    <td><input type="checkbox"/></td>
                                                    <td><a href="khachHang.html">#2-3323</a></td>
                                                    <td>11/11/2014</td>
                                                    <td><a href="khachHang.html">Trường Đại học Trà Vinh</a></td>
                                                    <td><span class="label label-warning">Ghi nợ</span></td>
                                                    <td>230.000</td>
                                                </tr>
                                                <tr>
                                                    <td><input type="checkbox"/></td>
                                                    <td><a href="khachHang.html">#2-3323</a></td>
                                                    <td>11/11/2014</td>
                                                    <td><a href="khachHang.html">Trường Đại học Trà Vinh</a></td>
                                                    <td><span class="label label-warning">Ghi nợ</span></td>
                                                    <td>230.000</td>
                                                </tr>
                                                <tr>
                                                    <td><input type="checkbox"/></td>
                                                    <td><a href="khachHang.html">#2-3323</a></td>
                                                    <td>11/11/2014</td>
                                                    <td><a href="khachHang.html">Trường Đại học Trà Vinh</a></td>
                                                    <td><span class="label label-success">Đã thanh toán</span></td>
                                                    <td>230.000</td>
                                                </tr>
                                                <tr>
                                                    <td><input type="checkbox"/></td>
                                                    <td><a href="khachHang.html">#2-3323</a></td>
                                                    <td>11/11/2014</td>
                                                    <td><a href="khachHang.html">Trường Đại học Trà Vinh</a></td>
                                                    <td><span class="label label-warning">Ghi nợ</span></td>
                                                    <td>230.000</td>
                                                </tr>
                                                <tr>
                                                    <td><input type="checkbox"/></td>
                                                    <td><a href="khachHang.html">#2-3323</a></td>
                                                    <td>11/11/2014</td>
                                                    <td><a href="khachHang.html">Trường Đại học Trà Vinh</a></td>
                                                    <td><span class="label label-warning">Ghi nợ</span></td>
                                                    <td>230.000</td>
                                                </tr>
                                                <tr>
                                                    <td><input type="checkbox"/></td>
                                                    <td><a href="khachHang.html">#2-3323</a></td>
                                                    <td>11/11/2014</td>
                                                    <td><a href="khachHang.html">Trường Đại học Trà Vinh</a></td>
                                                    <td><span class="label label-warning">Ghi nợ</span></td>
                                                    <td>230.000</td>
                                                </tr>
                                                <tr>
                                                    <td><input type="checkbox"/></td>
                                                    <td><a href="khachHang.html">#2-3323</a></td>
                                                    <td>11/11/2014</td>
                                                    <td><a href="khachHang.html">Trường Đại học Trà Vinh</a></td>
                                                    <td><span class="label label-warning">Ghi nợ</span></td>
                                                    <td>230.000</td>
                                                </tr>
                                                <tr>
                                                    <td><input type="checkbox"/></td>
                                                    <td><a href="khachHang.html">#2-3323</a></td>
                                                    <td>11/11/2014</td>
                                                    <td><a href="khachHang.html">Trường Đại học Trà Vinh</a></td>
                                                    <td><span class="label label-warning">Ghi nợ</span></td>
                                                    <td>230.000</td>
                                                </tr>
                                                <tr>
                                                    <td><input type="checkbox"/></td>
                                                    <td><a href="khachHang.html">#2-3323</a></td>
                                                    <td>11/11/2014</td>
                                                    <td><a href="khachHang.html">Trường Đại học Trà Vinh</a></td>
                                                    <td><span class="label label-warning">Ghi nợ</span></td>
                                                    <td>230.000</td>
                                                </tr>
                                                <tr>
                                                    <td><input type="checkbox"/></td>
                                                    <td><a href="khachHang.html">#2-3323</a></td>
                                                    <td>11/11/2014</td>
                                                    <td><a href="khachHang.html">Trường Đại học Trà Vinh</a></td>
                                                    <td><span class="label label-warning">Ghi nợ</span></td>
                                                    <td>230.000</td>
                                                </tr>
                                                <tr>
                                                    <td><input type="checkbox"/></td>
                                                    <td><a href="khachHang.html">#2-3323</a></td>
                                                    <td>11/11/2014</td>
                                                    <td><a href="khachHang.html">Trường Đại học Trà Vinh</a></td>
                                                    <td><span class="label label-warning">Ghi nợ</span></td>
                                                    <td>230.000</td>
                                                </tr>
                                                <tr>
                                                    <td><input type="checkbox"/></td>
                                                    <td><a href="khachHang.html">#2-3323</a></td>
                                                    <td>11/11/2014</td>
                                                    <td><a href="khachHang.html">Trường Đại học Trà Vinh</a></td>
                                                    <td><span class="label label-warning">Ghi nợ</span></td>
                                                    <td>230.000</td>
                                                </tr>
                                                <tr>
                                                    <td><input type="checkbox"/></td>
                                                    <td><a href="khachHang.html">#2-3323</a></td>
                                                    <td>11/11/2014</td>
                                                    <td><a href="khachHang.html">Trường Đại học Trà Vinh</a></td>
                                                    <td><span class="label label-warning">Ghi nợ</span></td>
                                                    <td>230.000</td>
                                                </tr>
                                            </tbody>
                                        </table>
                                    </div>
                                </div>
                            </div>
                            
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- /.container -->

    <!-- jQuery -->
    <script src="<?php echo $this->basePath();?>/js/jquery.js"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="<?php echo $this->basePath();?>/js/bootstrap.min.js"></script>

    <!-- DataTables JavaScript -->
    <script src="<?php echo $this->basePath();?>/js/plugins/dataTables/jquery.dataTables.js"></script>

    <!-- Page-Level Demo Scripts - Tables - Use for reference -->
    <script>
    $(document).ready(function() {
        $('#dataTables-example').dataTable({
            "pagingType": "simple",
            "bPaginate": true,
            "bLengthChange": true,
            "bFilter": true,
            "bInfo": true,
            "bAutoWidth": true
        });
    });
    </script>