<?php
    $this->headTitle('Chi tiết đơn hàng');
?>
<style type="text/css">   
    @media print {
        .col-sm-3 {display: none;}
        .form-group{display: none;}
        .col-md-2{display: none;}
        .col-sm-6{margin-top: -80px}
        .pull-right{display: none;}        
        .tb{width: 900px; margin-left: -10px; margin-top: -30px;}
        .td{width: 80px;}        
        table {display: table;}
        .dataTables_length{display: none;}
        .dataTables_filter{display: none;}
        .dataTables_info{display: none;}
        #dataTables-example_paginate{display: none;}
        .sorting_asc{display: none;}
        .sorting_1 {display: none;}
        #link{display: none;}
        .lb{display: block;}
        #destination-search{display: none;}        
    }
</style>

<div class="row">
    <div class="col-md-2">
        <div class="h5a-sidebar affix">
            <span class="breadcrumb row">
                <a href="<?php echo $this->url('hang_hoa/crud',array('action'=>'index'));?>">/ Kho</a>                        
                <a href="<?php echo $this->url('kenh_phan_phoi',array('action'=>'index'));?>">/ Khách hàng</a>
                 / Đơn hàng /
            </span>
            <ul class="nav h5a-sidenav nav-list accordion">
                <li>
                    <a href="<?php echo $this->url('loi_nhuan/crud',array('action'=>'index'));?>">
                        <i class="fa fa-flag-checkered"></i> Doanh thu
                    </a>
                </li>
                <li>
                    <a href="<?php echo $this->url('loi_nhuan/crud',array('action'=>'don-hang'));?>">
                        <i class="fa fa-cubes"></i> Phiếu xuất
                    </a>
                </li>
                <li>
                    <a href="<?php echo $this->url('loi_nhuan/crud',array('action'=>'phieu-nhap'));?>">
                        <i class="fa fa-tasks"></i> Phiếu nhập
                    </a>
                </li>
            </ul>
        </div>
    </div>
    <div class="col-md-10" role="main">
        <div class="h5a-docs-section">
            <div class="page-header">
                <div class="row">
                    <div class="col-sm-6">
                        <h1>Chi tiết đơn hàng</h1>
                    </div>
                    <div class="col-sm-6">
                        <div class="pull-right">
                            <div class="btn-group ">
                                <button id="btPrev" type="button" class="h5a-btn btn btn-default btn-sm">
                                    <i class="fa fa-chevron-left"></i>
                                </button>                                    
                                <button id="btNext" type="button" class="h5a-btn btn btn-default btn-sm">
                                    <i class="fa fa-chevron-right"></i>
                                </button>
                            </div>
                                <button type="button" class="h5a-btn btn btn-default btn-sm" onclick="return inDonHangFunction();">In đơn hàng</button>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-sm-6">
                    <b>Tên khách hàng: </b><a href="<?php echo $this->url('kenh_phan_phoi/crud',array('action'=>'chi-tiet-khach-hang','id'=>$hoaDon->getIdDoiTac()->getIdDoiTac())); ?>"><?php echo $hoaDon->getIdDoiTac()->getHoTen(); ?></a></div>
                </div>
            
            <div class="box">                        
                <div class="tab-content">
                    <div role="tabpanel" class="tab-pane active" id="home">
                        <div class="container">
                            <div class="row">
                                <table id="dataTables-example" class="">
                                    <thead>
                                        <th><input type="checkbox"/></th>
                                        <th>Tên sản phẩm</th>
                                        <th>Giá</th>
                                        <th>Số lượng</th>   
                                        <th>Thành tiền</th>                                                 
                                    </thead>
                                    <tbody>
                                        
                                    <?php
                                    foreach ($chiTietHoaDons as $chiTietHoaDon) {
                                        echo '<tr>';
                                            echo '<td><input type="checkbox"/></td>';
                                            echo '<td><a id="link" href="'.$this->url('hang_hoa/crud', array('action'=>'san-pham', 'id'=>$chiTietHoaDon->getIdSanPham()->getIdSanPham())).'">'.$chiTietHoaDon->getIdSanPham()->getTenSanPham().'</a><label hidden="true" class="lb">'.$chiTietHoaDon->getIdSanPham()->getTenSanPham().'</label></td>';
                                            echo '<td>'.$chiTietHoaDon->getGia().'</td>';
                                            echo '<td>'.$chiTietHoaDon->getSoLuong().'</td>';
                                            echo '<td>'.$chiTietHoaDon->getGia()*$chiTietHoaDon->getSoLuong().'</td>';
                                        echo '</tr>';
                                    }
                                    ?>
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                    
                </div>
            </div>
        </div>
    </div>
</div>

<!-- /.container -->

    <!-- jQuery -->
    <script src="<?php echo $this->basePath();?>/js/jquery.js"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="<?php echo $this->basePath();?>/js/bootstrap.min.js"></script>

    <!-- DataTables JavaScript -->
    <script src="<?php echo $this->basePath();?>/js/plugins/dataTables/jquery.dataTables.js"></script>

    <!-- Page-Level Demo Scripts - Tables - Use for reference -->
    <script>
    $(document).ready(function() {
        $('#dataTables-example').dataTable({
            "pagingType": "simple",
            "bPaginate": true,
            "bLengthChange": true,
            "bFilter": true,
            "bInfo": true,
            "bAutoWidth": true
        });
    });

    inDonHangFunction=function()
    {
        window.print();        
    }

    $('#btPrev').click(function(){
        document.getElementById('dataTables-example_previous').click();
    });

    $('#btNext').click(function(){
        document.getElementById('dataTables-example_next').click();
    }); 
    </script>