<?php
    $this->headTitle('Chi tiết phiếu nhập');
?>

<div class="row">
    <div class="col-md-2">
        <div class="h5a-sidebar affix">
            <span class="breadcrumb row">
                <a href="<?php echo $this->url('hang_hoa/crud',array('action'=>'index'));?>">/ Kho</a>                        
                <a href="<?php echo $this->url('kenh_phan_phoi',array('action'=>'index'));?>">/ Khách hàng</a>
                 / Đơn hàng /
            </span>
            <ul class="nav h5a-sidenav nav-list accordion">
                <li>
                    <a href="<?php echo $this->url('loi_nhuan/crud',array('action'=>'index'));?>">
                        <i class="fa fa-flag-checkered"></i> Doanh thu
                    </a>
                </li>
                <li>
                    <a href="<?php echo $this->url('loi_nhuan/crud',array('action'=>'don-hang'));?>">
                        <i class="fa fa-cubes"></i> Phiếu xuất
                    </a>
                </li>
                <li>
                    <a href="<?php echo $this->url('loi_nhuan/crud',array('action'=>'phieu-nhap'));?>">
                        <i class="fa fa-tasks"></i> Phiếu nhập
                    </a>
                </li>
            </ul>
        </div>
    </div>
    <div class="col-md-10" role="main">
        <div class="h5a-docs-section">
            <div class="row">
                <div class="col-sm-6">
                    
                </div>
            </div>
            <?php //die(var_dump($phieuNhap)); ?>
            <div  class="tbIn">
                <table class="table">
                    <tr style="text-align: -moz-center; border-style:hidden">
                        <td>
                            <table border="0" class="tb">
                                <tr>
                                    <td style="width:60%">
                                        <b>
                                            CTY CP SÁCH &amp; TB TRƯỜNG HỌC TRÀ VINH</br>
                                            3A Trưng Nữ Vương Phường 1 TP.Trà Vinh</br>
                                            Mã số thuế: 2100 290 521
                                        </b>
                                    </td>
                                    <td style="text-align:center">
                                        <b>Mẫ số: 01 - TT</b></br>
                                        (Ban hành theo QĐ số: 15/2006/QĐ-BTC ngày 20/3/2006 của Bộ trưởng BTC)
                                    </td>            
                                </tr>
                            </table>

                            <table border="0" style="width:65%; margin-left:220px"  class="tb">
                                <tr>
                                    <td style="width:50%; padding:0px 0px 0px 30px; font-size:16px; font-weight:bold">PHIẾU NHẬP KHO</td>
                                    <td></td>
                                </tr>
                                <tr>
                                    <td style="padding:0px;">Ngày <?php echo $phieuNhap->getNgayNhap()->format('d'); ?> tháng <?php echo $phieuNhap->getNgayNhap()->format('m'); ?> năm <?php echo $phieuNhap->getNgayNhap()->format('Y');?></td>
                                    <td style="padding:0px;">
                                        Nợ: ........................................
                                    </td>
                                </tr>
                                <tr>
                                    <td style="padding:0px;">
                                        Số: ........................................<div style="margin-left:30px; margin-top:-22px;"><?php echo $phieuNhap->getMaPhieuNhap(); ?> </div>
                                    </td>
                                    <td style="padding:0px;">
                                        Có: ........................................
                                    </td>
                                </tr>
                            </table>

                            <table border="0"  class="tb">
                                <tr>
                                    <td colspan="4">
                                        - Họ và tên người giao: <?php echo $phieuNhap->getIdDoiTac()->getHoTen(); ?>
                                    </td>
                                </tr>
                                <tr>
                                    <td style="width:200px">
                                        - Theo.....................
                                    </td>
                                    <td style="width:100px">
                                        số....................
                                    </td>
                                    <td style="width:215px">
                                        ngày <?php echo $phieuNhap->getNgayNhap()->format('d'); ?> tháng <?php echo $phieuNhap->getNgayNhap()->format('m'); ?>  năm <?php echo $phieuNhap->getNgayNhap()->format('Y'); ?> 
                                    </td>
                                    <td>                            
                                        của...............................................
                                    </td>
                                </tr>
                                <tr>
                                    <td colspan="2">                        
                                        Nhập tại kho:........................................
                                    </td>                    
                                    <td colspan="2">
                                        Địa điểm............................................................................................
                                    </td>
                                </tr>
                                <tr><td></td></tr>
                            </table>

                            <table border="1" id="tbSanPham">
                                <tr style="text-align:center">
                                    <td rowspan="2" style="width:45px">STT</td>
                                    <td rowspan="2">Tên, nhãn hiệu quy cách, phẩm chất vật tư, dụng cụ sản phẩm, hàng hóa</td>
                                    <td rowspan="2" class="td">Mã số</td>
                                    <td rowspan="2" class="td">Đơn vị tính</td>
                                    <td colspan="2" style="width:300px">Số lượng</td>
                                    <td rowspan="2" class="td">Đơn giá</td>
                                    <td rowspan="2" class="td">Thành tiền</br>(vnđ)</td>
                                </tr>
                                <tr style="text-align:center">
                                    <td>Theo chứng từ</td>
                                    <td>Thực nhập</td>
                                </tr>
                                
                                <?php
                                $stt=0;
                                foreach ($phieuNhap->getCtPhieuNhaps() as $chiTietPhieuNhap) {
                                    $stt++;
                                ?>
                                    <tr style="text-align:center">
                                        <td><?php echo $stt; ?></td>
                                        <td><?php echo $chiTietPhieuNhap->getIdSanPham()->getTenSanPham(); ?></td>
                                        <td><?php echo $chiTietPhieuNhap->getIdSanPham()->getMaSanPham(); ?></td>
                                        <td><?php echo $chiTietPhieuNhap->getIdSanPham()->getIdDonViTinh()->getTermId()->getName(); ?></td>
                                        <td>1</td>
                                        <td><?php echo number_format($chiTietPhieuNhap->getSoLuong(),'0','',' '); ?></td>
                                        <td><?php echo number_format($chiTietPhieuNhap->getGiaNhap(),'0','',' '); ?></td>
                                        <td width="100px">
                                        <?php 
                                            $thanhTien=(float)$chiTietPhieuNhap->getSoLuong()*$chiTietPhieuNhap->getGiaNhap();
                                            echo number_format($thanhTien,'0','',' '); ?>
                                        </td>
                                    </tr> 
                                <?php
                                }
                                ?>                   
                            </table>
                        </td>
                    </tr>
                    <tr style="border-style:hidden">
                        <td style="padding-left:20px">- Tổng số tiền (viết bằng chữ): <span id="tongSoTien"></span>&nbsp;đồng</td>
                    </tr>
                    <tr style="border-style:hidden">
                        <td style="padding-left:20px">
                            - Số chứng từ gốc kèm theo: .....................................................................................................................................
                        </td>
                    </tr>
                    <tr style="text-align: -moz-center">
                        <td>
                            <table border="0" class="tb" style="width:100%;">
                                <tr>
                                    <td colspan="4" style="text-align:right">Ngày <?php echo $phieuNhap->getNgayNhap()->format('d'); ?> tháng <?php echo $phieuNhap->getNgayNhap()->format('m'); ?> năm <?php echo $phieuNhap->getNgayNhap()->format('Y'); ?></td>
                                </tr>
                                <tr style="text-align: center;">
                                    <td>
                                        Người lập phiếu</br>(Ký, họ tên)
                                    </td>
                                    <td>
                                        Người giao hàng</br>(Ký, họ tên)
                                    </td>
                                    <td>
                                        Thủ kho</br>(Ký, họ tên)
                                    </td>
                                    <td>
                                        Kế toán trưởng<br>(Hoặc bộ phận có nhu cầu nhập)</br>(Ký, họ tên)
                                    </td>
                                </tr>
                                <tr>
                                    <td style="height:100px"></td>
                                </tr>  
                                <tr style="text-align: center;">
                                    <td>
                                        <b><?php echo $phieuNhap->getIdUserNv()->getHoTen(); ?></b>
                                    </td>
                                    <td>
                                        <b><?php echo $phieuNhap->getIdDoiTac()->getHoTen(); ?></b>
                                    </td>
                                    <td>
                                        
                                    </td>
                                    <td>
                                       
                                    </td>
                                </tr>                  
                            </table>
                        </td>
                    </tr>
                </table>
            </div>
        </div>
    </div>
</div>
<!-- /.container -->

    <!-- jQuery -->
    <script src="<?php echo $this->basePath();?>/js/jquery.js"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="<?php echo $this->basePath();?>/js/bootstrap.min.js"></script>

    <!-- DataTables JavaScript -->
    <script src="<?php echo $this->basePath();?>/js/plugins/dataTables/jquery.dataTables.js"></script>

    <!-- Page-Level Demo Scripts - Tables - Use for reference -->
    <script>
    $(document).ready(function() {
        $('#dataTables-example').dataTable({
            "pagingType": "simple",
            "bPaginate": true,
            "bLengthChange": true,
            "bFilter": true,
            "bInfo": true,
            "bAutoWidth": true
        });
    });
    </script>