<?php $this->headTitle('Thông tin nhà cung cấp'); ?>

<div class="row">
    <div class="col-md-2">
        <div class="h5a-sidebar affix">
            <span class="breadcrumb row">
                <a href="<?php echo $this->url('hang_hoa/crud',array('action'=>'index'));?>">/ Kho</a>
                <a href="<?php echo $this->url('kenh_phan_phoi');?>">/ Khách hàng</a>
                 / #xxx /
            </span>
            <ul class="nav h5a-sidenav nav-list accordion">
                <li>
                    <a href="<?php echo $this->url('kenh_phan_phoi/crud',array('action'=>'index'));?>">
                        <i class="glyphicon glyphicon-open"></i> Khách hàng
                    </a>
                </li> 
                <li>
                    <a href="<?php echo $this->url('kenh_phan_phoi/crud',array('action'=>'nhaCungCap'));?>">
                        <i class="glyphicon glyphicon-save"></i> Nhà cung cấp
                    </a>
                </li>                
                
            </ul>
        </div>
    </div>
    <div class="col-md-10" role="main">
        <div class="h5a-docs-section">
            
    </div>
</div>

<!-- /.container -->

<div class="container h5a-container gray">
    <div class="row">
        <div class="col-md-10 col-md-offset-2">
            <h1>
                <?php if($nhaCungCap->getHinhAnh()){ ?>
                    <img class="pull-left img-circle" src="<?php echo $this->basePath(); ?>/img/<?php echo $nhaCungCap->getHinhAnh(); ?>" width="40px" height="40px" alt="Ảnh đại diện">
                <?php } else{ ?>
                    <img class="pull-left img-circle" width="40px" height="40px" src="<?php echo $this->basePath(); ?>/img/photo_default.png" alt="Ảnh đại diện">
                <?php } ?>
                <?php echo $nhaCungCap->getHoTen(); ?>
            </h1>
            <?php 
                    $flash=$this->flashMessenger();
                    $flash->setMessageOpenFormat('<div%s>
                     <button type="button" class="close" data-dismiss="alert" aria-hidden="true">
                         &times;
                     </button>
                     <ul><li>')
                     ->setMessageSeparatorString('</li><li>')
                     ->setMessageCloseString('</li></ul></div>');

                     echo $flash->render('error',   array('alert', 'alert-dismissable', 'alert-danger'));
                     echo $flash->render('info',    array('alert', 'alert-dismissable', 'alert-info'));
                     echo $flash->render('default', array('alert', 'alert-dismissable', 'alert-warning'));
                     echo $flash->render('success', array('alert', 'alert-dismissable', 'alert-success'));
            ?>
            <div class="btn-group pull-right">
                <a href="<?php echo $this->url('kenh_phan_phoi/crud', array('action'=>'xoaNhaCungCap','id'=>$nhaCungCap->getIdDoiTac())); ?>" class="btn h5a-btn btn-danger btn-xs" onclick="return xacNhanXoa()"><i class="fa fa-times"></i> Xóa nhà cung cấp</a> 
                <!-- <a class="btn h5a-btn btn-primary btn-xs"><i class="fa fa-refresh"></i> Refresh Item</a> -->
            </div>
            <p>
          
            </p>
            <div class="tabbable">
                <ul class="nav nav-tabs" role="tablist" id="myTab">
                    <li role="presentation" class="active">
                        <a href="#home" role="tab" data-toggle="tab">Xem chi tiết</a>
                    </li>
                    <li role="presentation">
                        <a href="#1" role="tab" data-toggle="tab">Cập nhật</a>
                    </li>
                    <li role="presentation">
                        <a href="#2" role="tab" data-toggle="tab">Lịch sử giao dịch</a>
                    </li>
                </ul>
                <div class="tab-content">
                    <div role="tabpanel" class="tab-pane active" id="home">
                        <div class="row">
                            <div class="col-md-6">
                                <div class="thumbnail">
                                    <?php if($nhaCungCap->getHinhAnh()){ ?>
                                        <img class="img-responsive" src="<?php echo $this->basePath(); ?>/img/<?php echo $nhaCungCap->getHinhAnh(); ?>" alt="Ảnh đại diện">
                                    <?php } else{ ?>
                                        <img class="img-responsive" src="<?php echo $this->basePath(); ?>/img/photo_default.png" alt="Ảnh đại diện">
                                    <?php } ?>
                                    
                                </div>
                            </div>
                            <div class="col-md-6">
                                <h4>Nhà cung cấp: <?php echo $nhaCungCap->getHoTen(); ?></h4>
                                <p><?php echo $nhaCungCap->getMoTa(); ?> </p>
                                <h4 class="underline">Thông tin chi tiết</h4>
                                <table class="item">
                                    <tbody>
                                        <tr>
                                            <td><i class="fa fa-user"></i> Họ Tên</td>
                                            <td><?php echo $nhaCungCap->getHoTen(); ?></td>
                                        </tr>
                                        <tr>
                                            <td><i class="fa fa-home"></i>Địa chỉ</td>
                                            <td><?php echo $nhaCungCap->getDiaChi(); ?></td>
                                        </tr>
                                        
                                        <tr>
                                            <td><i class="fa fa-mobile-phone"></i> Di động</td>
                                            <td class="green"><?php echo $nhaCungCap->getDiDong(); ?></td>
                                        </tr>
                                        <tr>
                                            <td class="col-sm-4" ><i class="fa fa-phone"></i> Điện thoại cố định</td>
                                            <td><?php echo $nhaCungCap->getDienThoaiCoDinh(); ?></td>
                                        </tr>
                                        <tr>
                                            <td><i class="fa fa-envelope-o fa-fw"></i> Email: </td>
                                            <td class="red"><?php echo $nhaCungCap->getEmail(); ?></td>
                                        </tr>
                                        <tr>
                                            <td><i class="fa fa-twitter"></i>Twitter: </td>
                                            <td>
                                                <?php echo $nhaCungCap->getTwitter(); ?>
                                            </td>
                                        </tr>
                                        
                                        <tr>
                                            <td><i class="fa fa-globe"></i> Website</td>
                                            <td><a href=""><?php echo $nhaCungCap->getWebsite(); ?></a></td>
                                        </tr>                                        
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                    <div role="tabpanel" class="tab-pane" id="1">
                        <div class="row">
                            <div class="col-md-6">
                                <?php  
                                $form->setAttribute('action', $this->url('kenh_phan_phoi/crud', array('action' => 'chiTietNhaCungCap','id'=>$nhaCungCap->getIdDoiTac())));
                                $form->setAttribute('role','form');
                                $form->prepare();
                                echo $this->form()->openTag($form);

                                $nhaCungCapElement=$form->get('khach-hang');
                                echo $this->formHidden($nhaCungCapElement->get('idDoiTac'));
                                $nhaCungCapElement->get('idKenhPhanPhoi')->setAttribute('value','39');
                                echo $this->formHidden($nhaCungCapElement->get('idKenhPhanPhoi'));

                                
                                ?>   
                                <input type="text" name="hoTenTruoc" value="<?php echo $nhaCungCap->getHoTen(); ?>" hidden="true"/>                              
                                    <p>
                                                                              
                                    </p>
                                    <h4 class="underline">More Info</h4>
                                    <table class="item">
                                        <tbody>
                                            <tr>
                                                <td> </td>
                                                <td>
                                                <?php
                                                if($coKiemTraTrung==1)
                                                {
                                                    echo '<span class="label label-warning">Tên vừa nhập đã tồn tại</span>';                        
                                                }
                                                ?>
                                                </td>
                                            </tr>
                                            <tr>
                                                <td>Họ Tên</td>
                                                <td>
                                                <?php
                                                    $nhaCungCapElement->get('hoTen')->setAttribute('class','form-control h5a-input');
                                                    echo $this->formElement($nhaCungCapElement->get('hoTen'));
                                                ?>
                                                </td>
                                            </tr>
                                            <tr>
                                                <td>Địa chỉ</td>
                                                <td>
                                                <?php
                                                    $nhaCungCapElement->get('hoTen')->setAttribute('class','form-control h5a-input');
                                                    echo $this->formElement($nhaCungCapElement->get('diaChi'));
                                                ?>
                                                </td>
                                            </tr>
                                            <tr>
                                                <td>Mô tả</td>
                                                <td>
                                                <?php
                                                    $nhaCungCapElement->get('moTa')->setAttribute('class','form-control h5a-input');
                                                    $nhaCungCapElement->get('moTa')->setAttribute('id','editor');
                                                    $nhaCungCapElement->get('moTa')->setAttribute('rows','6');
                                                    echo $this->formElement($nhaCungCapElement->get('moTa'));
                                                ?> 
                                                </td>
                                            </tr>
                                            
                                            <tr>
                                                <td>Di động</td>
                                                <td>
                                                <?php
                                                    $nhaCungCapElement->get('diDong')->setAttribute('class','form-control h5a-input');
                                                    echo $this->formElement($nhaCungCapElement->get('diDong'));
                                                ?>
                                                </td>
                                            </tr>
                                            <tr>
                                                <td>Điện thoại cố định</td>
                                                <td>
                                                <?php
                                                    $nhaCungCapElement->get('dienThoaiCoDinh')->setAttribute('class','form-control h5a-input');
                                                    echo $this->formElement($nhaCungCapElement->get('dienThoaiCoDinh'));
                                                ?>
                                                </td>
                                            </tr>

                                            <tr>
                                                <td>Ảnh đại diện</td>
                                                <td>
                                                    <?php if($nhaCungCap->getHinhAnh()){ ?>
                                                        <img width="350px" height="350px" src="<?php echo $this->basePath(); ?>/img/<?php echo $nhaCungCap->getHinhAnh(); ?>" alt="Ảnh đại diện">
                                                    <?php } else{ ?>
                                                        <img width="350px" height="350px" src="<?php echo $this->basePath(); ?>/img/photo_default.png" alt="Ảnh đại diện">
                                                    <?php } ?>
                                                </td>
                                            </tr>
                                            <tr>
                                                <td>Đổi ảnh đại diện</td>
                                                <td>
                                                <?php
                                                    $nhaCungCapElement->get('hinhAnh')->setAttribute('class','h5a-btn btn btn-primary');
                                                    $nhaCungCapElement->get('hinhAnh')->setAttribute('placeholder','Tải ảnh đại diện');
                                                    echo $this->formElement($nhaCungCapElement->get('hinhAnh'));
                                                ?>
                                                </td>
                                            </tr>

                                            <tr>
                                                <td>Email</td>
                                                <td>
                                                <?php
                                                    $nhaCungCapElement->get('email')->setAttribute('class','form-control h5a-input');
                                                    echo $this->formElement($nhaCungCapElement->get('email'));
                                                ?>
                                                </td>
                                            </tr>

                                            <tr>
                                                <td>Twitter</td>
                                                <td>
                                                <?php
                                                    $nhaCungCapElement->get('twitter')->setAttribute('class','form-control h5a-input');
                                                    echo $this->formElement($nhaCungCapElement->get('twitter'));
                                                ?>
                                                </td>
                                            </tr>


                                            <tr>
                                                <td>Website</td>
                                                <td>
                                                <?php
                                                    $nhaCungCapElement->get('website')->setAttribute('class','form-control h5a-input');
                                                    echo $this->formElement($nhaCungCapElement->get('website'));
                                                ?>
                                                </td>
                                            </tr>
                                            <tr>
                                                <td> </td>
                                                <td>                                                
                                                <input type="submit" class="full btn h5a-btn btn-success" value="Lưu Thay Đổi"/>
                                                </td>
                                            </tr>
                                            

                                        </tbody>
                                    </table>
                            <?php echo $this->form()->closeTag(); ?>
                            </div>
                            <div class="col-md-6">

                            </div>
                        </div>
                    </div>
                    <div role="tabpanel" class="tab-pane" id="2">
                        <div class="container">
                            <div class="row">
                                <table id="dataTables-example" class="">
                                    <thead>
                                        <th><input type="checkbox"/></th>
                                        <th>Ngày</th>
                                        <th>Giao dịch</th>
                                        <th>Diễn giải</th>
                                    </thead>
                                    <tbody>
                                    <!--<?php
                                    foreach ($lichSuGiaoDichs as $lichSuGiaoDich) 
                                    {?>
                                       <tr>
                                            <td><input type="checkbox"/></td>
                                            <td><?php  echo $lichSuGiaoDich->getNgayNhap()->format('d/m/Y'); ?></td>
                                            <td>
                                                <?php                                                 
                                                    echo '<a href="'.$this->url('kenh_phan_phoi/crud', array('action'=>'chiTietPhieuNhap', 'id'=>$lichSuGiaoDich->getIdPhieuNhap())).'">#'.$lichSuGiaoDich->getMaPhieuNhap(); 
                                                ?>
                                            </td>
                                        </tr>
                                    <?php } ?>
                                     -->
                                     <?php
                                    foreach ($phieuNhaps as $phieuNhap) 
                                    {?>
                                       <tr>
                                            <td><input type="checkbox"/></td>
                                            <td><?php  echo $phieuNhap->getNgayNhap()->format('d/m/Y'); ?></td>
                                            <td>
                                                <?php                                                 
                                                    echo '<a href="'.$this->url('kenh_phan_phoi/crud', array('action'=>'chiTietPhieuNhap', 'id'=>$phieuNhap->getIdPhieuNhap())).'">#'.$phieuNhap->getMaPhieuNhap(); 
                                                ?>
                                            </td>
                                            <td><span class="label label-warning">Nhập hàng</span></td>
                                        </tr>
                                    <?php } ?>

                                    <?php
                                    foreach ($phieuChis as $phieuChi) 
                                    {?>
                                       <tr>
                                            <td><input type="checkbox"/></td>
                                            <td><?php  echo $phieuChi->getNgayThanhToan()->format('d/m/Y'); ?></td>
                                            <td>
                                                <?php                                                 
                                                    echo /*'<a href="'.$this->url('kenh_phan_phoi/crud', array('action'=>'chiTietPhieuChi', 'id'=>$phieuChi->getIdPhieuChi())).'">#'.*/$phieuChi->getSoTien(); 
                                                ?>
                                            </td>
                                            <td><span class="label label-success">Đã thanh toán</span></td>
                                        </tr>
                                    <?php } ?>
                                           
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<!-- jQuery -->
<script src="<?php echo $this->basePath();?>/js/jquery.js"></script>

<!-- Bootstrap Core JavaScript -->
<script src="<?php echo $this->basePath();?>/js/bootstrap.min.js"></script>

<!-- DataTables JavaScript -->
<script src="<?php echo $this->basePath();?>/js/plugins/dataTables/jquery.dataTables.js"></script>

<!-- editor -->
<script src="<?php echo $this->basePath();?>/js/summernote.min.js"></script>

<script>
    $(document).ready(function() {
        $('#dataTables-example').dataTable({
            "pagingType": "simple",
            "bPaginate": true,
            "bLengthChange": true,
            "bFilter": true,
            "bInfo": true,
            "bAutoWidth": true
        });
    });
$("#editor").summernote({height:150});
</script>

<script language="JavaScript">
    function xacNhanXoa() {
      var xacNhan=confirm("Bạn thật sự muốn xóa khách hàng này?");
      if(xacNhan==true)
      {
        return true;
      }
      return false;
    }
</script>
