<?php
     $this->headTitle('Kênh phân phối');
?>

<div class="row">
    <div class="col-md-2">
        <div class="h5a-sidebar affix">
            <span class="breadcrumb row">
                <a href="<?php echo $this->url('hang_hoa/crud',array('action'=>'index'));?>">/ Kho</a>
                 / Khách hàng /
            </span>
            <ul class="nav h5a-sidenav nav-list accordion">
                <li>
                    <a href="<?php echo $this->url('kenh_phan_phoi/crud',array('action'=>'index'));?>">
                        <i class="glyphicon glyphicon-open"></i> Khách hàng
                    </a>
                </li> 
                <li>
                    <a href="<?php echo $this->url('kenh_phan_phoi/crud',array('action'=>'nha-cung-cap'));?>">
                        <i class="glyphicon glyphicon-save"></i> Nhà cung cấp
                    </a>
                </li>                 
               
            </ul>
        </div>
    </div>
    <div class="col-md-10" role="main">
        <div class="h5a-docs-section">
            <div class="page-header">
                <div class="row">
                    <div class="col-sm-6">
                        <h1>Khách hàng</h1>
                    </div>
                    <div class="col-sm-6">
                        <div class="pull-right">
                            <div class="btn-group ">
                                <button id="btPrev" type="button" class="h5a-btn btn btn-default btn-sm">
                                    <i class="fa fa-chevron-left"></i>
                                </button>                                    
                                <button id="btNext" type="button" class="h5a-btn btn btn-default btn-sm">
                                    <i class="fa fa-chevron-right"></i>
                                </button>
                            </div>
                            <div class="btn-group ">
                                <?php
                                    $form->setAttribute('action', $this->url('kenh_phan_phoi/crud', array('action' => 'import-khach-hang')));
                                    $form->setAttribute('role','form');
                                    $form->setAttribute('name','frmImport');
                                    $form->setAttribute('style','margin-top: 0px;margin-bottom:0px;');
                                    $form->prepare();
                                    echo $this->form()->openTag($form);
                                    $file=$form->get('file');                                        
                                    $file->setAttribute('style','display:none');
                                    $file->setAttribute('onchange','return hamSubmit();');       
                                    echo $this->formElement($file);
                                ?>
                                <button type="button" class="h5a-btn btn btn-default btn-sm" onclick="return Import();">Import</button>
                                <a href="<?php echo $this->url('kenh_phan_phoi/crud',array('action'=>'export-khach-hang')); ?>"><button type="button" class="h5a-btn btn btn-default btn-sm">Export</button></a>
                            </div>                                    
                            <a  href="<?php echo $this->url('kenh_phan_phoi/crud',array('action'=>'them-khach-hang'));?>" type="button" class="h5a-btn btn btn-primary btn-sm">Thêm mới</a>
                        </div>
                    </div>
                </div>                
                <?php
                    $flash=$this->flashMessenger();
                    $flash->setMessageOpenFormat('<div%s>
                     <button type="button" id="btFm" class="close" data-dismiss="alert" aria-hidden="true">
                         &times;
                     </button>
                     <ul><li>')
                     ->setMessageSeparatorString('</li><li>')
                     ->setMessageCloseString('</li></ul></div>');

                     $error=$flash->render('error',   array('alert', 'alert-dismissable', 'alert-danger'));
                     echo $error;

                     $info=$flash->render('info',    array('alert', 'alert-dismissable', 'alert-info'));
                     echo $info;

                     $default=$flash->render('default', array('alert', 'alert-dismissable', 'alert-warning'));
                     echo $default;

                     $success=$flash->render('success', array('alert', 'alert-dismissable', 'alert-success'));
                     echo $success;                     
                    if($error||$success||$info||$default)
                    {
                        echo '
                        <script type="text/javascript">
                            setTimeout(function(){
                                document.getElementById("btFm").click();
                            },5000);
                        </script>';                        
                    }
                ?>
            </div>
            <div class="box">
                <ul class="nav nav-tabs" role="tablist" id="myTab">
                    <li role="presentation" class="active" id="tab_tac_ca">
                        <a href="#home" role="tab" data-toggle="tab">Tất cả</a>
                    </li>
                    <?php                           
                    foreach ($kenhPhanPhois as $key=>$kenhPhanPhoi) 
                    {
                        if($kenhPhanPhoi['cap']>0)
                        {
                            echo '<li role="presentation" id="tab_'.$kenhPhanPhoi['termTaxonomyId'].'">';
                                echo '<a href="#'.$key.'" role="tab" data-toggle="tab">'.$kenhPhanPhoi['termId']['name'].'</a>';
                            echo '</li>';
                        }
                    }
                    ?>                       
                </ul>
                <div class="tab-content">
                    <div role="tabpanel" class="tab-pane active" id="home">
                        <?php
                        /*$tongNo=0;
                        foreach ($doiTacs as $key => $doiTac) {
                            if($doiTac->getLoaiDoiTac()->getTermTaxonomyId()==45)
                            {
                                $array=$this->GetSoHoaDonVaHoaDonMoiNhat($doiTac->getIdDoiTac());
                                $tongNo+=(float)$array['noCuoiKi'];
                            }
                        }*/
                        ?>
                        <!-- <label style="margin-right:0px; width:100%;text-align:right">Tổng nợ: <?php //echo $tongNo; $tongNo=0;?></label> -->
                        <div class="container">                            
                            <div class="row">
                                <table id="tatCa" class="dataTables">
                                    <thead>
                                        <th><input type="checkbox"/></th>
                                        <th>Khách hàng</th>
                                        <th>Điện thoại</th>
                                        <th>Địa chỉ</th>
                                        <th>Tổng số đơn hàng</th>
                                        <th>Tổng nợ</th>
                                    </thead>
                                    <tbody>                                               
                                        <?php
                                            $tongNo=0;
                                            foreach ($doiTacs as $key => $doiTac) {
                                                if($doiTac->getLoaiDoiTac()->getTermTaxonomyId()==45)
                                                {
                                                    $array=$this->GetSoHoaDonVaHoaDonMoiNhat($doiTac->getIdDoiTac());
                                                    $soHoaDon=$array['soHoaDon'];
                                                    $hoaDonMoiNhat=$array['hoaDonMoiNhat'];
                                                    $idHoaDon=$array['idHoaDon'];
                                                    $tongNo+=$array['noCuoiKi'];
                                                    
                                                    echo '<tr>';
                                                        echo '<td><input type="checkbox"/></td>';
                                                        echo '<td>';
                                                            echo '<a href="'.$this->url('kenh_phan_phoi/crud',array('action'=>'chi-tiet-khach-hang','id'=>$doiTac->getIdDoiTac())).'">'.$doiTac->getHoTen().'</a>';
                                                        echo '</td>';                                                            
                                                        echo '<td>'.$doiTac->getDiDong().'</td>';
                                                        echo '<td>'.$doiTac->getDiaChi().'</td>';
                                                        echo '<td style="text-align:center;">'.$soHoaDon.'</td>';
                                                        echo '<td>';
                                                            echo $array['noCuoiKi'];
                                                        echo '</td>';
                                                    echo '</tr>  ';
                                                }
                                            }
                                        ?>
                                        <tr>
                                            <td>&nbsp;</td>
                                            <td style="text-align:center;"></td>
                                            <td style="text-align:center;"></td>
                                            <td style="text-align:center;"></td>
                                            <td style="text-align:center;"><b>Tổng nợ: </b></td>
                                            <td><b><?php echo $tongNo; $tongNo=0; ?></b></td>
                                        </tr> 
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                    <?php  
                    foreach ($kenhPhanPhois as $key=>$kenhPhanPhoi) 
                    {
                        
                        if($kenhPhanPhoi['cap']>0)
                        {                               
                            echo '<div role="tabpanel" class="tab-pane" id="'.$key.'">';
                            /*$tongNo=0;
                            foreach ($doiTacs as $key => $doiTac) {
                                if($doiTac->getLoaiDoiTac()->getTermTaxonomyId()==45&&$doiTac->getIdKenhPhanPhoi()->getTermId()->getTermId()==$kenhPhanPhoi['termTaxonomyId'])
                                {
                                    $array=$this->GetSoHoaDonVaHoaDonMoiNhat($doiTac->getIdDoiTac());
                                    $tongNo+=(float)$array['noCuoiKi'];
                                }
                            }*/
                            ?>
                                <!-- <label style="margin-right:0px; width:100%;text-align:right">Tổng nợ: <?php //echo $tongNo; $tongNo=0; ?></label> -->
                                <div class="container">
                                    <div class="row">                                    
                                            <table id="<?php echo $key; ?>" class="dataTables">
                                                <thead>
                                                    <th><input type="checkbox"/></th>
                                                    <th>Khách hàng</th>
                                                    <th>Điện thoại</th>
                                                    <th>Địa chỉ</th>
                                                    <th>Tổng số đơn hàng</th>
                                                    <th>Tổng nợ</th>
                                                </thead>
                                                <tbody> 
                                                    <?php
                                                        $tongNo=0;
                                                        foreach ($doiTacs as $key => $doiTac) {
                                                            if($doiTac->getLoaiDoiTac()->getTermTaxonomyId()==45&&$doiTac->getIdKenhPhanPhoi()->getTermId()->getTermId()==$kenhPhanPhoi['termTaxonomyId'])
                                                            {
                                                                $array=$this->GetSoHoaDonVaHoaDonMoiNhat($doiTac->getIdDoiTac());
                                                                $soHoaDon=$array['soHoaDon'];
                                                                $hoaDonMoiNhat=$array['hoaDonMoiNhat'];
                                                                $idHoaDon=$array['idHoaDon'];
                                                                $tongNo+=(float)$array['noCuoiKi'];
                                                                
                                                                echo '<tr>';
                                                                    echo '<td><input type="checkbox"/></td>';
                                                                    echo '<td>';
                                                                        echo '<a href="'.$this->url('kenh_phan_phoi/crud',array('action'=>'chi-tiet-khach-hang','id'=>$doiTac->getIdDoiTac())).'">'.$doiTac->getHoTen().'</a>';
                                                                    echo '</td>';                                                            
                                                                    echo '<td>'.$doiTac->getDiDong().'</td>';
                                                                    echo '<td>'.$doiTac->getDiaChi().'</td>';
                                                                    echo '<td style="text-align:center;">'.$soHoaDon.'</td>';
                                                                    echo '<td>';
                                                                        echo $array['noCuoiKi'];
                                                                    echo '</td>';
                                                                echo '</tr>  ';
                                                            }
                                                        }
                                                    ?>
                                                    <tr>
                                                        <td>&nbsp;</td>
                                                        <td style="text-align:center;"></td>
                                                        <td style="text-align:center;"></td>
                                                        <td style="text-align:center;"></td>
                                                        <td style="text-align:center;"><b>Tổng nợ: </b></td>
                                                        <td><b><?php echo $tongNo; $tongNo=0; ?></b></td>
                                                    </tr>        
                                                </tbody>
                                            </table>                                      
                                        </div>
                                    </div>
                            <?php
                            echo '</div>';                            
                        }                               
                    }
                    ?>      
                </div>
            </div>
        </div>
    </div>
</div>    
<!-- /.container -->

    <!-- jQuery -->
    <script src="<?php echo $this->basePath();?>/js/jquery.js"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="<?php echo $this->basePath();?>/js/bootstrap.min.js"></script>

    <!-- DataTables JavaScript -->
    <script src="<?php echo $this->basePath();?>/js/plugins/dataTables/jquery.dataTables.js"></script>

    <!-- Page-Level Demo Scripts - Tables - Use for reference -->
    <script>
    $(document).ready(function() {
        $('.dataTables').dataTable({
            "pagingType": "simple",
            "bPaginate": true,
            "bLengthChange": true,
            "bFilter": true,
            "bInfo": true,
            "bAutoWidth": true
        });
         

    });
    

    Import=function()
    {
        document.getElementById('file').click();   
        return false;     
    }
    hamSubmit=function(){
        var valueFile=document.getElementById('file').value;
        if(valueFile)
        {               
            document.frmImport.submit();
            return true;           
        }
    }

    $('#btPrev').click(function(){
        document.getElementById('dataTables-example_previous').click();
    });

    $('#btNext').click(function(){
        document.getElementById('dataTables-example_next').click();
    }); 

    </script>