<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Khách hàng</title>
</head>

<div class="container">
        <div class="row">
            <div class="col-md-2">
                <div class="h5a-sidebar affix">
                    <span class="breadcrumb row">
                        <a href="<?php echo $this->url('hang_hoa/crud',array('action'=>'index'));?>">/ Kho</a>
                        <a href="<?php echo $this->url('kenh_phan_phoi');?>">/ Khách hàng</a>
                         / #xxx /
                    </span>
                    <ul class="nav h5a-sidenav nav-list accordion">
                    </ul>
                </div>
            </div>
            <div class="col-md-10" role="main">
                <div class="h5a-docs-section">
                    <!-- <div class="page-header">
                        <div class="row">
                            <div class="col-sm-6">
                                <h2>Chi tiết khách hàng</h2>
                            </div>
                            <div class="col-sm-6">
                                <div class="pull-right">
                                    <div class="btn-group ">
                                        <button type="button" class="h5a-btn btn btn-default btn-sm">
                                            <i class="fa fa-chevron-left"></i>
                                        </button>                                    
                                        <button type="button" class="h5a-btn btn btn-default btn-sm">
                                            <i class="fa fa-chevron-right"></i>
                                        </button>
                                    </div>
                                    <button type="button" class="h5a-btn btn btn-default btn-sm">Export</button>
                                </div>
                            </div>
                        </div>
                    </div>
                </div> -->
            </div>
        </div>
</div>
<!-- /.container -->

<div class="container h5a-container gray">
    <div class="row">
        <div class="col-md-10 col-md-offset-2">
            <h1>
                <img class="pull-left img-circle" src="http://lorempixel.com/40/40/food/" alt=""> Trường đại học Trà Vinh
            </h1>
            <div class="btn-group pull-right">
                <a class="btn h5a-btn btn-danger btn-xs"><i class="fa fa-times"></i> Xóa khách hàng</a> 
                <!-- <a class="btn h5a-btn btn-primary btn-xs"><i class="fa fa-refresh"></i> Refresh Item</a> -->
            </div>
            <p>Tenderloin pastrami shank filet mignon sirloin jerky leberkas meatball pork tail<br>rump capicolameatball capicola turkey fatback kielbasa brisket.<br><br></p>
            <div class="tabbable">
                <ul class="nav nav-tabs" role="tablist" id="myTab">
                    <li role="presentation" class="active">
                        <a href="#home" role="tab" data-toggle="tab">Xem chi tiết</a>
                    </li>
                    <li role="presentation">
                        <a href="#1" role="tab" data-toggle="tab">Cập nhật</a>
                    </li>
                    <li role="presentation">
                        <a href="#2" role="tab" data-toggle="tab">Lịch sử giao dịch</a>
                    </li>
                </ul>
                <div class="tab-content">
                    <div role="tabpanel" class="tab-pane active" id="home">
                        <div class="row">
                            <div class="col-md-6">
                                <div class="thumbnail">
                                    <img class="img-responsive" src="http://lorempixel.com/1650/1400/food/An%20Item/" alt="Whatever Item">
                                    <div class="caption">
                                        <h4>Simple Johnx XXL</h4>
                                        <p>This is a picture caption</p>
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <h4>Tiêu đề</h4>
                                <p>Mô tả khách hàng</p>
                                <h4 class="underline">More Info</h4>
                                <table class="item">
                                    <tbody>
                                        <tr>
                                            <td><i class="fa fa-key"></i> ID</td>
                                            <td>556</td>
                                        </tr>
                                        <tr>
                                            <td>Company-Code</td>
                                            <td>33223-556H-TT</td>
                                        </tr>
                                        <tr>
                                            <td><i class="fa fa-arrows"></i> Size</td>
                                            <td class="red">-556 mm/hh</td>
                                        </tr>
                                        <tr>
                                            <td><i class="fa fa-user"></i> Niceness</td>
                                            <td class="green">Super Kewl</td>
                                        </tr>
                                        <tr>
                                            <td><i class="fa fa-tag"></i> TAGS</td>
                                            <td>Super, Kewl, 556, wow,<br>nice, hop, html5, admin, responsive<br>more, lines</td>
                                        </tr>
                                        <tr>
                                            <td><i class="fa fa-edit"></i> Colors</td>
                                            <td>
                                                <span class="badge green"></span> <span class="badge red"></span> <span class="badge orange"></span> <span class="badge blue"></span>
                                            </td>
                                        </tr>
                                        <tr>
                                            <td><i class="fa fa-cog"></i> Type</td>
                                            <td>556H-TT</td>
                                        </tr>
                                        <tr>
                                            <td><i class="fa fa-globe"></i> Website</td>
                                            <td><a href="http://www.sharedesk.net">ShareDesk - Shared Offices</a></td>
                                        </tr>
                                        <tr>
                                            <td><i class="fa fa-twitter"></i> Twitter</td>
                                            <td><a href="http://www.twitter.com/sharedesk">@sharedesk</a></td>
                                        </tr>
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                    <div role="tabpanel" class="tab-pane" id="1">
                        <div class="row">
                            <div class="col-md-6">
                                <form>
                                    <input type="text" class="form-control h5a-input" placeholder="Title?" value="This can be anything">
                                    <p>
                                        <textarea placeholder="description here" name="longtext" class="form-control h5a-input" rows="6">Bacon ipsum dolor sit amet pork chop drumstick meatloaf pork loin, shankle turducken filet mignon shank short loin tongue ham salami cow. Shank ball tip DESCRIPTION, capicola prosciutto hamburger ribeye pork loin fatback short loin boudin. Kevin kielbasa capicola, pig pork chop ribeye corned bee. Turkey spare ribs filet mignon chicken boudin sirloin, t-bone shankle chuck turducken. Corned beef sausage rump pork loin. Doner pork biltong pork loin salami.
                                            </textarea><br><br>
                                    </p>
                                    <h4 class="underline">More Info</h4>
                                    <table class="item">
                                        <tbody>
                                            <tr>
                                                <td>ID</td>
                                                <td>556 
                                                    <a href="#" class="tooltip-test" title="" data-original-title="You cannot change it! Call the System Administrator">
                                                        <i class="fa fa-info-circle"></i> Need to change this?
                                                    </a>
                                                </td>
                                            </tr>
                                            <tr>
                                                <td>CompanyCode</td>
                                                <td><input type="text" class="form-control h5a-input" placeholder="CompanyCode?" value="33223-556H-TT"></td>
                                            </tr>
                                            <tr>
                                                <td>Size</td>
                                                <td class="red"><input type="text" class="form-control h5a-input" placeholder="Size?" value="-556 mm/hh"></td>
                                            </tr>
                                            <tr>
                                                <td>Niceness</td>
                                                <td class="green"><input type="text" class="form-control h5a-input" placeholder="Niceness?" value="Super Kewl"></td>
                                            </tr>
                                            <tr>
                                                <td>TAGS</td>
                                                <td>
                                                    <span class="tm-tag" id="SCZrC_1"><span>Super</span><a href="#" class="tm-tag-remove" id="SCZrC_Remover_1" tagidtoremove="1">x</a></span> 
                                                    <span class="tm-tag" id="SCZrC_1"><span>Kewl</span><a href="#" class="tm-tag-remove" id="SCZrC_Remover_1" tagidtoremove="1">x</a></span> 
                                                    <span class="tm-tag" id="SCZrC_1"><span>wow</span><a href="#" class="tm-tag-remove" id="SCZrC_Remover_1" tagidtoremove="1">x</a></span>
                                                    <div class="form-group">
                                                        <input type="text" name="display-tfmjW" placeholder="Tags" id="tags-input" class="h5a-input form-control">
                                                        <input type="hidden" name="tags">
                                                        <label for="exampleInputEmail1"><small>Comma Separated tags</small></label>
                                                    </div>
                                                </td>
                                            </tr>
                                            <tr>
                                                <td>Colors</td>
                                                <td>
                                                    <select multiple="multiple" id="select-colors" name="my-select[]" style="position: absolute; left: -9999px;">
                                                        <option value="elem_1">blue</option>
                                                        <option value="elem_2">red</option>
                                                        <option value="elem_3">orange</option>
                                                        <option value="elem_4">yellow</option>
                                                        <option value="elem_100">green</option>
                                                    </select>
                                                    <div class="ms-container" id="ms-select-colors">
                                                        <div class="ms-selectable">
                                                            <ul class="ms-list" tabindex="-1">
                                                                <li class="ms-elem-selectable" id="elem_1-selectable"><span>blue</span></li>
                                                                <li class="ms-elem-selectable" id="elem_2-selectable"><span>red</span></li>
                                                                <li class="ms-elem-selectable" id="elem_3-selectable"><span>orange</span></li>
                                                                <li class="ms-elem-selectable ms-hover" id="elem_4-selectable"><span>yellow</span></li>
                                                                <li class="ms-elem-selectable" id="elem_100-selectable"><span>green</span></li>
                                                            </ul>
                                                        </div>
                                                        <div class="ms-selection">
                                                            <ul class="ms-list" tabindex="-1">
                                                                <li class="ms-elem-selection" id="elem_1-selection" style="display: none;"><span>blue</span></li>
                                                                <li class="ms-elem-selection" id="elem_2-selection" style="display: none;"><span>red</span></li>
                                                                <li class="ms-elem-selection" id="elem_3-selection" style="display: none;"><span>orange</span></li>
                                                                <li class="ms-elem-selection" id="elem_4-selection" style="display: none;"><span>yellow</span></li>
                                                                <li class="ms-elem-selection" id="elem_100-selection" style="display: none;"><span>green</span></li>
                                                            </ul>
                                                        </div>
                                                    </div>
                                                </td>
                                            </tr>
                                            <tr>
                                                <td>Type</td>
                                                <td><input type="text" class="form-control h5a-input" placeholder="Type?" value="556H-TT"></td>
                                            </tr>
                                            <tr>
                                                <td colspan="2"><br><a class="full btn h5a-btn btn-success">SAVE THIS ITEM</a></td>
                                            </tr>
                                        </tbody>
                                    </table>
                                </form>
                            </div>
                            <div class="col-md-6">

                            </div>
                        </div>
                    </div>
                    <div role="tabpanel" class="tab-pane" id="2">
                        <div class="container">
                            <div class="row">
                                <table id="dataTables-example" class="">
                                    <thead>
                                        <th><input type="checkbox"/></th>
                                        <th>Ngày</th>
                                        <th>Giao dịch</th>
                                    </thead>
                                    <tbody>
                                        <tr>
                                            <td><input type="checkbox"/></td>
                                            <td>10/11/2014</td>
                                            <td>Đơn hàng #7-3435</td>
                                        </tr>
                                        <tr>
                                            <td><input type="checkbox"/></td>
                                            <td>10/11/2014</td>
                                            <td>Đơn hàng #7-3435</td>
                                        </tr>
                                        <tr>
                                            <td><input type="checkbox"/></td>
                                            <td>10/11/2014</td>
                                            <td>Đơn hàng #7-3435</td>
                                        </tr>
                                        <tr>
                                            <td><input type="checkbox"/></td>
                                            <td>10/11/2014</td>
                                            <td>Đơn hàng #7-3435</td>
                                        </tr>
                                        <tr>
                                            <td><input type="checkbox"/></td>
                                            <td>10/11/2014</td>
                                            <td>Đơn hàng #7-3435</td>
                                        </tr>
                                        <tr>
                                            <td><input type="checkbox"/></td>
                                            <td>10/11/2014</td>
                                            <td>Đơn hàng #7-3435</td>
                                        </tr>
                                        <tr>
                                            <td><input type="checkbox"/></td>
                                            <td>10/11/2014</td>
                                            <td>Đơn hàng #7-3435</td>
                                        </tr>
                                        <tr>
                                            <td><input type="checkbox"/></td>
                                            <td>10/11/2014</td>
                                            <td>Đơn hàng #7-3435</td>
                                        </tr>
                                        <tr>
                                            <td><input type="checkbox"/></td>
                                            <td>10/11/2014</td>
                                            <td>Đơn hàng #7-3435</td>
                                        </tr>
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<!-- jQuery -->
<script src="<?php echo $this->basePath();?>/js/jquery.js"></script>

<!-- Bootstrap Core JavaScript -->
<script src="<?php echo $this->basePath();?>/js/bootstrap.min.js"></script>

<!-- DataTables JavaScript -->
<script src="<?php echo $this->basePath();?>/js/plugins/dataTables/jquery.dataTables.js"></script>

<script>
    $(document).ready(function() {
        $('#dataTables-example').dataTable({
            "pagingType": "simple",
            "bPaginate": true,
            "bLengthChange": true,
            "bFilter": true,
            "bInfo": true,
            "bAutoWidth": true
        });
    });
    </script>