<?php
     $this->headTitle('Nhà cung cấp');
?>

<div class="row">
    <div class="col-md-2">
        <div class="h5a-sidebar affix">
            <span class="breadcrumb row">
                <a href="<?php echo $this->url('hang_hoa/crud',array('action'=>'index'));?>">/ Kho</a>
                 / Nhà Cung Cấp /
            </span>
            <ul class="nav h5a-sidenav nav-list accordion">     

                <li>
                    <a href="<?php echo $this->url('kenh_phan_phoi/crud',array('action'=>'index'));?>">
                        <i class="glyphicon glyphicon-user"></i><i class="glyphicon glyphicon-arrow-right"></i> Khách hàng
                    </a>
                </li> 
                <li>
                    <a href="<?php echo $this->url('kenh_phan_phoi/crud',array('action'=>'nha-cung-cap'));?>">
                        <i class="glyphicon glyphicon-user"></i><i class="glyphicon glyphicon-arrow-left"></i> Nhà cung cấp
                    </a>
                </li>              
                
            </ul>
        </div>
    </div>
    <div class="col-md-10" role="main">
        <div class="h5a-docs-section">
            <div class="page-header">
                <div class="row">
                    <div class="col-sm-6">
                        <h1>Nhà cung cấp</h1>
                    </div>
                    <div class="col-sm-6">
                        <div class="pull-right">
                            <div class="btn-group ">
                                <button type="button" class="h5a-btn btn btn-default btn-sm">
                                    <i class="fa fa-chevron-left"></i>
                                </button>                                    
                                <button type="button" class="h5a-btn btn btn-default btn-sm">
                                    <i class="fa fa-chevron-right"></i>
                                </button>
                            </div>
                            <div class="btn-group ">
                                <button type="button" class="h5a-btn btn btn-default btn-sm">Import</button>
                                <a href="<?php echo $this->url('kenh_phan_phoi/crud',array('action'=>'export-nha-cung-cap')); ?>"><button type="button" class="h5a-btn btn btn-default btn-sm">Export</button></a>
                            </div>                                    
                            <a  href="<?php echo $this->url('kenh_phan_phoi/crud',array('action'=>'them-nha-cung-cap'));?>" type="button" class="h5a-btn btn btn-primary btn-sm">Thêm mới</a>
                        </div>
                    </div>
                </div>
                <?php 
                    $flash=$this->flashMessenger();
                    $flash->setMessageOpenFormat('<div%s>
                     <button type="button" class="close" data-dismiss="alert" aria-hidden="true">
                         &times;
                     </button>
                     <ul><li>')
                     ->setMessageSeparatorString('</li><li>')
                     ->setMessageCloseString('</li></ul></div>');

                     echo $flash->render('error',   array('alert', 'alert-dismissable', 'alert-danger'));
                     echo $flash->render('info',    array('alert', 'alert-dismissable', 'alert-info'));
                     echo $flash->render('default', array('alert', 'alert-dismissable', 'alert-warning'));
                     echo $flash->render('success', array('alert', 'alert-dismissable', 'alert-success'));
                 ?>
            </div>
            <div class="box">
                <ul class="nav nav-tabs" role="tablist" id="myTab">
                    <li role="presentation" class="active">
                        <a href="#home" role="tab" data-toggle="tab">Tất cả</a>
                    </li>
                </ul>
                <div class="tab-content">
                    <div role="tabpanel" class="tab-pane active" id="home">
                        <?php
                        /*$tongNo=0;
                        foreach ($doiTacs as $key => $doiTac) {
                            if($doiTac->getLoaiDoiTac()->getTermTaxonomyId()==46)
                            {
                                $array=$this->GetSoPhieuNhapVaPhieuNhapMoiNhat($doiTac->getIdDoiTac());
                                $tongNo+=$array['noCuoiKi'];
                            }
                        }*/
                        ?>
                        <!-- <label style="margin-right:0px; width:100%;text-align:right">Tổng nợ: <?php //echo $tongNo; $tongNo=0; ?></label> -->
                        <div class="container">
                            <div class="row">
                                <table id="tatCa" class="dataTables">
                                    <thead>
                                        <th><input type="checkbox"/></th>
                                        <th>Nhà cung cấp</th>
                                        <th>Điện thoại</th>
                                        <th>Địa chỉ</th>
                                        <th>Tổng số đơn hàng</th>
                                        <th>Tổng nợ</th>
                                    </thead>
                                    <tbody>                                               
                                        <?php
                                            $tongNo=0;
                                            foreach ($doiTacs as $key => $doiTac) {
                                                if($doiTac->getLoaiDoiTac()->getTermTaxonomyId()==46)
                                                {
                                                    $array=$this->GetSoPhieuNhapVaPhieuNhapMoiNhat($doiTac->getIdDoiTac());
                                                    $soHoaDon=$array['soHoaDon'];
                                                    $hoaDonMoiNhat=$array['hoaDonMoiNhat'];
                                                    $idHoaDon=$array['idHoaDon'];
                                                    $tongNo+=(float)$array['noCuoiKi'];
                                                    echo '<tr>';
                                                        echo '<td><input type="checkbox"/></td>';
                                                        echo '<td>';
                                                            echo '<a href="'.$this->url('kenh_phan_phoi/crud',array('action'=>'chi-tiet-nha-cung-cap','id'=>$doiTac->getIdDoiTac())).'">'.$doiTac->getHoTen().'</a>';
                                                        echo '</td>';                                                            
                                                        echo '<td>'.$doiTac->getDiDong().'</td>';
                                                        echo '<td>'.$doiTac->getDiaChi().'</td>';                                                        
                                                        echo '<td>'.number_format($soHoaDon,'0','',' ').'</td>';
                                                        echo '<td>';                                                        
                                                            echo number_format($array['noCuoiKi'],'0','',' ');
                                                        echo '</td>';
                                                    echo '</tr>  ';
                                                }
                                            }
                                        ?> 
                                        <tr>
                                            <td>&nbsp;</td>
                                            <td style="text-align:center;"></td>
                                            <td style="text-align:center;"></td>
                                            <td style="text-align:center;"></td>
                                            <td style="text-align:center;"><b>Tổng nợ: </b></td>
                                            <td><b><?php echo number_format($tongNo,'0','',' '); $tongNo=0; ?></b></td>
                                        </tr>                                                     
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                       
                </div>
            </div>
        </div>
    </div>
</div>    
<!-- /.container -->

    <!-- jQuery -->
    <script src="<?php echo $this->basePath();?>/js/jquery.js"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="<?php echo $this->basePath();?>/js/bootstrap.min.js"></script>

    <!-- DataTables JavaScript -->
    <script src="<?php echo $this->basePath();?>/js/plugins/dataTables/jquery.dataTables.js"></script>

    <!-- Page-Level Demo Scripts - Tables - Use for reference -->
    <script>
    $(document).ready(function() {
        $('.dataTables').dataTable({
            "pagingType": "simple",
            "bPaginate": true,
            "bLengthChange": true,
            "bFilter": true,
            "bInfo": true,
            "bAutoWidth": true
        });
    });
    </script>