<?php
     $this->headTitle('Kênh phân phối');
?>
<div class="container">
        <div class="row">
            <div class="col-md-2">
                <div class="h5a-sidebar affix">
                    <span class="breadcrumb row">
                        <a href="<?php echo $this->url('hang_hoa/crud',array('action'=>'index'));?>">/ Kho</a>
                         / Khách hàng /
                    </span>
                    <ul class="nav h5a-sidenav nav-list accordion">     

                        <li>
                            <a href="<?php echo $this->url('kenh_phan_phoi/crud',array('action'=>'index'));?>">
                                <i class="fa fa-cubes"></i> Khách hàng
                            </a>
                        </li> 
                        <li>
                            <a href="<?php echo $this->url('kenh_phan_phoi/crud',array('action'=>'nhaCungCap'));?>">
                                <i class="fa fa-cubes"></i> Nhà cung cấp
                            </a>
                        </li>                 
                        <li>
                            <a href="<?php echo $this->url('kenh_phan_phoi/crud',array('action'=>'donHang'));?>">
                                <i class="fa fa-cubes"></i> Đơn hàng
                            </a>
                        </li>
                        <li>
                            <a href="<?php echo $this->url('kenh_phan_phoi/crud',array('action'=>'doanhThu'));?>">
                                <i class="fa fa-flag-checkered"></i> Doanh thu
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
            <div class="col-md-10" role="main">
                <div class="h5a-docs-section">
                    <div class="page-header">
                        <div class="row">
                            <div class="col-sm-6">
                                <h1>Nhà cung cấp</h1>
                            </div>
                            <div class="col-sm-6">
                                <div class="pull-right">
                                    <div class="btn-group ">
                                        <button type="button" class="h5a-btn btn btn-default btn-sm">
                                            <i class="fa fa-chevron-left"></i>
                                        </button>                                    
                                        <button type="button" class="h5a-btn btn btn-default btn-sm">
                                            <i class="fa fa-chevron-right"></i>
                                        </button>
                                    </div>
                                    <div class="btn-group ">
                                        <button type="button" class="h5a-btn btn btn-default btn-sm">Import</button>
                                        <button type="button" class="h5a-btn btn btn-default btn-sm">Export</button>
                                    </div>                                    
                                    <a  href="<?php echo $this->url('kenh_phan_phoi/crud',array('action'=>'themNhaCungCap'));?>" type="button" class="h5a-btn btn btn-primary btn-sm">Thêm mới</a>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="box">
                        <ul class="nav nav-tabs" role="tablist" id="myTab">
                            <li role="presentation" class="active">
                                <a href="#home" role="tab" data-toggle="tab">Tất cả</a>
                            </li>
                        </ul>
                        <div class="tab-content">
                            <div role="tabpanel" class="tab-pane active" id="home">
                                <div class="container">
                                    <div class="row">
                                        <table id="tatCa" class="dataTables">
                                            <thead>
                                                <th><input type="checkbox"/></th>
                                                <th>Nhà cung cấp</th>
                                                <th>Điện thoại</th>
                                                <th>Địa chỉ</th>
                                                <th>Đơn hàng</th>
                                                <th>Mới nhất</th>
                                            </thead>
                                            <tbody>                                               
                                                <?php
                                                    foreach ($doiTacs as $key => $doiTac) {
                                                        if($doiTac->getLoaiDoiTac()->getTermTaxonomyId()==46)
                                                        {
                                                            $array=$this->GetSoPhieuNhapVaPhieuNhapMoiNhat($doiTac->getIdDoiTac());
                                                            $soHoaDon=$array['soHoaDon'];
                                                            $hoaDonMoiNhat=$array['hoaDonMoiNhat'];
                                                            $idHoaDon=$array['idHoaDon'];
                                                            echo '<tr>';
                                                                echo '<td><input type="checkbox"/></td>';
                                                                echo '<td>';
                                                                    echo '<a href="'.$this->url('kenh_phan_phoi/crud',array('action'=>'chiTietNhaCungCap','id'=>$doiTac->getIdDoiTac())).'">'.$doiTac->getHoTen().'</a>';
                                                                echo '</td>';                                                            
                                                                echo '<td>'.$doiTac->getDiDong().'</td>';
                                                                echo '<td>'.$doiTac->getDiaChi().'</td>';
                                                                echo '<td>'.$soHoaDon.'</td>';
                                                                echo '<td>';
                                                                    if($hoaDonMoiNhat!='')
                                                                    {
                                                                        echo '<a href="'.$this->url('kenh_phan_phoi/crud',array('action'=>'chiTietPhieuNhap','id'=>$idHoaDon)).'">#'.$hoaDonMoiNhat.'</a>';
                                                                    }
                                                                echo '</td>';
                                                            echo '</tr>  ';
                                                        }
                                                    }
                                                ?>                                                     
                                            </tbody>
                                        </table>
                                    </div>
                                </div>
                            </div>
                               
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- /.container -->

    <!-- jQuery -->
    <script src="<?php echo $this->basePath();?>/js/jquery.js"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="<?php echo $this->basePath();?>/js/bootstrap.min.js"></script>

    <!-- DataTables JavaScript -->
    <script src="<?php echo $this->basePath();?>/js/plugins/dataTables/jquery.dataTables.js"></script>

    <!-- Page-Level Demo Scripts - Tables - Use for reference -->
    <script>
    $(document).ready(function() {
        $('.dataTables').dataTable({
            "pagingType": "simple",
            "bPaginate": true,
            "bLengthChange": true,
            "bFilter": true,
            "bInfo": true,
            "bAutoWidth": true
        });
    });
    </script>