<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Thêm khách hàng</title>
</head>

<div class="container">
        <div class="row">
            <div class="col-md-2">
                <div class="h5a-sidebar affix">
                    <span class="breadcrumb row">
                        <a href="<?php echo $this->url('hang_hoa/crud',array('action'=>'index'));?>">/ Kho</a> 
                        <a href="<?php echo $this->url('kenh_phan_phoi',array('action'=>'index'));?>">/ Khách hàng</a>
                         / Thêm khách hàng /
                    </span>
                    <ul class="nav h5a-sidenav nav-list accordion">                        
                        <li>
                            <a href="<?php echo $this->url('kenh_phan_phoi');?>">
                                <i class="fa fa-cubes"></i> Khách hàng
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
            <div class="col-md-10" role="main">
                <div class="h5a-docs-section">
                    <div class="page-header">
                        <div class="row">
                            <div class="col-sm-6">
                                <h1>Thêm khách hàng</h1>
                            </div>
                            <div class="col-sm-6">
                                <div class="pull-right">
                                    <button type="button" class="h5a-btn btn btn-default btn-sm">Hủy</button>
                                    <button type="button" class="h5a-btn btn btn-primary btn-sm">Lưu
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <form>
                            <h4 class="underline">More Info</h4>
                            <table class="item">
                                <tbody>
                                    <tr>
                                        <td>Tên khách hàng</td>
                                        <td>
                                            <input type="text" id="form-field-1" placeholder="Username" class="h5a-input form-control input-sm">
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>Mô tả</td>
                                        <td>
                                            <textarea class="form-control h5a" rows="5" id="editor"></textarea>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>Hình ảnh</td>
                                        <td>
                                            <input type="filepicker" data-fp-button-text="<i class='fa fa-cloud-upload'></i> Files UPLOAD from ANYWERE" data-fp-apikey="fakeAPIkey" name="filePicker" id="filePicker" class="h5a-btn btn btn-primary" style="display: none;">
                                            <button type="button" class="h5a-btn btn btn-primary"><i class="fa fa-cloud-upload"></i> Tải lên</button>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>CompanyCode</td>
                                        <td><input type="text" class="form-control h5a-input" placeholder="CompanyCode?" value="33223-556H-TT"></td>
                                    </tr>
                                    <tr>
                                        <td>Size</td>
                                        <td class="red"><input type="text" class="form-control h5a-input" placeholder="Size?" value="-556 mm/hh"></td>
                                    </tr>
                                    <tr>
                                        <td>Niceness</td>
                                        <td class="green"><input type="text" class="form-control h5a-input" placeholder="Niceness?" value="Super Kewl"></td>
                                    </tr>
                                    <tr>
                                        <td>TAGS</td>
                                        <td>
                                            <span class="tm-tag" id="SCZrC_1"><span>Super</span><a href="#" class="tm-tag-remove" id="SCZrC_Remover_1" tagidtoremove="1">x</a></span> 
                                            <span class="tm-tag" id="SCZrC_1"><span>Kewl</span><a href="#" class="tm-tag-remove" id="SCZrC_Remover_1" tagidtoremove="1">x</a></span> 
                                            <span class="tm-tag" id="SCZrC_1"><span>wow</span><a href="#" class="tm-tag-remove" id="SCZrC_Remover_1" tagidtoremove="1">x</a></span>
                                            <div class="form-group">
                                                <input type="text" name="display-tfmjW" placeholder="Tags" id="tags-input" class="h5a-input form-control">
                                                <input type="hidden" name="tags">
                                                <label for="exampleInputEmail1"><small>Comma Separated tags</small></label>
                                            </div>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>Colors</td>
                                        <td>
                                            <select multiple="multiple" id="select-colors" name="my-select[]" style="position: absolute; left: -9999px;">
                                                <option value="elem_1">blue</option>
                                                <option value="elem_2">red</option>
                                                <option value="elem_3">orange</option>
                                                <option value="elem_4">yellow</option>
                                                <option value="elem_100">green</option>
                                            </select>
                                            <div class="ms-container" id="ms-select-colors">
                                                <div class="ms-selectable">
                                                    <ul class="ms-list" tabindex="-1">
                                                        <li class="ms-elem-selectable" id="elem_1-selectable"><span>blue</span></li>
                                                        <li class="ms-elem-selectable" id="elem_2-selectable"><span>red</span></li>
                                                        <li class="ms-elem-selectable" id="elem_3-selectable"><span>orange</span></li>
                                                        <li class="ms-elem-selectable ms-hover" id="elem_4-selectable"><span>yellow</span></li>
                                                        <li class="ms-elem-selectable" id="elem_100-selectable"><span>green</span></li>
                                                    </ul>
                                                </div>
                                                <div class="ms-selection">
                                                    <ul class="ms-list" tabindex="-1">
                                                        <li class="ms-elem-selection" id="elem_1-selection" style="display: none;"><span>blue</span></li>
                                                        <li class="ms-elem-selection" id="elem_2-selection" style="display: none;"><span>red</span></li>
                                                        <li class="ms-elem-selection" id="elem_3-selection" style="display: none;"><span>orange</span></li>
                                                        <li class="ms-elem-selection" id="elem_4-selection" style="display: none;"><span>yellow</span></li>
                                                        <li class="ms-elem-selection" id="elem_100-selection" style="display: none;"><span>green</span></li>
                                                    </ul>
                                                </div>
                                            </div>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>Type</td>
                                        <td><input type="text" class="form-control h5a-input" placeholder="Type?" value="556H-TT"></td>
                                    </tr>
                                </tbody>
                            </table>
                        </form>
                    </div>
                    <div class="page-footer">
                        <div class="row bottom20">
                            <div class="col-sm-6 col-sm-offset-6">
                                <div class="pull-right">
                                    <button type="button" class="h5a-btn btn btn-default btn-sm">Hủy</button>
                                    <button type="button" class="h5a-btn btn btn-primary btn-sm">Lưu
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- /.container -->

    <!-- jQuery -->
    <script src="<?php echo $this->basePath();?>/js/jquery.js"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="<?php echo $this->basePath();?>/js/bootstrap.min.js"></script>

    <!-- DataTables JavaScript -->
    <script src="<?php echo $this->basePath();?>/js/plugins/dataTables/jquery.dataTables.js"></script>

    <!-- Summernot JavaScript -->
    <script src="<?php echo $this->basePath();?>/js/summernote.min.js"></script>

    <!-- Page-Level Demo Scripts - Tables - Use for reference -->
    <script>
    $(document).ready(function() {
        $('#dataTables-example').dataTable({
            "pagingType": "simple",
            "bPaginate": true,
            "bLengthChange": true,
            "bFilter": true,
            "bInfo": true,
            "bAutoWidth": true
        });
    });

    $("#editor").summernote({height:150});
    </script>