<?php
 $this->headTitle('Thêm khách hàng');

 $form->setAttribute('action', $this->url('kenh_phan_phoi/crud', array('action' => 'themKhachHang')));
 $form->setAttribute('role','form');
 $form->prepare();
 echo $this->form()->openTag($form);

 $khachHang=$form->get('khach-hang');    
 echo $this->formHidden($khachHang->get('idDoiTac'));
 $khachHang->get('loaiDoiTac')->setAttribute('value','45');
 echo $this->formHidden($khachHang->get('loaiDoiTac'));
?>

<div class="row">
    <div class="col-md-2">
        <div class="h5a-sidebar affix">
            <span class="breadcrumb row">
                <a href="<?php echo $this->url('hang_hoa/crud',array('action'=>'index'));?>">/ Kho</a> 
                <a href="<?php echo $this->url('kenh_phan_phoi',array('action'=>'index'));?>">/ Khách hàng</a>
                 / Thêm khách hàng /
            </span>
            <ul class="nav h5a-sidenav nav-list accordion">                        
                <li>
                    <a href="<?php echo $this->url('kenh_phan_phoi/crud',array('action'=>'index'));?>">
                        <i class="glyphicon glyphicon-open"></i> Khách hàng
                    </a>
                </li> 
                <li>
                    <a href="<?php echo $this->url('kenh_phan_phoi/crud',array('action'=>'nhaCungCap'));?>">
                        <i class="glyphicon glyphicon-save"></i> Nhà cung cấp
                    </a>
                </li>                 
                <li>
                    <a href="<?php echo $this->url('loi_nhuan/crud',array('action'=>'donHang'));?>">
                        <i class="fa fa-cubes"></i> Đơn hàng
                    </a>
                </li>
                <li>
                    <a href="<?php echo $this->url('loi_nhuan/crud',array('action'=>'index'));?>">
                        <i class="fa fa-flag-checkered"></i> Doanh thu
                    </a>
                </li>
            </ul>
        </div>
    </div>
    <div class="col-md-10" role="main">
        <div class="h5a-docs-section">
            <div class="page-header">
                <div class="row">
                    <div class="col-sm-6">
                        <h1>Thêm khách hàng</h1>
                    </div>
                    <div class="col-sm-6">
                        <div class="pull-right">
                            <button type="button" class="h5a-btn btn btn-default btn-sm">Hủy</button>
                            <button type="submit" class="h5a-btn btn btn-primary btn-sm">Lưu
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">                        
                    <h4 class="underline">More Info</h4>
                    <table class="item">
                        <tbody>
                            
                            <tr>
                                <td>Tên khách hàng</td>
                                <td>
                                <?php 
                                    $hoTen=$khachHang->get('hoTen');
                                    $hoTen->setAttribute('class','h5a-input form-control input-sm');
                                    $hoTen->setAttribute('placeholder','Họ tên khách hàng');
                                    $hoTen->setAttribute('id','form-field-1');
                                    echo $this->formElement($hoTen);
                                ?>                                           
                                </td>
                            </tr>
                            <tr>
                                <td>Địa chỉ khách hàng</td>
                                <td>
                                <?php 
                                    $diaChi=$khachHang->get('diaChi');
                                    $diaChi->setAttribute('class','h5a-input form-control input-sm');
                                    $diaChi->setAttribute('placeholder','Địa chỉ khách hàng');
                                    $diaChi->setAttribute('id','form-field-1');
                                    echo $this->formElement($diaChi);
                                ?>                                           
                                </td>
                            </tr>
                            <tr>
                                <td>Mô tả</td>
                                <td>
                                    
                                <?php 
                                    $moTa=$khachHang->get('moTa');
                                    $moTa->setAttribute('class','form-control h5a');
                                    $moTa->setAttribute('placeholder','Mô tả khách hàng');
                                    $moTa->setAttribute('id','editor');
                                    $moTa->setAttribute('rows','5');
                                    echo $this->formElement($moTa);
                                ?>   
                                </td>
                            </tr>
                            <tr>
                                <td>Hình ảnh</td>
                                <td>
                                <?php 
                                    $hinhAnh=$khachHang->get('hinhAnh');        
                                    $hinhAnh->setAttribute('placeholder','Chọn hình ảnh');
                                    $hinhAnh->setAttribute('class','h5a-btn btn btn-primary');
                                    echo $this->formElement($hinhAnh);
                                ?>                                           
                                </td>
                            </tr>
                            <tr>
                                <td>Kênh phân phối</td>
                                <td>
                                <?php 
                                    $idKenhPhanPhoi=$khachHang->get('idKenhPhanPhoi');
                                    $idKenhPhanPhoi->setAttribute('class','h5a-input form-control input-sm');
                                    $idKenhPhanPhoi->setAttribute('id','form-field-1');
                                    $idKenhPhanPhoi->setValueOptions($this->MakeArrayOptionTaxonomy($kenhPhanPhois)); 
                                    echo $this->formElement($idKenhPhanPhoi);
                                ?>                                           
                                </td>
                            </tr>

                            <tr>
                                <td>Địa chỉ email</td>
                                <td>
                                <?php 
                                    $email=$khachHang->get('email');
                                    $email->setAttribute('class','h5a-input form-control input-sm');
                                    $email->setAttribute('placeholder','Địa chỉ email');
                                    $email->setAttribute('id','form-field-1');
                                    echo $this->formElement($email);
                                ?>                                           
                                </td>
                            </tr>
                            <tr>
                                <td></td>
                                <td>
                                    <?php
                                        if($ktTonTaiKhachHang==1)
                                        {
                                            echo '<tr>';
                                                echo '<td></td>';
                                                echo '<td><span class="badge red">Email đã được sử dụng, vui lòng kiểm tra lại</span></td>';
                                            echo '<tr>';
                                        }
                                    ?>
                                </td>

                            </tr>
                            <tr>
                                <td>Di động</td>
                                <td>
                                <?php 
                                    $diDong=$khachHang->get('diDong');
                                    $diDong->setAttribute('class','h5a-input form-control input-sm');
                                    $diDong->setAttribute('placeholder','Điện thoại di động');
                                    $diDong->setAttribute('id','form-field-1');
                                    echo $this->formElement($diDong);
                                ?>                                           
                                </td>
                            </tr>


                            <tr>
                                <td>Điện thoại cố định</td>
                                <td>
                                <?php 
                                    $dienThoaiCoDinh=$khachHang->get('dienThoaiCoDinh');
                                    $dienThoaiCoDinh->setAttribute('class','h5a-input form-control input-sm');
                                    $dienThoaiCoDinh->setAttribute('placeholder','Điện thoại cố định');
                                    $dienThoaiCoDinh->setAttribute('id','form-field-1');
                                    echo $this->formElement($dienThoaiCoDinh);
                                ?>                                           
                                </td>
                            </tr>

                            <tr>
                                <td>Website</td>
                                <td>
                                <?php 
                                    $website=$khachHang->get('website');
                                    $website->setAttribute('class','h5a-input form-control input-sm');
                                    $website->setAttribute('placeholder','Website');
                                    $website->setAttribute('id','form-field-1');
                                    echo $this->formElement($website);
                                ?>                                           
                                </td>
                            </tr>

                            <tr>
                                <td>Twitter</td>
                                <td>
                                <?php 
                                    $twitter=$khachHang->get('twitter');
                                    $twitter->setAttribute('class','h5a-input form-control input-sm');
                                    $twitter->setAttribute('placeholder','Twitter');
                                    $twitter->setAttribute('id','form-field-1');
                                    echo $this->formElement($twitter);
                                ?>                                           
                                </td>
                            </tr>

                            
                        </tbody>
                    </table>
            </div>
            <div class="page-footer">
                <div class="row bottom20">
                    <div class="col-sm-6 col-sm-offset-6">
                        <div class="pull-right">
                            <button type="button" class="h5a-btn btn btn-default btn-sm">Hủy</button>
                            <button type="submit" class="h5a-btn btn btn-primary btn-sm">Lưu
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>    
<!-- /.container -->

    <!-- jQuery -->
    <script src="<?php echo $this->basePath();?>/js/jquery.js"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="<?php echo $this->basePath();?>/js/bootstrap.min.js"></script>

    <!-- DataTables JavaScript -->
    <script src="<?php echo $this->basePath();?>/js/plugins/dataTables/jquery.dataTables.js"></script>

    <!-- Summernot JavaScript -->
    <script src="<?php echo $this->basePath();?>/js/summernote.min.js"></script>

    <!-- Page-Level Demo Scripts - Tables - Use for reference -->
    <script>
    $(document).ready(function() {
        $('#dataTables-example').dataTable({
            "pagingType": "simple",
            "bPaginate": true,
            "bLengthChange": true,
            "bFilter": true,
            "bInfo": true,
            "bAutoWidth": true
        });
    });

    $("#editor").summernote({height:150});
    </script>