<?php $this->headTitle('Thông tin chi tiết'); ?>

<div class="row">
    <div class="col-md-2">
        <div class="h5a-sidebar affix">
            <!-- <span class="breadcrumb row">
                <a href="<?php echo $this->url('hang_hoa/crud',array('action'=>'index'));?>">/ Kho</a>
                <a href="<?php echo $this->url('kenh_phan_phoi');?>">/ Khách hàng</a>
                 / #xxx /
            </span> -->
            <ul class="nav h5a-sidenav nav-list accordion">
                <li>
                    <a href="<?php echo $this->url('barcode/crud',array('action'=>'index'));?>">
                        <i class="fa fa-list-alt"></i> Cài đặt mã vạch
                    </a>
                </li> 
            </ul>
        </div>
    </div>
    <div class="col-md-10" role="main">
        <div class="h5a-docs-section">
            
    </div>
</div>
<!-- /.container -->

<div class="container h5a-container gray">
    <div class="row">
        <div class="col-md-10 col-md-offset-2">
            <h1>                
                <?php echo $barcode->getTenBarcode(); ?>
            </h1>
            <?php 
                    $flash=$this->flashMessenger();
                    $flash->setMessageOpenFormat('<div%s>
                     <button type="button" class="close" data-dismiss="alert" aria-hidden="true">
                         &times;
                     </button>
                     <ul><li>')
                     ->setMessageSeparatorString('</li><li>')
                     ->setMessageCloseString('</li></ul></div>');

                     echo $flash->render('error',   array('alert', 'alert-dismissable', 'alert-danger'));
                     echo $flash->render('info',    array('alert', 'alert-dismissable', 'alert-info'));
                     echo $flash->render('default', array('alert', 'alert-dismissable', 'alert-warning'));
                     echo $flash->render('success', array('alert', 'alert-dismissable', 'alert-success'));
            ?>
            <div class="btn-group pull-right">
                
            </div>
            <p>
            
            </p>
            <div class="tabbable">
                <ul class="nav nav-tabs" role="tablist" id="myTab">
                    <li role="presentation" class="active">
                        <a href="#home" role="tab" data-toggle="tab">Cập nhật</a>
                    </li>                    
                </ul>
                <div class="tab-content">                    
                    <div role="tabpanel" class="tab-pane active" id="home">
                        <div class="row">
                            <div class="col-md-6">
                                <?php  
                                $form->setAttribute('action', $this->url('barcode/crud', array('action' => 'sua-barcode','id'=>$barcode->getIdBarcode())));
                                $form->setAttribute('role','form');
                                $form->prepare();
                                echo $this->form()->openTag($form);
                                echo $this->formHidden($form->get('barcode')->get('idBarcode'));
                                echo $this->formHidden($form->get('barcode')->get('state'));
                                ?>     
                                <input type="text" name="TenTruoc" value="<?php echo $barcode->getTenBarcode(); ?>" hidden="true"/>    
                                    <h4 class="underline">Thông tin chi tiết</h4>
                                    <table class="item">
                                        <tbody> 

                                            <tr>
                                                <td>Tên</td>
                                                <td>
                                                <?php
                                                    echo $this->formElement($form->get('barcode')->get('tenBarcode'));
                                                    if($ktTonTai==1)
                                                    {
                                                        echo '<span class="badge red">Tên này đã được sử dụng, vui lòng kiểm tra lại</span>';
                                                    }
                                                ?>
                                                </td>
                                            </tr>
                                            <tr>
                                                <td>Độ dài ký tự</td>
                                                <td>
                                                    <input type="number" min="0" name="length" class="h5a-input form-control input-sm"/>
                                                </td>
                                            </tr>
                                            <tr>
                                                <td></td>
                                                <td>
                                                <input type="submit" class="full btn h5a-btn btn-success" value="Lưu Thay Đổi"/>
                                                </td>
                                            </tr>
                                        </tbody>
                                    </table>
                            <?php echo $this->form()->closeTag(); ?>
                            </div>
                            <div class="col-md-6">
                            </div>
                        </div>
                    </div>                    
                </div>
            </div>
        </div>
    </div>
</div>

<!-- jQuery -->
<script src="<?php echo $this->basePath();?>/js/jquery.js"></script>

<!-- Bootstrap Core JavaScript -->
<script src="<?php echo $this->basePath();?>/js/bootstrap.min.js"></script>