<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- <title>Nhà Sách</title> -->

    <!-- Bootstrap Core CSS -->
    <link href="<?php echo $this->basePath();?>/css/bootstrap.min.css" rel="stylesheet">

    <!-- Nha Sach CSS -->
    <link href="<?php echo $this->basePath();?>/css/nhaSach.css" rel="stylesheet">
    <link href="<?php echo $this->basePath();?>/css/bootstrap-overrides.css" rel="stylesheet">
    <link href="<?php echo $this->basePath();?>/css/HTML5admin.css" rel="stylesheet">
    <link href="<?php echo $this->basePath();?>/css/plugins/animate.css" rel="stylesheet">

    <!-- DataTables CSS -->
    <!-- <link href="css/plugins/dataTables.bootstrap.css" rel="stylesheet"> -->
    <link href="<?php echo $this->basePath();?>/css/plugins/jquery.dataTables.css" rel="stylesheet">
    <link href="<?php echo $this->basePath();?>/css/datatables-overrides.css" rel="stylesheet">

    <!-- Custom Fonts -->
    <link href="<?php echo $this->basePath();?>/font-awesome-4.2.0/css/font-awesome.min.css" rel="stylesheet" type="text/css">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body>

    <nav class="navbar navbar-fixed-top" role="navigation">
        <div class="container-fluid">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="<?php echo $this->url('hang_hoa/crud',array('action'=>'index'));?>">
                    <img alt="Brand" src="<?php echo $this->basePath();?>/img/brand.png">
                </a>
            </div>

            <div class="collapse navbar-collapse">
                <ul class="nav navbar-nav">
                    <li>                        
                        <a href="<?php echo $this->url('hang_hoa/crud',array('action'=>'hangHoa'));?>">                        
                            <i class="fa fa-barcode"></i>
                            Hàng hóa
                        </a>
                    </li>
                    <li>                        
                        <a href="<?php echo $this->url('kenh_phan_phoi');?>">
                            <i class="fa fa-cogs"></i>
                            Kênh phân phối
                        </a>
                    </li>
                    <li>
                        <a href="congNo.html">
                            <i class="fa fa-database"></i>
                            Công nợ
                        </a>
                    </li>
                    <li>
                        <a href="loiNhuan.html">
                            <i class="fa fa-line-chart"></i>
                           Lợi nhuận
                        </a>
                    </li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                            <i class="fa fa-bell shake"></i> <span class="badge red">42</span>
                        </a>
                        <ul class="dropdown-menu" id="notifications">
                            <li class="dropdown-header">
                                <i class="fa fa-bell"></i> Notifications
                            </li>
                            <li>
                                <a href="#">
                                    <i class="image fa fa-cog"></i>
                                    <p><i class="fa fa-clock-o"></i> <small>2 hours ago<br></small>This could be a system notification</p>
                                </a>
                            </li>
                            <li>
                                <a href="#">
                                    <i class="image fa fa-flag"></i>
                                    <p><i class="fa fa-clock-o"></i> <small>06/02/2015 14:30<br></small>This could be a system Error/Flag notification</p>
                                </a>
                            </li>
                            <li>
                                <p>You have no notifications.</p>
                            </li>
                        </ul>
                    </li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                            <i class="fa fa-envelope-o shake"></i> <span class="badge blue">2</span>
                        </a>
                        <ul class="dropdown-menu" id="messages">
                            <li class="dropdown-header">
                                <i class="fa fa-envelope-o"></i> Messages
                            </li>
                            <li>
                                <a href="#">
                                    <img class="img-circle" alt="Can you please do..." src="http://placehold.it/48x48">
                                    <p><i class="fa fa-clock-o"></i> <small>2 hours ago<br></small>Can you please do this message very very long so we can see how it breaks? thanks!</p>
                                </a>
                            </li>
                            <li>
                                <a href="#">
                                    <img class="img-circle" alt="Can you please do..." src="http://placehold.it/48x49">
                                    <p><i class="fa fa-clock-o"></i> <small>4 hours ago<br></small>This can be another message, but it's a shorter one..</p>
                                </a>
                            </li>
                            <li>
                                <p>You have no messages.</p>
                            </li>
                        </ul>
                    </li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                            <img src="http://placekitten.com/20/20" style="display:inline" class="img-circle img-responsive"> User Name <b class="caret"></b>
                        </a>
                        <ul class="dropdown-menu">
                            <li>
                                <a href="#"><i class="fa fa-edit"></i> Profile</a>
                            </li>
                            <li>
                                <a href="#"><i class="fa fa-lock"></i> Security</a>
                            </li>
                            <li class="divider"></li>
                            <li class="dropdown-header">Quick Adds</li>
                            <li>
                                <a href="#"><i class="fa fa-tag"></i> Add Product</a>
                            </li>
                            <li>
                                <a href="#"><i class="fa fa-user"></i> Add User</a>
                            </li>
                            <li class="divider"></li>
                            <li class="dropdown-header">Settings</li>
                            <li>
                                <a href="#"><i class="fa fa-signout"></i> Log out</a>
                            </li>
                        </ul>
                    </li>
                </ul>
            </div><!-- /.navbar-collapse -->
        </div><!-- /.container-fluid -->
    </nav>
    <!-- /.nav menu -->

    <div class="container">        
        <?php echo $this->content; ?>
    </div>
    <!-- /.container -->
</body>
</html>
