<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    
    <?php echo $this->headTitle();?>

    <!-- Bootstrap Core CSS -->
    <link href="<?php echo $this->basePath();?>/css/bootstrap.min.css" rel="stylesheet">

    <!-- Nha Sach CSS -->
    <link href="<?php echo $this->basePath();?>/css/nhaSach.css" rel="stylesheet">
    <link href="<?php echo $this->basePath();?>/css/bootstrap-overrides.css" rel="stylesheet">
    <link href="<?php echo $this->basePath();?>/css/HTML5admin.css" rel="stylesheet">
    <link href="<?php echo $this->basePath();?>/css/plugins/animate.css" rel="stylesheet">

    <!-- DataTables CSS -->
    <!-- <link href="css/plugins/dataTables.bootstrap.css" rel="stylesheet"> -->
    <link href="<?php echo $this->basePath();?>/css/plugins/jquery.dataTables.css" rel="stylesheet">
    <link href="<?php echo $this->basePath();?>/css/datatables-overrides.css" rel="stylesheet">

    <!-- Custom Fonts -->
    <link href="<?php echo $this->basePath();?>/font-awesome-4.2.0/css/font-awesome.min.css" rel="stylesheet" type="text/css">    
</head>

<body>

    
    <nav class="navbar navbar-fixed-top" role="navigation">
        <div class="container-fluid">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="<?php echo $this->url('hang_hoa/crud',array('action'=>'index'));?>">
                    <img alt="Brand" src="<?php echo $this->basePath();?>/img/brand.png">
                </a>
            </div>

            <div class="collapse navbar-collapse">
                <ul class="nav navbar-nav">
                    <li>                        
                        <a href="<?php echo $this->url('hang_hoa/crud',array('action'=>'hang-hoa'));?>">                        
                            <i class="fa fa-barcode"></i>
                            Hàng hóa
                        </a>
                    </li>
                    <li>                        
                        <a href="<?php echo $this->url('kenh_phan_phoi');?>">
                            <i class="fa fa-indent"></i>
                            Kênh phân phối
                        </a>
                    </li>
                    <li>                        
                        <a href="<?php echo $this->url('s3u_taxonomy/taxonomys',array('action'=>'chiet-khau'));?>">
                            <i class="glyphicons-magic"></i>
                            <!-- Chiết khấu -->
                            Chính sách bán hàng
                        </a>
                    </li>
                    <li>
                        <a href="<?php echo $this->url('cong_no');?>">
                            <i class="fa fa-compress"></i>
                            <!-- Công nợ -->
                            Thanh toán
                        </a>
                    </li>
                    <li>
                        <a href="<?php echo $this->url('loi_nhuan');?>">
                            <i class="glyphicon glyphicon-usd"></i>
                           <!-- Lợi nhuận -->
                           Bán hàng
                        </a>
                    </li>
                    <?php 
                        if($this->zfcUserIdentity()&&$this->zfcUserIdentity()->getId()==1) 
                        { 
                    ?>
                            <li>
                                <a href="<?php echo $this->url('kho');?>">
                                    <i class="fa fa-share-alt"></i>
                                   Chi nhánh
                                </a>
                            </li>
                    <?php
                        }
                    ?>
                    <?php
                    if($this->zfcUserIdentity())
                    { 
                         $kho=$this->GetTenKho($this->zfcUserIdentity()->getKho());
                    ?>
                        <li title="Bạn đang ở chi nhánh <?php echo $kho->getTenKho(); ?>">
                            <a href="#">
                                <i class="fa fa-hand-o-right"></i>
                               <b style="color:red;">
                                    <?php 
                                        
                                        echo $kho->getTenKho();
                                    ?>
                                </b>
                            </a>
                        </li>
                    <?php
                    }
                    ?>
                    
                </ul>

                <ul class="nav navbar-nav navbar-right">
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                            <i class="fa fa-bell shake"></i> 
                                <span class="badge red">
                                <?php
                                if($this->zfcUserIdentity())
                                {
                                    $responses=$this->GetCongNoQuaHan($this->zfcUserIdentity()->getKho());
                                    $soDonHanQuaHan=count($responses['response']);
                                    echo $soDonHanQuaHan;
                                }
                                else
                                {
                                    echo '0';
                                }
                                ?>
                                </span>
                        </a>
                                                
                        
                            <?php
                            if($this->zfcUserIdentity())
                            { ?>
                                <ul class="dropdown-menu" id="notifications">   
                                <li class="dropdown-header">
                                    <i class="fa fa-bell"></i> Thông báo
                                </li>
                            <?php

                                if($soDonHanQuaHan>0)
                                { 
                                    
                                    foreach ($responses['response'] as $response) {
                                    ?>
                                        <li>
                                            <a href="<?php echo $this->url('cong_no/crud',array('action'=>'chi-tiet-cong-no-khach-hang','id'=>$response['idDoiTac'])); ?>">
                                                <i class="image fa fa-flag"></i>
                                                <p><i class="fa fa-clock-o"></i> 
                                                    <small><b><?php echo $response['hoTenDoiTac']; ?></b>.</small>
                                                    <br><small>Số ngày quá hạn: <b style="color:red"><?php echo $response['soNgayQuaHan']; ?></b>.
                                                    <br></small>Tổng tiền chưa thanh toán: <b style="color:red"><?php echo $response['noCuoiKi']; ?></b></p>
                                            </a>
                                        </li>
                                    <?php                                    
                                    }
                                
                                }
                                else
                                {
                                ?>
                                    <li>
                                        <p>You have no notifications.</p>
                                    </li>
                                <?php
                                }
                                echo '</ul>';
                            }
                            else
                            {
                                echo '<ul></ul>';
                            }
                            ?>
                        
                    </li>
                    <!--
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                            <i class="fa fa-envelope-o shake"></i> <span class="badge blue">2</span>
                        </a>
                        <ul class="dropdown-menu" id="messages">
                            <li class="dropdown-header">
                                <i class="fa fa-envelope-o"></i> Messages
                            </li>
                            <li>
                                <a href="#">
                                    <img class="img-circle" alt="Can you please do..." src="http://placehold.it/48x48">
                                    <p><i class="fa fa-clock-o"></i> <small>2 hours ago<br></small>Can you please do this message very very long so we can see how it breaks? thanks!</p>
                                </a>
                            </li>
                            <li>
                                <a href="#">
                                    <img class="img-circle" alt="Can you please do..." src="http://placehold.it/48x49">
                                    <p><i class="fa fa-clock-o"></i> <small>4 hours ago<br></small>This can be another message, but it's a shorter one..</p>
                                </a>
                            </li>
                            <li>
                                <p>You have no messages.</p>
                            </li>
                        </ul>
                    </li>
                    -->
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                            
                            <span class="glyphicon glyphicon-user"></span>
                            <?php if($this->zfcUserIdentity())
                            { 
                                echo  $this->zfcUserIdentity()->getDisplayName(); 
                            } 
                            else
                            {
                                echo 'User Name';
                            }
                            ?>
                            <b class="caret"></b>
                        </a>                            
                        <?php if($this->zfcUserIdentity()){ ?>
                        <ul class="dropdown-menu">      
                            <li class="divider"></li>
                            <li class="dropdown-header">Quick Adds</li>
                            <li>
                                <a href="<?php echo $this->url('kenh_phan_phoi/crud',array('action'=>'them-khach-hang')); ?>"><i class="fa fa-tag"></i> Thêm khách hàng</a>
                            </li>
                            <li>
                                <a href="<?php echo $this->url('kenh_phan_phoi/crud',array('action'=>'them-nha-cung-cap')); ?>"><i class="fa fa-tag"></i> Add Product</a>
                            </li>
                            <?php if((int)$this->zfcUserIdentity()->getId()==1) { ?>
                                <li>
                                    <a href="<?php echo $this->url('zfcuser/register',array('action'=>'register')); ?>"><i class="fa fa-user"></i> Add User</a>
                                </li>
                            <?php } if((int)$this->zfcUserIdentity()->getId()!=1) { ?>
                                    <li>
                                        <a href="#"><i class="fa fa-user"></i> Add User</a>
                                    </li>
                            <?php } ?>
                            <li class="divider"></li>
                            <li class="dropdown-header">Settings</li>
                            <li>
                                <a href="<?php echo $this->url('application/default',array('controller'=>'Index','action'=>'logout'));?>"><i class="fa fa-signout"></i> Log out</a>
                            </li>
                        </ul>
                        <?php } ?>
                        
                    </li>
                </ul>
            </div><!-- /.navbar-collapse -->
        </div><!-- /.container-fluid -->
    </nav>
    <!-- /.nav menu -->
    <div class="container">        
        <?php echo $this->content; ?>
    </div>
    
</body>
</html>
