<?php 
    echo $this->headTitle('Phiếu nhập');
?>

<div class="row">
    <div class="col-md-2">
        <div class="h5a-sidebar affix">
            <span class="breadcrumb row">
                <a href="<?php echo $this->url('hang_hoa/crud',array('action'=>'index'));?>">/ Kho</a>                        
                <a href="<?php echo $this->url('kenh_phan_phoi',array('action'=>'index'));?>">/ Khách hàng</a>
                 / Phiếu xuất /
            </span>
            <ul class="nav h5a-sidenav nav-list accordion">
                <li>
                    <a href="<?php echo $this->url('loi_nhuan/crud',array('action'=>'index'));?>">
                        <i class="fa fa-flag-checkered"></i> Doanh thu
                    </a>
                </li>
                <li>
                    <a href="<?php echo $this->url('loi_nhuan/crud',array('action'=>'don-hang'));?>">
                        <i class="fa fa-cubes"></i> Phiếu xuất
                    </a>
                </li>
                <li>
                    <a href="<?php echo $this->url('loi_nhuan/crud',array('action'=>'phieu-nhap'));?>">
                        <i class="fa fa-tasks"></i> Phiếu nhập
                    </a>
                </li>
                
            </ul>
        </div>
    </div>
    <div class="col-md-10" role="main">
        <div class="h5a-docs-section">
            <div class="page-header">
                <div class="row">
                    <div class="col-sm-6">
                        <h1>Phiếu nhập</h1>
                    </div>
                    <div class="col-sm-6">
                        <div class="pull-right">
                            <div class="btn-group ">
                                <button type="button" class="h5a-btn btn btn-default btn-sm">
                                    <i class="fa fa-chevron-left"></i>
                                </button>                                    
                                <button type="button" class="h5a-btn btn btn-default btn-sm">
                                    <i class="fa fa-chevron-right"></i>
                                </button>
                            </div>
                            <a href="<?php echo $this->url('loi_nhuan/crud',array('action'=>'export-phieu-nhap')); ?>">
                             <button type="button" class="h5a-btn btn btn-default btn-sm">Export</button></a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="box">
                <ul class="nav nav-tabs" role="tablist" id="myTab">
                    <li role="presentation" class="active">
                        <a href="#home" role="tab" data-toggle="tab">Tất cả</a>
                    </li>
                               
                </ul>
                <div class="tab-content">
                    <div role="tabpanel" class="tab-pane active" id="home">
                        <div class="container">
                            <div class="row">
                                <table id="" class="dataTables-example">
                                    <thead>
                                        <th><input type="checkbox"/></th>
                                        <th>Ngày</th>
                                        <th>Phiếu nhập</th>                                       
                                        <th>Khách hàng</th>
                                        <th>Thanh toán</th>
                                        <th>Tổng tiền</th>
                                    </thead>
                                    <tbody>
                                    <?php
                                        foreach($phieuNhaps as $phieuNhap)
                                        {?>
                                        <tr>
                                            <td><input type="checkbox"/></td>
                                            <td><?php echo $phieuNhap->getNgayNhap()->format('d-m-Y'); ?></td>
                                            <td>
                                                <a href="<?php echo $this->url('kenh_phan_phoi/crud',array('action'=>'chi-tiet-phieu-nhap','id'=>$phieuNhap->getIdPhieuNhap()));?>"><?php echo '#'.$phieuNhap->getMaPhieuNhap(); ?></a>
                                            </td>
                                            
                                            <td><a href="<?php echo $this->url('kenh_phan_phoi/crud',array('action'=>'chi-tiet-nha-cung-cap','id'=>$phieuNhap->getIdDoiTac()->getIdDoiTac()));?>"><?php echo $phieuNhap->getIdDoiTac()->getHoTen(); ?></a></td>
                                            <td>
                                            <?php 
                                                if($phieuNhap->getStatus()==0)
                                                {
                                                    ?>
                                                    <span class="label label-warning">
                                                        Ghi nợ
                                                    </span>
                                                    <?php
                                                }
                                                else
                                                {
                                                    ?>
                                                    <span class="label label-success">Đã thanh toán
                                                    </span>
                                                    <?php
                                                }
                                            ?>
                                            </td>
                                            <td>
                                            <?php
                                                $tongTien=0;
                                                foreach ($phieuNhap->getCtPhieuNhaps() as $ctPhieuNhap) {
                                                    $tongTien+=(float)$ctPhieuNhap->getGiaNhap()*(float)$ctPhieuNhap->getSoLuong();
                                                }
                                                echo number_format($tongTien,'0','',' ');
                                            ?>
                                            </td>
                                        </tr>
                                        <?php
                                        }
                                    ?>
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>

                </div>
            </div>
        </div>
    </div>
</div>
<!-- /.container -->

    <!-- jQuery -->
    <script src="<?php echo $this->basePath();?>/js/jquery.js"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="<?php echo $this->basePath();?>/js/bootstrap.min.js"></script>

    <!-- DataTables JavaScript -->
    <script src="<?php echo $this->basePath();?>/js/plugins/dataTables/jquery.dataTables.js"></script>

    <!-- Page-Level Demo Scripts - Tables - Use for reference -->
    <script>
    $(document).ready(function() {
        $('.dataTables-example').dataTable({
            "pagingType": "simple",
            "bPaginate": true,
            "bLengthChange": true,
            "bFilter": true,
            "bInfo": true,
            "bAutoWidth": true
        });
    });
    </script>