<head>
    <meta charset="UTF-8">    
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>Bảng Giá</title>
</head>
<div class="container">
        <div class="row">
            <div class="col-md-2">
                <div class="h5a-sidebar affix">
                    <span class="breadcrumb row">
                        <a href="#">/ Kho</a>
                        <a href="<?php echo $this->url('hang_hoa');?>">/ Hàng hóa</a>
                         / Bảng giá /
                    </span>
                    <ul class="nav h5a-sidenav nav-list accordion">
                        <!-- <li class="sidenav-messages dark">
                            <span class="pull-right"><i class="fa fa-times"></i></span>
                            <h4 class="underline red"><i class="fa fa-exclamation-triangle"></i> Warning!</h4>
                            <p class="black">This can be a perfect place for <strong>important communication</strong>, a response after a form has been sent...or anything else (like buttons, small forms, social sharing widget, etc.)<br></p>
                        </li> -->
                        <li>
                            <a href="<?php echo $this->url('hang_hoa');?>">
                                <i class="fa fa-cubes"></i> Danh sách hàng
                            </a>
                        </li>
                        <li>
                            <!-- <a href="nhapHang.html"> -->
                            <a href="<?php echo $this->url('hang_hoa/crud',array('action'=>'nhapHang'));?>">
                                <i class="fa fa-download"></i> Nhập hàng
                            </a>
                        </li>
                        <li>
                            <!-- <a href="xuatHang.html"> -->
                            <a href="<?php echo $this->url('hang_hoa/crud',array('action'=>'xuatHang'));?>">
                                <i class="fa fa-upload"></i> Xuất hàng
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
            <div class="col-md-10" role="main">
                <div class="h5a-docs-section">
                    <div class="page-header">
                        <div class="row">
                            <div class="col-sm-6">
                                <h1>Bảng giá</h1>
                            </div>
                            <div class="col-sm-6">
                                <div class="pull-right">
                                    <div class="btn-group ">
                                        <button type="button" class="h5a-btn btn btn-default btn-sm">
                                            <i class="fa fa-chevron-left"></i>
                                        </button>                                    
                                        <button type="button" class="h5a-btn btn btn-default btn-sm">
                                            <i class="fa fa-chevron-right"></i>
                                        </button>
                                    </div>
                                    <div class="btn-group ">
                                        <button type="button" class="h5a-btn btn btn-default btn-sm">Import</button>
                                        <button type="button" class="h5a-btn btn btn-default btn-sm">Export</button>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="box">
                        <ul class="nav nav-tabs" role="tablist" id="myTab">
                            <li role="presentation" class="active">
                                <a href="#home" role="tab" data-toggle="tab">Tất cả</a>
                            </li>
                        </ul>
                        <div class="tab-content">
                            <div role="tabpanel" class="tab-pane active" id="home">
                                <div class="container">
                                    <div class="row">
                                        <table id="dataTables-example" class="">
                                            <thead>
                                                <th><input type="checkbox"/></th>
                                                <th>Sản phẩm</th>
                                                <th>Đơn vị tính</th>
                                                <th>Giá nhập</th>
                                                <th>Giá điểm bán</th>
                                                <th>Giá cơ quan</th>
                                                <th>Giá trường học</th>
                                                <th>Giá bán lẻ</th>
                                            </thead>
                                            <tbody>
                                                <tr>
                                                    <td><input type="checkbox"/></td>
                                                    <td><img src="img/brand.png" height="40"> <a href="sanPham.html">Giấy in Lucky 100g</a></td>
                                                    <td>Thùng</td>
                                                    <td>70.000</td>
                                                    <td>72.000</td>
                                                    <td>71.000</td>
                                                    <td>71.000</td>
                                                    <td>75.000</td>
                                                </tr>
                                                <tr>
                                                    <td><input type="checkbox"/></td>
                                                    <td><img src="img/brand.png" height="40"> <a href="sanPham.html">Giấy in Lucky 100g</a></td>
                                                    <td>Thùng</td>
                                                    <td>70.000</td>
                                                    <td>72.000</td>
                                                    <td>71.000</td>
                                                    <td>71.000</td>
                                                    <td>75.000</td>
                                                </tr>
                                                <tr>
                                                    <td><input type="checkbox"/></td>
                                                    <td><img src="img/brand.png" height="40"> <a href="sanPham.html">Giấy in Lucky 100g</a></td>
                                                    <td>Thùng</td>
                                                    <td>70.000</td>
                                                    <td>72.000</td>
                                                    <td>71.000</td>
                                                    <td>71.000</td>
                                                    <td>75.000</td>
                                                </tr>
                                                <tr>
                                                    <td><input type="checkbox"/></td>
                                                    <td><img src="img/brand.png" height="40"> <a href="sanPham.html">Giấy in Lucky 100g</a></td>
                                                    <td>Thùng</td>
                                                    <td>70.000</td>
                                                    <td>72.000</td>
                                                    <td>71.000</td>
                                                    <td>71.000</td>
                                                    <td>75.000</td>
                                                </tr>
                                                <tr>
                                                    <td><input type="checkbox"/></td>
                                                    <td><img src="img/brand.png" height="40"> <a href="sanPham.html">Giấy in Lucky 100g</a></td>
                                                    <td>Thùng</td>
                                                    <td>70.000</td>
                                                    <td>72.000</td>
                                                    <td>71.000</td>
                                                    <td>71.000</td>
                                                    <td>75.000</td>
                                                </tr>
                                                <tr>
                                                    <td><input type="checkbox"/></td>
                                                    <td><img src="img/brand.png" height="40"> <a href="sanPham.html">Giấy in Lucky 100g</a></td>
                                                    <td>Thùng</td>
                                                    <td>70.000</td>
                                                    <td>72.000</td>
                                                    <td>71.000</td>
                                                    <td>71.000</td>
                                                    <td>75.000</td>
                                                </tr>
                                                <tr>
                                                    <td><input type="checkbox"/></td>
                                                    <td><img src="img/brand.png" height="40"> <a href="sanPham.html">Giấy in Lucky 100g</a></td>
                                                    <td>Thùng</td>
                                                    <td>70.000</td>
                                                    <td>72.000</td>
                                                    <td>71.000</td>
                                                    <td>71.000</td>
                                                    <td>75.000</td>
                                                </tr>
                                                <tr>
                                                    <td><input type="checkbox"/></td>
                                                    <td><img src="img/brand.png" height="40"> <a href="sanPham.html">Giấy in Lucky 100g</a></td>
                                                    <td>Thùng</td>
                                                    <td>70.000</td>
                                                    <td>72.000</td>
                                                    <td>71.000</td>
                                                    <td>71.000</td>
                                                    <td>75.000</td>
                                                </tr>
                                                <tr>
                                                    <td><input type="checkbox"/></td>
                                                    <td><img src="img/brand.png" height="40"> <a href="sanPham.html">Giấy in Lucky 100g</a></td>
                                                    <td>Thùng</td>
                                                    <td>70.000</td>
                                                    <td>72.000</td>
                                                    <td>71.000</td>
                                                    <td>71.000</td>
                                                    <td>75.000</td>
                                                </tr>
                                                <tr>
                                                    <td><input type="checkbox"/></td>
                                                    <td><img src="img/brand.png" height="40"> <a href="sanPham.html">Giấy in Lucky 100g</a></td>
                                                    <td>Thùng</td>
                                                    <td>70.000</td>
                                                    <td>72.000</td>
                                                    <td>71.000</td>
                                                    <td>71.000</td>
                                                    <td>75.000</td>
                                                </tr>
                                                <tr>
                                                    <td><input type="checkbox"/></td>
                                                    <td><img src="img/brand.png" height="40"> <a href="sanPham.html">Giấy in Lucky 100g</a></td>
                                                    <td>Thùng</td>
                                                    <td>70.000</td>
                                                    <td>72.000</td>
                                                    <td>71.000</td>
                                                    <td>71.000</td>
                                                    <td>75.000</td>
                                                </tr>
                                                <tr>
                                                    <td><input type="checkbox"/></td>
                                                    <td><img src="img/brand.png" height="40"> <a href="sanPham.html">Giấy in Lucky 100g</a></td>
                                                    <td>Thùng</td>
                                                    <td>70.000</td>
                                                    <td>72.000</td>
                                                    <td>71.000</td>
                                                    <td>71.000</td>
                                                    <td>75.000</td>
                                                </tr>
                                            </tbody>
                                        </table>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>