<script type="text/javascript">
    functionLocTheoLoaiHang = function(){
        document.getElementById("locTheoLoaiHang").click();
    }

    functionLocTheoNhanHang = function(){
        document.getElementById("locTheoNhanHang").click();
    }

    functionKiemTraDieuKienLoc = function(){
        if(!document.getElementById("dieuKienLoc").value)
        {
           $('#thongBaoLoi').text('Chưa nhập điều kiện lọc');
            return false;
        }
        return true;
    }
</script>    
<?php
    $this->headTitle('Hàng hóa');    
?>

<div class="row">
    <div class="col-md-2">
        <div class="h5a-sidebar affix">
            <span class="breadcrumb row">
                <a href="<?php echo $this->url('hang_hoa/crud',array('action'=>'index'));?>">/ Kho</a>
                 / Hàng hóa /
            </span>
            <ul class="nav h5a-sidenav nav-list accordion">                        
                <li>                            
                    <a href="<?php echo $this->url('hang_hoa/crud',array('action'=>'bangGia'));?>">                                 
                        <i class="fa fa-list-alt"></i> Bảng giá
                    </a>
                </li>
                <li>                            
                    <a href="<?php echo $this->url('hang_hoa/crud',array('action'=>'nhapHang'));?>">
                        <i class="fa fa-download"></i> Nhập hàng
                    </a>
                </li>
                <li>
                    <a href="<?php echo $this->url('hang_hoa/crud',array('action'=>'xuatHang'));?>">
                        <i class="fa fa-upload"></i> Xuất hàng
                    </a>
                </li>
            </ul>
        </div>
    </div>
    <div class="col-md-10" role="main">
        <?php
            $flash=$this->flashMessenger();
            $flash->setMessageOpenFormat('<div%s>
             <button type="button" class="close" data-dismiss="alert" aria-hidden="true">
                 &times;
             </button>
             <ul><li>')
             ->setMessageSeparatorString('</li><li>')
             ->setMessageCloseString('</li></ul></div>');

             echo $flash->render('error',   array('alert', 'alert-dismissable', 'alert-danger'));
             echo $flash->render('info',    array('alert', 'alert-dismissable', 'alert-info'));
             echo $flash->render('default', array('alert', 'alert-dismissable', 'alert-warning'));
             echo $flash->render('success', array('alert', 'alert-dismissable', 'alert-success'));
        ?>
        <div class="h5a-docs-section">
            <div class="page-header">
                <div class="row">
                    <div class="col-sm-6">
                        <h1>Hàng hóa</h1>
                    </div>                    
                    <div class="col-sm-6">
                        <div class="pull-right">                                    
                            <div class="btn-group ">
                                <button id="btPrev" type="button" class="h5a-btn btn btn-default btn-sm">
                                    <i class="fa fa-chevron-left"></i>
                                </button>                                    
                                <button id="btNext" type="button" class="h5a-btn btn btn-default btn-sm">
                                    <i class="fa fa-chevron-right"></i>
                                </button>
                            </div>
                            <div class="btn-group ">                
                                <?php
                                    $form->setAttribute('action', $this->url('hang_hoa/crud', array('action' => 'importHangHoa')));
                                    $form->setAttribute('role','form');
                                    $form->setAttribute('name','frmImport');
                                    $form->setAttribute('style','margin-top: 0px;margin-bottom:0px;');
                                    $form->prepare();
                                    echo $this->form()->openTag($form);
                                    $file=$form->get('file');                                        
                                    $file->setAttribute('style','display:none');
                                    $file->setAttribute('onchange','return hamSubmit();');       
                                    echo $this->formElement($file);
                                ?>
                                    <button type="button" class="h5a-btn btn btn-default btn-sm" onclick="return Import();">Import</button>
                                    <a href="<?php echo $this->url('hang_hoa/crud',array('action'=>'exportHangHoa')); ?>">
                                    <button type="button" class="h5a-btn btn btn-default btn-sm">Export</button></a>
                                <?php
                                    echo $this->form()->closeTag();
                                ?>
                            </div>
                            <a href="<?php echo $this->url('hang_hoa/crud',array('action'=>'themSanPham'));?>" type="button" class="h5a-btn btn btn-primary btn-sm">Thêm mới</a>
                        </div>
                    </div>
                </div>
            </div>            
            <div class="box">
                <ul class="nav nav-tabs" role="tablist" id="myTab">
                    <li role="presentation" class="active">
                        <a href="#home" role="tab" data-toggle="tab">Tất cả</a>
                    </li>
                </ul>
                <div class="tab-content">
                    <div role="tabpanel" class="tab-pane active" id="home">
                        <div class="container">
                            <div class="row bottom20" style="margin-bottom: -20px;margin-top:-20px">                                        
                                <?php
                                    // gửi tới form loc hang hóa
                                    $url=$this->url('hang_hoa/crud', array('action' => 'locHangHoa'));
                                ?>
                                <form method="post" action="<?php echo $url; ?>" onSubmit="return functionKiemTraDieuKienLoc();">
                                <div class="input-group has-feedback">                                   
                                    
                                    <input type="text" class="form-control h5a-input" id="dieuKienLoc" name="dieuKienLoc"> 
                                    <!--<i class="glyphicon glyphicon-search form-control-feedback"></i>-->
                                    <div class="input-group-btn">                                       
                                        <button type="button" class="btn btn-default h5a-btn dropdown-toggle" data-toggle="dropdown">Lọc sản phẩm <span class="caret"></span></button>
                                        <ul class="dropdown-menu" role="menu">
                                            <li><a onclick="functionLocTheoLoaiHang();" >Loại hàng</a></li>
                                            <li><a onclick="functionLocTheoNhanHang();">Nhãn hàng</a></li>
                                        </ul>
                                    </div><!-- /btn-group -->
                                    <input type="submit" id="locTheoLoaiHang" name="locHangHoa" hidden="true" value="locTheoLoaiHang"> 
                                    <input type="submit" id="locTheoNhanHang" name="locHangHoa" hidden="true" value="locTheoNhanHang"> 
                                </div>
                                <span id="thongBaoLoi" class="badge red"></span>
                                </form> 
                            </div>

                            <div class="row">
                                <table id="dataTables-example" class="">
                                    <thead>
                                        <th><input type="checkbox"/></th>
                                        <th>Sản phẩm</th>
                                        <th>Tồn kho</th>
                                        <th>Loại</th>
                                        <th>Nhãn hàng</th>
                                    </thead>
                                    <tbody> 
                                    <!-- lấy dữ liệu và xuất ra form  -->
                                    <?php foreach ($sanPhams as $sanPham) {?>                
                                        <tr>
                                            <td><input type="checkbox"/></td>
                                            <td><img src="<?php echo $this->basePath();?>/img/<?php echo $sanPham->getHinhAnh(); ?>" height="40" width="40px"> <a href="<?php echo $this->url('hang_hoa/crud',array('action'=>'sanPham', 'id'=>$sanPham->getIdSanPham()));?>"><?php echo $sanPham->getTenSanPham(); ?></a></td>
                                            <td><?php echo $sanPham->getTonKho(); ?></td>
                                            <td><?php echo $sanPham->getIdLoai()->getTermId()->getName(); ?></td>
                                            <td><?php echo $sanPham->getNhan(); ?></td>
                                        </tr>
                                    <?php } ?>
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<!-- jQuery -->
<script src="<?php echo $this->basePath();?>/js/jquery.js"></script>

<!-- Bootstrap Core JavaScript -->
<script src="<?php echo $this->basePath();?>/js/bootstrap.min.js"></script>

<!-- DataTables JavaScript -->
<script src="<?php echo $this->basePath();?>/js/plugins/dataTables/jquery.dataTables.js"></script>

<!-- Page-Level Demo Scripts - Tables - Use for reference -->
<script>
$(document).ready(function() {
    $('#dataTables-example').dataTable({
        "pagingType": "simple",
        "bPaginate": true,
        "bLengthChange": true,
        "bFilter":false,
        "bInfo": true,
        "bAutoWidth": true
    });
});

Import=function()
{
    document.getElementById('file').click();   
    return false;     
}

hamSubmit=function(){
    var valueFile=document.getElementById('file').value;
    if(valueFile)
    {               
        document.frmImport.submit();
        return true;           
    }
}

$('#btPrev').click(function(){
    document.getElementById('dataTables-example_previous').click();
});

$('#btNext').click(function(){
    document.getElementById('dataTables-example_next').click();
});    
</script>