<?php
$this->headTitle('Hàng hóa');
if($import==1)
{
	if(count($listMaSanPham)>0)	
	{ ?>	
		<div align="center">
			<h3>DANH SÁCH CÁC MÃ SẢN PHẨM KHÔNG THỂ IMPORT</h3>
			<table>
				<?php
				$i=0;
				foreach ($listMaSanPham as $list) {?>
					<tr>
						<td><?php echo ++$i; ?>.</td>
						<td><?php echo $list; ?></td>
					</tr>			
				<?php }?>
			</table>		
		</div>
	<?php }	
	if(count($listMaSanPham)==0)
	{?>
		<script type="text/javascript">
			alert('Import thành công');	
			window.history.back(-1);
		</script>
	<?php }
}
else
{ ?>
	<script type="text/javascript">
		alert('Tập tin import không hợp lệ!');	
		window.history.back(-1);
	</script>
<?php }?>

