<?php
$this->headTitle('Bảng giá');
if($import==1)
{
	if(count($listMaSanPham)>0)	
	{ ?>	
		<div align="center">
			<h3>DANH SÁCH CÁC MÃ SẢN PHẨM KHÔNG THỂ IMPORT BẢNG GIÁ</h3>
			<table>
				<?php
				$i=0;
				foreach ($listMaSanPham as $list) {?>
					<tr>
						<td><?php echo ++$i; ?>.</td>
						<td><?php echo $list; ?></td>
					</tr>			
				<?php }?>
			</table>			
		</div>		
		<div class="page-footer">
            <div class="row bottom20">
                <div class="col-sm-7 col-sm-offset-3">
                    <div class="col-sm-5 col-sm-offset-3">
                        <a href="<?php echo $this->url('hang_hoa/crud',array('action'=>'bangGia'));?>"><button type="button" class="btn h5a-btn btn-primary full">Trở về</button></a>                        
                    </div>
                </div>
            </div>
        </div>
	<?php }	
	if(count($listMaSanPham)==0)
	{
		$flash=$this->flashMessenger();
		$flash->setMessageOpenFormat('<div%s>
		 <button type="button" class="close" data-dismiss="alert" aria-hidden="true">
		     &times;
		 </button>
		 <ul><li>')
		 ->setMessageSeparatorString('</li><li>')
		 ->setMessageCloseString('</li></ul></div>');

		 echo $flash->render('error',array('alert', 'alert-dismissable', 'alert-danger'));
		 echo $flash->render('info',array('alert', 'alert-dismissable','alert-info'));
		 echo $flash->render('default',array('alert', 'alert-dismissable','alert-warning'));
		 echo $flash->render('success',array('alert','alert-dismissable','alert-success'));
	}
}
else
{ 
	$flash=$this->flashMessenger();
	$flash->setMessageOpenFormat('<div%s>
	 <button type="button" class="close" data-dismiss="alert" aria-hidden="true">
	     &times;
	 </button>
	 <ul><li>')
	 ->setMessageSeparatorString('</li><li>')
	 ->setMessageCloseString('</li></ul></div>');

	 echo $flash->render('error',   array('alert', 'alert-dismissable', 'alert-danger'));
	 echo $flash->render('info',    array('alert', 'alert-dismissable', 'alert-info'));
	 echo $flash->render('default', array('alert', 'alert-dismissable', 'alert-warning'));
	 echo $flash->render('success', array('alert', 'alert-dismissable', 'alert-success'));

	 echo '<meta http-equiv="refresh" content="3;bangGia"/>';
}
?>
<!-- jQuery -->
<script src="<?php echo $this->basePath();?>/js/jquery.js"></script>

<!-- Bootstrap Core JavaScript -->
<script src="<?php echo $this->basePath();?>/js/bootstrap.min.js"></script>