<style type="text/css">
    #san-pham-search-result{ cursor:pointer;}
    #search-result{cursor:pointer;}
    .table{width: 790px; font-size: 13px; margin-top: -60px}
    @media print {        
        .table{width: 790px; font-size: 13px; margin-top: -60px}
        .tb{width: 97%;}
        .td{width: 90px;}  
        table td{padding: 5px;}      
                
        .col-md-2{display: none;}
        .page-header{display: none;}
        .tbIn{display: block;}
        #formNhapHang{display: none;}
    }
    
</style>
<?php
$d=$hoaDon->getNgayXuat()->format('d');
$m=$hoaDon->getNgayXuat()->format('m');
$y=$hoaDon->getNgayXuat()->format('Y');
?>
<div class="row">
    <div class="col-md-2">
        <div class="h5a-sidebar affix">
            <span class="breadcrumb row">
                <a href="<?php echo $this->url('hang_hoa/crud',array('action'=>'index'));?>">/ Kho</a>                        
                <a href="<?php echo $this->url('kenh_phan_phoi',array('action'=>'index'));?>">/ Khách hàng</a>
                 / Đơn hàng /
            </span>
            <ul class="nav h5a-sidenav nav-list accordion">
                <li>                            
                    <a href="<?php echo $this->url('hang_hoa/crud',array('action'=>'bang-gia'));?>">                                 
                        <i class="fa fa-list-alt"></i> Bảng giá
                    </a>
                </li>
                <li>
                    <a href="<?php echo $this->url('hang_hoa/crud',array('action'=>'hang-hoa'));?>">
                        <i class="glyphicon glyphicon-align-justify"></i> Danh sách hàng
                    </a>
                </li>
                <li>
                    <a href="<?php echo $this->url('hang_hoa/crud',array('action'=>'nhap-hang'));?>">
                        <i class="glyphicon glyphicon-import"></i> Nhập hàng
                    </a>
                </li>
                <li>
                    <a href="<?php echo $this->url('hang_hoa/crud',array('action'=>'xuat-hang'));?>">
                        <i class="glyphicon glyphicon-export"></i> Xuất hàng
                    </a>
                </li>
                <li>
                    <a href="<?php echo $this->url('hang_hoa/crud',array('action'=>'doi-tra-hang'));?>">
                        <i class="glyphicon glyphicon-transfer"></i> Đổi trả hàng
                    </a>
                </li>
            </ul>
        </div>
    </div>
    <div class="col-md-10" role="main">
        <div class="h5a-docs-section">
            <div class="page-header">
                
            </div>           
            <div>
                <table class="table">
                    <tr style="text-align: -moz-center; border-style:hidden">
                        <td>
                            <table border="0" class="tb">
                                <tr>
                                    <td style="width:60%">
                                        <b>
                                            NHÀ SÁCH VINH QUANG</br>
                                            45A Phạm Ngũ Lão, Phường 1, TP. Trà Vinh</br>
                                            Mã số thuế: 
                                        </b>
                                    </td>
                                    <td style="text-align:center">
                                        <b>Mẫ số: 02 - TT</b></br>
                                        (Ban hành theo QĐ số: 15/2006/QĐ-BTC ngày 20/3/2006 của Bộ trưởng BTC)
                                    </td>            
                                </tr>
                            </table>

                            <table border="0" style="width:65%; margin-left:220px"  class="tb">
                                <tr>
                                    <td style="width:50%; padding:0px 0px 0px 30px; font-size:16px; font-weight:bold">PHIẾU XUẤT KHO</td>
                                    <td></td>
                                </tr>
                                <tr>
                                    <td style="padding:0px;">Ngày <?php echo $d;?> tháng <?php echo $m;?> năm <?php echo $y;?></td>
                                    <td style="padding:0px;">
                                        Nợ: ........................................
                                    </td>
                                </tr>
                                <tr>
                                    <td style="padding:0px;">
                                        Số: ........................................<div style="margin-top:-22px; margin-left: 30px;"><?php echo $hoaDon->getMaHoaDon(); ?></div>
                                    </td>
                                    <td style="padding:0px;">
                                        Có: ........................................
                                    </td>
                                </tr>
                            </table>

                            <table border="0"  class="tb">
                                <tr>
                                    <td colspan="4">
                                        - Họ và tên người nhận hàng:.................................................... Địa chỉ (bộ phận).....................
                                        <div style="margin-top:-22px; margin-left:200px;"><?php echo $hoaDon->getIdDoiTac()->getHoTen(); ?></div><div style="margin-top:-22px; margin-left:510px;"><?php echo $hoaDon->getIdDoiTac()->getDiaChi(); ?></div>

                                    </td>
                                </tr>
                                
                                <tr>
                                    <td style="width:200px">
                                        <span>- Theo....................</span>
                                    </td>
                                    <td style="width:100px">
                                        số....................
                                    </td>
                                    <td style="width:215px">
                                        Ngày <?php echo $d;?> tháng <?php echo $m;?> năm <?php echo $y;?>
                                    </td>
                                    <td>                            
                                        của................
                                    </td>
                                </tr>
                                <tr>
                                    <td colspan="2">                        
                                        Xuất tại kho:.................
                                    </td>                    
                                    <td colspan="2">                            
                                        Địa điểm..........................................................................................
                                    </td>
                                </tr>
                                <tr><td></td></tr>
                            </table>

                            <table border="1" id="tbSanPham">
                                <tr style="text-align:center">
                                    <td rowspan="2" style="width:45px">STT</td>
                                    <td rowspan="2">Tên, nhãn hiệu quy cách, phẩm chất vật tư, dụng cụ sản phẩm, hàng hóa</td>
                                    <td rowspan="2" class="td">Mã số</td>
                                    <td rowspan="2" class="td">Đơn vị tính</td>
                                    <td colspan="2" style="width:300px">Số lượng</td>
                                    <td rowspan="2" class="td">Đơn giá</td>
                                    <td rowspan="2" class="td">Thành tiền</br>(vnđ)</td>
                                </tr>
                                <tr style="text-align:center">
                                    <td>Theo chứng từ</td>
                                    <td>Thực xuất</td>
                                </tr>
                                <?php
                                    $stt=0; $tongCong=0;
                                    foreach ($hoaDon->getCtHoaDons() as $chiTietHoaDon) {
                                        $stt++;
                                ?>
                                        <tr style="text-align:center">
                                            <td><?php echo $stt; ?></td>
                                            <td><?php echo $chiTietHoaDon->getIdSanPham()->getTenSanPham(); ?></td>
                                            <td><?php echo $chiTietHoaDon->getIdSanPham()->getMaSanPham(); ?></td>
                                            <td><?php echo $chiTietHoaDon->getIdSanPham()->getIdDonViTinh()->getTermId()->getName(); ?></td>
                                            <td></td>
                                            <td style="white-space:nowrap;"><?php echo number_format($chiTietHoaDon->getSoLuong(),'0','',' '); ?></td>
                                            <td style="white-space:nowrap;">
                                                <?php 
                                                    echo number_format($chiTietHoaDon->getGia(),'0','',' ');
                                                ?>
                                            </td>
                                            <td width="100px" style="white-space:nowrap;">
                                            <?php 
                                                
                                                $thanhTien=(float)$chiTietHoaDon->getGia()*(float)$chiTietHoaDon->getSoLuong();
                                                
                                                echo number_format($thanhTien,'0','',' ');
                                                $tongCong+=$thanhTien;

                                            ?>
                                            </td>
                                            
                                        </tr>     
                                <?php
                                    }
                                ?>
                                <tr style="text-align:center">
                                    <td rowspan="2" style="width:45px"></td>
                                    <td rowspan="2"><b>Tổng cộng</b></td>
                                    <td rowspan="2" class="td"></td>
                                    <td rowspan="2" class="td"></td>
                                    <td colspan="2" style="width:300px"></td>
                                    <td rowspan="2" class="td"></td>
                                    <td rowspan="2" class="td" style="white-space:nowrap;"><b><?php echo number_format($tongCong,'0','',' '); ?></b></td>
                                </tr>                 
                            </table>
                        </td>
                    </tr>
                    <tr style="border-style:hidden">
                        <td style="padding-left:20px">- Tổng số tiền (viết bằng chữ): <span id="tongSoTien"></span>&nbsp;đồng</td>
                    </tr>
                    <tr style="border-style:hidden">
                        <td style="padding-left:20px">
                            - Số chứng từ gốc kèm theo: .....................................................................................................................................
                        </td>
                    </tr>
                    <tr style="text-align: -moz-center">
                        <td>
                            <table border="0" class="tb" style="width:100%;">
                                <tr>
                                    <td colspan="5" style="text-align:right">Ngày <?php echo $d;?> tháng <?php echo $m;?> năm <?php echo $y;?></td>
                                </tr>
                                <tr style="text-align: center;">
                                    <td>
                                        Người lập phiếu</br>(Ký, họ tên)
                                    </td>
                                    <td>
                                        Người nhận hàng</br>(Ký, họ tên)
                                    </td>
                                    <td>
                                        Thủ kho</br>(Ký, họ tên)
                                    </td>
                                    <td>
                                        Thủ trưởng đơn vị</br>(Ký, họ tên)
                                    </td>
                                    <td>
                                        Giám đốc</br>(Ký, họ tên)
                                    </td>
                                </tr>
                                <tr>
                                    <td style="height:100px"></td>
                                </tr> 
                                          
                            </table>
                        </td>
                    </tr>
                </table>
            </div>
        </div>
    </div>
</div>
<form method="post" action="<?php echo $this->url('hang_hoa/crud',array('action'=>'hang-hoa')); ?>" id="nhapHang">
</form>
<!-- FormatNumber -->
    <script src="<?php echo $this->basePath();?>/js/formatnumber.js"></script>

    <!-- convernumbertostring -->
    <script src="<?php echo $this->basePath();?>/js/convernumbertostring.js"></script>

    <!-- jQuery -->
    <script src="<?php echo $this->basePath();?>/js/jquery.js"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="<?php echo $this->basePath();?>/js/bootstrap.min.js"></script>

    <!-- DataTables JavaScript -->
    <script src="<?php echo $this->basePath();?>/js/plugins/dataTables/jquery.dataTables.js"></script>
    <!-- Page-Level Demo Scripts - Tables - Use for reference -->
    <script type="text/javascript">
        $(document).ready(function(){
            var tongSoTien=docso(<?php echo $tongCong; ?>);
            $('#tongSoTien').text(tongSoTien);

            window.print();   
            document.getElementById('nhapHang').submit();         
        })
    </script>
