<?php
    //die(var_dump());
?>
<head>
   <!--  <meta charset="UTF-8">    
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content=""> -->
    <title>Hàng Hóa</title>
</head>
<div class="container">
        <div class="row">
            <div class="col-md-2">
                <div class="h5a-sidebar affix">
                    <span class="breadcrumb row">
                        <a href="index.html">/ Kho</a>
                         / Hàng hóa /
                    </span>
                    <ul class="nav h5a-sidenav nav-list accordion">                        
                        <li>                            
                            <a href="<?php echo $this->url('hang_hoa/crud',array('action'=>'bangGia'));?>"                                 
                                <i class="fa fa-list-alt"></i> Bảng giá
                            </a>
                        </li>
                        <li>
                            <!-- <a href="nhapHang.html"> -->
                            <a href="<?php echo $this->url('hang_hoa/crud',array('action'=>'nhapHang'));?>" 
                                <i class="fa fa-download"></i> Nhập hàng
                            </a>
                        </li>
                        <li>
                            <a href="<?php echo $this->url('hang_hoa/crud',array('action'=>'xuatHang'));?>">
                                <i class="fa fa-upload"></i> Xuất hàng
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
            <div class="col-md-10" role="main">
                <div class="h5a-docs-section">
                    <div class="page-header">
                        <div class="row">
                            <div class="col-sm-6">
                                <h1>Hàng hóa</h1>
                            </div>
                            <div class="col-sm-6">
                                <div class="pull-right">                                    
                                    <div class="btn-group ">
                                        <button type="button" class="h5a-btn btn btn-default btn-sm">
                                            <i class="fa fa-chevron-left"></i>
                                        </button>                                    
                                        <button type="button" class="h5a-btn btn btn-default btn-sm">
                                            <i class="fa fa-chevron-right"></i>
                                        </button>
                                    </div>
                                    <div class="btn-group ">
                                        <button type="button" class="h5a-btn btn btn-default btn-sm">Import</button>
                                        <button type="button" class="h5a-btn btn btn-default btn-sm">Export</button>
                                    </div>
                                    <!-- <button type="button" class="h5a-btn btn btn-default btn-sm">Quản lý tồn kho</button> -->
                                    <a href="<?php echo $this->url('hang_hoa/crud',array('action'=>'themSanPham'));?>" type="button" class="h5a-btn btn btn-primary btn-sm">Thêm mới</a>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="box">
                        <ul class="nav nav-tabs" role="tablist" id="myTab">
                            <li role="presentation" class="active">
                                <a href="#home" role="tab" data-toggle="tab">Tất cả</a>
                            </li>
                        </ul>
                        <div class="tab-content">
                            <div role="tabpanel" class="tab-pane active" id="home">
                                <div class="container">
                                    <div class="row bottom20">
                                        <div class="input-group has-feedback">
                                            <div class="input-group-btn">
                                                <button type="button" class="btn btn-default h5a-btn dropdown-toggle" data-toggle="dropdown">Lọc sản phẩm <span class="caret"></span></button>
                                                <ul class="dropdown-menu" role="menu">
                                                    <li><a href="#">Loại hàng</a></li>
                                                    <li><a href="#">Nhãn hàng</a></li>
                                                </ul>
                                            </div><!-- /btn-group -->
                                            <input type="text" class="form-control h5a-input"> 
                                            <i class="glyphicon glyphicon-search form-control-feedback"></i>
                                            <!-- <span class="input-group-btn hide">
                                                <button class="btn btn-default" type="button">Go!</button>
                                            </span> -->
                                        </div><!-- /input-group -->
                                    </div>
                                    <div class="row">
                                        <table id="dataTables-example" class="">
                                            <thead>
                                                <th><input type="checkbox"/></th>
                                                <th>Sản phẩm</th>
                                                <th>Tồn kho</th>
                                                <th>Loại</th>
                                                <th>Nhãn hàng</th>
                                            </thead>
                                            <tbody>                                       
                                                <tr>
                                                    <td><input type="checkbox"/></td>
                                                    <td><img src="img/brand.png" height="40"> <a href="sanPham.html">Giấy in Lucky 100g</a></td>
                                                    <td>254</td>
                                                    <td>Giấy in</td>
                                                    <td>Lucky</td>
                                                </tr>
                                            </tbody>
                                        </table>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
</div>