<?php
    $this->headTitle('Nhà sách');
    phpinfo();
?>
<div class="h5a-container">
    <h1>
        <span class="breadcrumb">
            <a href="<?php echo $this->url('hang_hoa/crud',array('action'=>'index'));?>">/ Kho</a>
             / Tổng hợp /
        </span> TỔNG HỢP
    </h1>
    <div class="row">
        <div class="col-sm-3">
            <div class="box">
                <div class="icon blue">
                    <i class="fa fa-user"></i>
                </div>
                <div class="content-right">
                    <div class="title blue">Doanh thu</div>
                    <div class="value">594</div>
                    <div class="title blue">Lợi nhuận</div>
                    <div class="value">66780</div>
                    <div class="title blue">Khách hàng</div>
                    <div class="value">122</div>
                    <div class="title green">Sản phẩm</div>
                    <div class="value green">223*</div>
                    <div class="title red">Deleted</div>
                    <div class="value red">3</div><br>
                </div>
            </div>
        </div>
        <div class="col-sm-3">
            <div class="box">
                <div class="icon green"><i class="fa fa-edit"></i></div>
                <div class="content-right">
                    <div class="title black">Đơn hàng <a href="#">Tất cả »</a></div>
                    <div class="value">9564</div>
                    <div class="title black">Doanh thu <i>(+22.8%)</i></div>
                    <div class="value green">56.073.500 vnd</div>
                </div>
            </div>
        </div>
        <div class="col-sm-3">
            <div class="box">
                <div class="icon orange"><i class="fa fa-line-chart"></i></div>
                <div class="content-right">
                    <div class="title black">Thanh toán <a href="#">Tất cả »</a></div>
                    <div class="value">120</div>
                    <div class="title black">Lợi nhuận <i>(-13.4%)</i></div>
                    <div class="value red">5.670.000 vnd</div>
                </div>
            </div>
        </div>
        <div class="col-sm-3">
            <div class="box">
                <div class="icon red"><i class="fa fa-database"></i></div>
                <div class="content-right">
                    <div class="title black">Ghi công nợ <a href="#">Tất cả »</a></div> 
                    <!-- moi lan dat hang se co mot hoa don chua thanh toan, khi thanh toan thi gop cac hoa don thanh toan lai thanh phieu ghi no(no cu, no moi, tra) -->
                    <div class="value black">132</div>
                    <div class="title black">Công nợ  <i>(-43.2%)</i></div>
                    <div class="value red">12.500.000 vnd</div>
                </div>
            </div>
        </div>
        <div class="col-sm-3">
            <div class="box">
                <div class="icon blue"><i class="fa fa-globe"></i></div>
                <div class="content-right">
                    <div class="title blue">Khách hàng</div>
                    <div class="value">98347</div>
                    <div class="title black">Danh_Sach.xls</div>
                    <div class="value">
                        <a href="#"><i class="fa fa-download"></i> Tải về</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<!-- jQuery -->
<script src="<?php echo $this->basePath();?>/js/jquery.js"></script>
<!-- Bootstrap Core JavaScript -->
<script src="<?php echo $this->basePath();?>/js/bootstrap.min.js"></script>