<div class="row">
    <div class="col-md-2">
        <div class="h5a-sidebar affix">
            <span class="breadcrumb row">
                <a href="<?php echo $this->url('hang_hoa/crud',array('action'=>'index'));?>">/ Kho</a>
                <a href="<?php echo $this->url('hang_hoa/crud',array('action'=>'hang-hoa'));?>">/ Hàng hóa</a>
                 / Nhập hàng /
            </span>
            <ul class="nav h5a-sidenav nav-list accordion">                        
                <li>
                    <a href="<?php echo $this->url('hang_hoa/crud',array('action'=>'hang-hoa'));?>">
                        <i class="fa fa-cubes"></i> Danh sách hàng
                    </a>
                </li>
                <li>
                    <a href="<?php echo $this->url('hang_hoa/crud',array('action'=>'nhap-hang'));?>">
                        <i class="fa fa-download"></i> Nhập hàng
                    </a>
                </li>
                <li>
                    <a href="<?php echo $this->url('hang_hoa/crud',array('action'=>'xuat-hang'));?>">
                        <i class="fa fa-upload"></i> Xuất hàng
                    </a>
                </li>
            </ul>
        </div>
    </div>
    <div class="col-md-10" role="main">
        <div class="h5a-docs-section">
            <div class="page-header">
                <div class="row">
                    <div class="col-sm-6">
                        <h1>Lỗi nhập hàng</h1>
                    </div>
                    <div class="col-sm-6">                       
                        <div class="pull-right">
                            <div class="btn-group ">
                                <button id="btPrev" type="button" class="h5a-btn btn btn-default btn-sm">
                                    <i class="fa fa-chevron-left"></i>
                                </button>                                    
                                <button id="btNext" type="button" class="h5a-btn btn btn-default btn-sm">
                                    <i class="fa fa-chevron-right"></i>
                                </button>
                                <a href="<?php echo $this->url('hang_hoa/crud',array('action'=>'nhap-hang'));?>"><button type="button" class="h5a-btn btn btn-primary btn-sm">Trở về</button></a>&nbsp;
                            </div>                                
                        </div>
                    </div>
                </div>
                <?php
                    $flash=$this->flashMessenger();
                    $flash->setMessageOpenFormat('<div%s>
                     <button type="button" id="btFm" class="close" data-dismiss="alert" aria-hidden="true">
                         &times;
                     </button>
                     <ul><li>')
                     ->setMessageSeparatorString('</li><li>')
                     ->setMessageCloseString('</li></ul></div>');

                     $error=$flash->render('error',   array('alert', 'alert-dismissable', 'alert-danger'));
                     echo $error;

                     $info=$flash->render('info',    array('alert', 'alert-dismissable', 'alert-info'));
                     echo $info;

                     $default=$flash->render('default', array('alert', 'alert-dismissable', 'alert-warning'));
                     echo $default;

                     $success=$flash->render('success', array('alert', 'alert-dismissable', 'alert-success'));
                     echo $success;                     
                    if($error||$success||$info||$default)
                    {
                        echo '
                        <script type="text/javascript">
                            setTimeout(function(){
                                document.getElementById("btFm").click();
                            },5000);
                        </script>';                        
                    }
                ?>                
            </div>
                <div class="row">
                    <h3>DANH SÁCH CÁC MÃ SẢN PHẨM KHÔNG THỂ IMPORT</h3>
                    <table border="1" width="81%">
                        <thead>
                            <th>STT</th>
                            <th>Mã sản phẩm</th>
                            <th>Tên nhà cung cấp</th>
                            <th>Số lượng</th>
                            <th>giá</th>
                        </thead>
                        <tbody>
                            <?php
                            $i=0;
                            foreach ($danhSachLoi as $loi) {?>
                                <tr>
                                    <td><?php echo ++$i; ?></td>
                                    <td><?php echo $loi['maSanPham']; ?></td>
                                    <td><?php echo $loi['nhaCungCap']; ?></td>
                                    <td><?php echo $loi['soLuong']; ?></td>
                                    <td><?php echo $loi['gia']; ?></td>
                                </tr>           
                            <?php }?>
                        </tbody>
                    </table> 

                </div>
                <br>
                <div class="row">
                        
                </div>
            
        </div>                
    </div>
</div>

<?php
    echo $this->form()->closeTag();
?>   
    <!-- FormatNumber -->
    <script src="<?php echo $this->basePath();?>/js/formatnumber.js"></script>

    <!-- convernumbertostring -->
    <script src="<?php echo $this->basePath();?>/js/convernumbertostring.js"></script>

    <!-- jQuery -->
    <script src="<?php echo $this->basePath();?>/js/jquery.js"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="<?php echo $this->basePath();?>/js/bootstrap.min.js"></script>

    <!-- DataTables JavaScript -->
    <script src="<?php echo $this->basePath();?>/js/plugins/dataTables/jquery.dataTables.js"></script>

    <!-- Page-Level Demo Scripts - Tables - Use for reference -->
    <script>    
    $(document).ready(function() 
    {
        $('#dataTables-example').dataTable({
            "pagingType": "simple",
            "bPaginate": true,
            "bLengthChange": true,
            "bFilter": true,
            "bInfo": true,
            "bAutoWidth": true
        });
        $('#loaiGia').val(0);
        var i=0;
        
        $('#btnNhapHang').click(function(){            
            var idSanPham=$('#idSanPham').val();
            var maHang=$('#idMaHang').val();
            var tenHang=$('#tenHang').val();
            var soLuong=$('#soLuong').val(); 
            var giaNhap=$('#giaNhap').val();
            var donViTinh=$('#donViTinh').val();
            var idNhaCungCap=$('#idNhaCungCap').val();
            var nhaCungCap=$('#nhaCungCap').val();
            var loaiGia=$('#loaiGia').val();
            var giaBia=$('#giaBia').val();
            var chietKhau=$('#chiecKhau').val();

            if(loaiGia==1)
            {
                if(giaBia==0||giaBia==''||giaBia==null||
                   chietKhau==0||chietKhau==''||chietKhau==null)
                {
                    alert('Vui lòng điền đầy đủ thông tin');
                    return false;
                }
                var loiNhuan=(parseFloat(giaBia)*parseFloat(chietKhau))/100;   
                giaNhap=parseFloat(giaBia)-parseFloat(loiNhuan);

            }
            else
            {
                chietKhau=0;
                giaBia=0;
            }

            if(idSanPham==''||maHang==''||tenHang==''||donViTinh==''||soLuong==''||giaNhap==''||nhaCungCap==''||idNhaCungCap==''||idSanPham==null||maHang==null||tenHang==null||donViTinh==null||soLuong==null||giaNhap==null||nhaCungCap==null||idNhaCungCap==null)
            {
                alert('Thông tin không đầy đủ hoặc không chính xác');
                return false;
            }

            var soDong = $('#tbNhapHang > tbody > tr').length;            
            var template = '<tr class="price">'+
                '<td>'+tenHang+'</td>'+
                '<td>'+donViTinh+'</td>'+
                '<td>'+
                    '<input type="hidden" name="phieu-nhap&#x5B;ctPhieuNhaps&#x5D;&#x5B;__index__&#x5D;&#x5B;idSanPham&#x5D;&#x5B;idSanPham&#x5D;" value="'+idSanPham+'">'+'<span hidden="true" class="maSanPham">'+maHang+'</span>'+
                    '<input type="hidden" name="phieu-nhap&#x5B;ctPhieuNhaps&#x5D;&#x5B;__index__&#x5D;&#x5B;soLuong&#x5D;" value="'+soLuong+'">'+
                    '<span class="soLuong">'+addPeriod(soLuong)+'</span>'+
                '</td>'+
                '<td>'+
                    '<input type="hidden" name="phieu-nhap&#x5B;ctPhieuNhaps&#x5D;&#x5B;__index__&#x5D;&#x5B;giaNhap&#x5D;" value="'+giaNhap+'">'+
                    '<span class="giaNhap">'+addPeriod(giaNhap)+'</span>'+
                    '<input type="hidden" name="phieu-nhap&#x5B;ctPhieuNhaps&#x5D;&#x5B;__index__&#x5D;&#x5B;idSanPham&#x5D;&#x5B;loaiGia&#x5D;" value="'+loaiGia+'">'+
                    '<input type="hidden" name="phieu-nhap&#x5B;ctPhieuNhaps&#x5D;&#x5B;__index__&#x5D;&#x5B;idSanPham&#x5D;&#x5B;giaBia&#x5D;" value="'+giaBia+'">'+
                    '<input type="hidden" name="phieu-nhap&#x5B;ctPhieuNhaps&#x5D;&#x5B;__index__&#x5D;&#x5B;idSanPham&#x5D;&#x5B;chiecKhau&#x5D;" value="'+chietKhau+'">'+
                    
                '</td>'+
                '<td style="text-align:left;" class="an">'+
                    '<a class="btnHuy"><img src="<?php echo $this->basePath(); ?>/img/delete.png" width="30px" height="30px"></a>'+
                '</td>'+                
                '</tr>';

                $('input[name="phieu-nhap[idDoiTac][idDoiTac]"]').val(idNhaCungCap);
                $('input[name="phieu-nhap[idUserNv][userId]"]').val(1);

            template = template.replace(/__index__/g, soDong);
            $('#tbNhapHang tbody').append(template);
            return false;
        });

        //Hiển thị, chọn sản phẩm
        var xhr;
        var xhr1;    
        $('#idMaHang').keyup(function(){
            var maHang=$(this).val();            
            if(xhr && xhr.readyState != 4){
                xhr.abort(); //huy lenh ajax truoc do
            }
            if(maHang==''||maHang==null)
            {                
                $('#tenHang').val('');
            }

           xhr = $.ajax({
                url:'<?php echo $this->url('hang_hoa/crud', array('action'=>'search-san-pham')); ?>',
                type:'POST',
                dataType:'json',
                data:{
                    'maHang':maHang
                },

                success:function(data){                
                    $.each(data, function(key,val){
                        $('#ma-hang-search-result').empty(); //lam rong khung ket qua
                        $('#ma-vach-search-result').empty();

                        var pos = $('#idMaHang').position(); //lấy tọa độ của ô mã sản phẩm
                        $('#ma-hang-search-result').css({
                            position:'absolute',
                            top:pos.top + 35,
                            left:pos.left+177,
                            'z-index': 100 // đặt search-result lên layout ngoài nhất
                        });

                        $.each(data, function(key, val){
                            $('#ma-hang-search-result').append('<div class="list-group-item"><span class="hide">'+val.idSanPham+'</span><span>'+val.maHang+'</span><span class="hide">'+val.tenSanPham+'</span><span class="hide">'+val.giaNhap+'</span><span class="hide">'+val.donViTinh+'</span><span class="hide">'+val.loaiGia+'</span><span class="hide">'+val.giaBia+'</span><span class="hide">'+val.chietKhau+'</span><span class="hide">'+val.maVach+'</span></div>');
                            // thêm một dòng vào search result, mỗi một dòng là 1 sản phẩm
                        })
                    });
                }
            });
            return false;
        });

        $('#ma-hang-search-result').on('click', '.list-group-item', function(){
            var id = $(this).find('span:eq(0)').text();
            var ma = $(this).find('span:eq(1)').text();
            var ten = $(this).find('span:eq(2)').text();            
            var giaNhap = $(this).find('span:eq(3)').text();
            var donViTinh = $(this).find('span:eq(4)').text();   
            var loaiGia=$(this).find('span:eq(5)').text();   
            var giaBia=$(this).find('span:eq(6)').text();   
            var chietKhau=$(this).find('span:eq(7)').text(); 
            var maVach=$(this).find('span:eq(8)').text(); 

            $('#idSanPham').val(id);
            $('#idMaHang').val(ma);
            $('#maVach').val(maVach);
            $('#tenHang').val(ten);
            $('#giaNhap').val(giaNhap);
            $('#donViTinh').val(donViTinh);
            $('#loaiGia').val(loaiGia);
            $('#giaBia').val(giaBia);
            $('#chiecKhau').val(chietKhau);
            if(parseInt(loaiGia)==1)
            {
                $("#loaiGia").prop("checked", true);
                $("#loaiGia").val(1);
                kiemTracheckbox();
            }
            else
            {
                $("#loaiGia").prop("checked", false);
                $("#loaiGia").val(0);
                kiemTracheckbox();
            }
            
            $('#ma-vach-search-result').empty();
            $('#ma-hang-search-result').empty();
        });



// Khi gõ vào mã vạch
        var xhrMaVach;
        $('#maVach').keyup(function(){
            var maVach=$(this).val();
            if(maVach){
                if(xhrMaVach && xhrMaVach.readyState != 4){
                    xhrMaVach.abort(); //huy lenh ajax truoc do
                }
                xhrMaVach = $.ajax({
                    url:'<?php echo $this->url('hang_hoa/crud', array('action'=>'search-san-pham-theo-ma-vach')); ?>',
                    type:'POST',
                    dataType:'json',
                    data:{
                        'maVach':maVach
                    },
                    success:function(data){                
                        $.each(data, function(key,val){
                            $('#ma-vach-search-result').empty(); //lam rong khung ket qua
                            $('#ma-hang-search-result').empty();

                            var pos = $('#maVach').position(); //lấy tọa độ của ô mã sản phẩm
                            $('#ma-vach-search-result').css({
                                position:'absolute',
                                top:pos.top + 35,
                                left:pos.left,
                                'z-index': 100 // đặt search-result lên layout ngoài nhất
                            });

                            $.each(data, function(key, val){
                                $('#ma-vach-search-result').append('<div class="list-group-item"><span class="hide">'+val.idSanPham+'</span><span>'+val.maHang+'</span><span class="hide">'+val.tenSanPham+'</span><span class="hide">'+val.giaNhap+'</span><span class="hide">'+val.donViTinh+'</span><span class="hide">'+val.loaiGia+'</span><span class="hide">'+val.giaBia+'</span><span class="hide">'+val.chietKhau+'</span><span class="hide">'+val.maVach+'</span><span style="margin-right:0px;">&nbsp;&nbsp;('+val.maVach+')</span></div>');
                                // thêm một dòng vào search result, mỗi một dòng là 1 sản phẩm
                            });
                        });
                    }
                });

            }
            else{//ngược lại mã vạch == null
                $('#ma-vach-search-result').empty();
            }
        });
        
        $('#ma-vach-search-result').on('click', '.list-group-item', function(){
            var id = $(this).find('span:eq(0)').text();
            var ma = $(this).find('span:eq(1)').text();
            var ten = $(this).find('span:eq(2)').text();            
            var giaNhap = $(this).find('span:eq(3)').text();
            var donViTinh = $(this).find('span:eq(4)').text();   
            var loaiGia=$(this).find('span:eq(5)').text();   
            var giaBia=$(this).find('span:eq(6)').text();   
            var chietKhau=$(this).find('span:eq(7)').text(); 
            var maVach=$(this).find('span:eq(8)').text(); 

            $('#idSanPham').val(id);
            $('#idMaHang').val(ma);
            $('#maVach').val(maVach);
            $('#tenHang').val(ten);
            $('#giaNhap').val(giaNhap);
            $('#donViTinh').val(donViTinh);
            $('#loaiGia').val(loaiGia);
            $('#giaBia').val(giaBia);
            $('#chiecKhau').val(chietKhau);
            if(parseInt(loaiGia)==1)
            {
                $("#loaiGia").prop("checked", true);
                $("#loaiGia").val(1);
                kiemTracheckbox();
            }
            else
            {
                $("#loaiGia").prop("checked", false);
                $("#loaiGia").val(0);
                kiemTracheckbox();
            }
            
            $('#ma-vach-search-result').empty();
            $('#ma-hang-search-result').empty();
        });


    //Hiển thị, chọn nhà cung cấp
        $('#nhaCungCap').keyup(function()
        {

            if($('#idNhaCungCap').val()=='')
            {
                $('#nha-cung-cap-search-result').empty();
            }
            var nhaCungCap=$(this).val();            
            if(xhr1 && xhr1.readyState != 4){
                xhr1.abort(); //huy lenh ajax truoc do
            }

            xhr1 = $.ajax({
                url:'<?php echo $this->url('hang_hoa/crud', array('action'=>'search-nha-cung-cap')); ?>',
                type:'POST',
                dataType:'json',
                data:{
                    'nhaCungCap':nhaCungCap
                },

                success:function(data){  
                             
                    $.each(data, function(key,val){
                        $('#nha-cung-cap-search-result').empty(); //lam rong khung ket qua

                        var pos = $('#nhaCungCap').position(); //lấy tọa độ của ô mã sản phẩm
                        $('#nha-cung-cap-search-result').css({
                            position:'absolute',
                            top:pos.top + 145,
                            left:pos.left+182,
                            'z-index': 100 // đặt search-result lên layout ngoài nhất
                        });

                        $.each(data, function(key, val){
                            $('#nha-cung-cap-search-result').append('<div class="list-group-item"><span class="hide">'+val.idDoiTac+'</span><span>'+val.hoTen+'</span><span class="hide">'+val.diaChi+'</span></div>');
                        })
                    });
                }
            });            
            return false;
        });

        $('#nha-cung-cap-search-result').on('click', '.list-group-item', function()
            {
                $('#tbNhapHang > tbody > tr').remove();
                var idDoiTac = $(this).find('span:eq(0)').text();
                var hoTen = $(this).find('span:eq(1)').text();
                var diaChi = $(this).find('span:eq(2)').text();
                $('#idNhaCungCap').val(idDoiTac); 
                $('#nhaCungCap').val(hoTen);      
                $('#tenNCC').text(hoTen);     
                $('#diaChiNCC').text(diaChi);      

                $('#nha-cung-cap-search-result').empty();
            });    
    //./Hiển thị, chọn nhà cung cấp

    });

    Import=function()
    {
        document.getElementById('file').click();
        return false;     
    }
    hamSubmit=function(){
        var valueFile=document.getElementById('file').value;        
        if(valueFile)
        {            
            document.frmImport.submit();
            return true;           
        }
    }

    $(document).ready(function(){
      $(document).on('click', '.btnHuy', function(){        
        $(this).closest('tr').remove();        
        return false;
      });
    });    

    </script>

    <script>
        luuNhapHangFunction=function()
        {
            var soDong = $('#tbNhapHang > tbody > tr').length; 
            if(soDong==0)
            {
                alert('Không có sản phẩm trong danh sách nhập!');
                return false;
            }
            else
            {
                var soLuong=new Array();
                var donGia=new Array();                
                var maSanPham=new Array();
                var thanhTien=new Array();
                var i=1;
                var j=1;
                var k=1;
                var sL=0;
                var gN=0;
                var maSP='';
                var tongTien=0;

                var sD = $('#tbSanPham > tbody > tr').length;
                var temp = '<tr class="price">';                
                $("#tbNhapHang tbody tr").each(function()
                {
                    var timSoLuong=$(this).find(".soLuong");
                    var timGiaNhap=$(this).find(".giaNhap");
                    var timMaSanPham=$(this).find(".maSanPham");
                    timSoLuong.each(function(){                        
                        sL=parseInt($(this).html().replace(/ /g,''));                        
                    });
                    timGiaNhap.each(function(){
                        gN=parseInt($(this).html().replace(/ /g,''));
                    });
                    timMaSanPham.each(function(){                        
                        maSP=$(this).html();                        
                    });
                    //alert(sL+' '+gN);
                    soLuong[k]=sL;
                    donGia[k]=gN;
                    thanhTien[k]=sL*gN;
                    maSanPham[k]=maSP;
                    //alert(maSanPham[k].toString());
                    k++;
                });
                //------------------------------------------------
                $("#tbNhapHang tbody tr td").each(function()
                {
                    var t=$(this).html();
                    var c= parseInt(i%5);
                    if(c==1)
                    {
                        temp = temp +'<td style="text-align: center;">'+j+'</td>';
                    }                   
                    if(c!=0)                    
                    {
                        if(c==2||c==3||c==4)
                        {                            
                             if(c==2)
                             {
                                temp= temp+
                                '<td style="text-align: right;">'+$(this).html()+'</td>';
                             }
                             if(c==3)
                             {
                                temp= temp+
                                '<td style="text-align: right;">'+formatNumber(soLuong[j])+'</td>';
                             }
                             if(c==4)
                             {
                                temp= temp+
                                '<td style="text-align: right;">'+formatNumber(donGia[j])+'</td>';
                             }                             
                        }
                        else
                        {
                            temp= temp+
                             '<td>'+$(this).html()+'</td>';
                        }

                        if(c==1)
                        {
                            temp=temp+
                            '<td style="text-align: right;">'+maSanPham[j]+'</td>';
                        }
                        if(c==2)
                        {
                            temp=temp+'<td></td>';
                        }                            
                        if(c==4)
                        {
                            temp=temp+'<td style="text-align: right;"><span class="thanhTien">'+formatNumber(thanhTien[j])+'</span</td>';
                            tongTien=tongTien+parseInt(thanhTien[j]);
                        }
                    }
                    if(c==0)
                    {
                        temp=temp+'</tr>';                        
                        j++;                        
                    }                    
                    i++;
                });

                temp=temp+'<tr><td></td><td style="text-align: center;">TỔNG</td><td></td><td></td><td></td><td></td><td></td><td style="text-align: right;">'+formatNumber(tongTien)+'</td></tr>';
                //------------------------------------------------
                temp = temp.replace(/__index__/g, sD);                    
                $('#tbSanPham tbody').append(temp);
                var soTienBangChu=docso(tongTien);                                
                $('#tongSoTien').text(soTienBangChu);
                var nguoiGiaoHang=$('#nhaCungCap').val();
                $('.nguoiGiaoHang').text(nguoiGiaoHang);
                
                window.print();
                document.getElementById('formNhapHang').submit();
                return true;                
            }     
        }           

        function addPeriod(nStr){
            nStr += '';
            var x = nStr.split(' ');
            var x1 = x[0];
            var x2 = x.length > 1 ? ' ' + x[1] : '';
            var rgx = /(\d+)(\d{3})/;
            while (rgx.test(x1)) {
                x1 = x1.replace(rgx, '$1' + ' ' + '$2');
            }
            return x1 + x2;
        }    

    </script>