<?php
     $this->headTitle('Nhập hàng');
     $form->setAttribute('action', $this->url('hang_hoa/crud', array('action' => 'nhapHang')));
     $form->setAttribute('role','form');
     $form->setAttribute('class','form-horizontal');
     $form->prepare();
     echo $this->form()->openTag($form);
     echo $this->formHidden($form->get('idSanPham'));
?>
<div class="container">
        <div class="row">
            <div class="col-md-2">
                <div class="h5a-sidebar affix">
                    <span class="breadcrumb row">
                        <a href="<?php echo $this->url('hang_hoa/crud',array('action'=>'index'));?>">/ Kho</a>
                        <a href="<?php echo $this->url('hang_hoa/crud',array('action'=>'hangHoa'));?>">/ Hàng hóa</a>
                         / Nhập hàng /
                    </span>
                    <ul class="nav h5a-sidenav nav-list accordion">                        
                        <li>
                            <a href="<?php echo $this->url('hang_hoa/crud',array('action'=>'hangHoa'));?>">
                                <i class="fa fa-cubes"></i> Danh sách hàng
                            </a>
                        </li>
                        <li>
                            <a href="<?php echo $this->url('hang_hoa/crud',array('action'=>'nhapHang'));?>">
                                <i class="fa fa-download"></i> Nhập hàng
                            </a>
                        </li>
                        <li>
                            <a href="<?php echo $this->url('hang_hoa/crud',array('action'=>'xuatHang'));?>">
                                <i class="fa fa-upload"></i> Xuất hàng
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
            <div class="col-md-10" role="main">
                <div class="h5a-docs-section">
                    <div class="page-header">
                        <div class="row">
                            <div class="col-sm-6">
                                <h1>Nhập hàng</h1>
                            </div>
                            <div class="col-sm-6">                                
                            </div>
                        </div>
                    </div>                    
                        <div class="col-sm-6">
                            <div class="form-group">
                                <label class="col-sm-4 right" for="form-field-1">Mã hàng</label>
                                <div class="col-sm-7">                                    
                                    <?php                                    
                                        $maSanPham=$form->get('maHang');
                                        echo $this->formElement($maSanPham);        
                                    ?>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-sm-4 right" for="form-field-2">Tên hàng</label>
                                <div class="col-sm-7">                                    
                                    <?php                                    
                                        $tenSanPham=$form->get('tenHang');         
                                        echo $this->formElement($tenSanPham);
                                    ?>
                                </div>
                            </div>
                        </div>
                        <div class="col-sm-6">
                            <div class="form-group">
                                <label class="col-sm-4 right" for="form-field-3">Số lượng</label>
                                <div class="col-sm-7">                                    
                                    <?php                                    
                                        $soLuong=$form->get('soLuong');
                                        echo $this->formElement($soLuong);
                                    ?>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-sm-4 right" for="form-field-4">Giá nhập</label>
                                <div class="col-sm-7">                                    
                                    <?php                                    
                                        $giaNhap=$form->get('giaNhap');
                                        echo $this->formElement($giaNhap);
                                    ?>
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="col-sm-10 col-sm-offset-1">
                                    <button id="btnNhapHang" class="btn h5a-btn btn-primary full">Nhập hàng</button>
                                </div>
                            </div>
                        </div>
                </div>                
            </div>
        </div>
</div>

<div class="container h5a-container">
        <div class="row">
            <div class="col-md-2">
            </div>
            <div class="col-md-10">
                <h1>Danh sách nhập</h1>
                <div class="box">
                    <table class="invoice pricelist bottom20">
                        <thead>
                            <th>Sản phẩm</th>
                            <th>Đơn vị tính</th>
                            <th>Số lượng</th>
                            <th>Giá nhập</th>
                        </thead>
                        <tbody>
                            <tr class="price">
                                <td>Giấy in Lucky 100g</td>
                                <td>Thùng</td>
                                <td>125</td>
                                <td>70.000</td>
                            </tr>                            
                        </tbody>
                    </table>
                </div>
                <div class="page-footer">
                    <div class="row bottom20">
                        <div class="col-sm-6 col-sm-offset-6">
                            <div class="col-sm-10 col-sm-offset-1"><!-- class="pull-right" -->
                                <button type="submit" class="btn h5a-btn btn-primary full">Lưu</button>
                            </div>
                        </div>
                    </div>
                </div> 
            </div>
        </div>
</div>
<?php
    echo $this->form()->closeTag();
?>
    <!-- jQuery -->
    <script src="<?php echo $this->basePath();?>/js/jquery.js"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="<?php echo $this->basePath();?>/js/bootstrap.min.js"></script>

    <!-- DataTables JavaScript -->
    <script src="<?php echo $this->basePath();?>/js/plugins/dataTables/jquery.dataTables.js"></script>

    <!-- Page-Level Demo Scripts - Tables - Use for reference -->
    <script>
    $(document).ready(function() {
        $('#dataTables-example').dataTable({
            "pagingType": "simple",
            "bPaginate": true,
            "bLengthChange": true,
            "bFilter": true,
            "bInfo": true,
            "bAutoWidth": true
        });
    });

    $('#btnNhapHang').click(function(){
        
    });
    </script>