<?php
     $this->headTitle('Nhập hàng');
     $form->setAttribute('action', $this->url('hang_hoa/crud', array('action' => 'nhapHang')));
     $form->setAttribute('role','form');
     $form->setAttribute('class','form-horizontal');
     $form->prepare();
     echo $this->form()->openTag($form);
     echo $this->formHidden($form->get('idSanPham'));
     echo $this->formHidden($form->get('donViTinh'));
     echo $this->formHidden($form->get('idNhaCungCap'));
?>
<style type="text/css">
    #nha-cung-cap-search-result{ cursor:pointer;}
    #ma-hang-search-result{ cursor:pointer;}
</style>
<div class="container">
        <div class="row">
            <div class="col-md-2">
                <div class="h5a-sidebar affix">
                    <span class="breadcrumb row">
                        <a href="<?php echo $this->url('hang_hoa/crud',array('action'=>'index'));?>">/ Kho</a>
                        <a href="<?php echo $this->url('hang_hoa/crud',array('action'=>'hangHoa'));?>">/ Hàng hóa</a>
                         / Nhập hàng /
                    </span>
                    <ul class="nav h5a-sidenav nav-list accordion">                        
                        <li>
                            <a href="<?php echo $this->url('hang_hoa/crud',array('action'=>'hangHoa'));?>">
                                <i class="fa fa-cubes"></i> Danh sách hàng
                            </a>
                        </li>
                        <li>
                            <a href="<?php echo $this->url('hang_hoa/crud',array('action'=>'nhapHang'));?>">
                                <i class="fa fa-download"></i> Nhập hàng
                            </a>
                        </li>
                        <li>
                            <a href="<?php echo $this->url('hang_hoa/crud',array('action'=>'xuatHang'));?>">
                                <i class="fa fa-upload"></i> Xuất hàng
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
            <div class="col-md-10" role="main">
                <div class="h5a-docs-section">
                    <div class="page-header">
                        <div class="row">
                            <div class="col-sm-6">
                                <h1>Nhập hàng</h1>
                            </div>
                            <div class="col-sm-6">                                
                            </div>
                        </div>
                    </div>                    
                        <div class="col-sm-6">
                            <div class="form-group">
                                <label class="col-sm-4 right" for="form-field-1">Mã hàng</label>
                                <div class="col-sm-7">                                    
                                    <?php                                    
                                        $maSanPham=$form->get('maHang');
                                        echo $this->formElement($maSanPham);        
                                    ?>
                                </div>
                                <div id="ma-hang-search-result"></div>
                            </div>
                            <div class="form-group">
                                <label class="col-sm-4 right" for="form-field-2">Tên hàng</label>
                                <div class="col-sm-7">                                    
                                    <?php                                    
                                        $tenSanPham=$form->get('tenHang');         
                                        echo $this->formElement($tenSanPham);
                                    ?>
                                </div>
                            </div>

                            <div class="form-group">
                                <label class="col-sm-4 right" for="form-field-1">Nhà cung cấp</label>
                                <div class="col-sm-7">
                                    <?php                                        
                                        $nhaCungCap=$form->get('nhaCungCap');       
                                        echo $this->formElement($nhaCungCap);
                                    ?>
                                </div>
                                <div id="nha-cung-cap-search-result"></div>
                            </div>
                        </div>
                        <div class="col-sm-6">
                            <div class="form-group">
                                <label class="col-sm-4 right" for="form-field-3">Số lượng</label>
                                <div class="col-sm-7">                                    
                                    <?php                                    
                                        $soLuong=$form->get('soLuong');
                                        echo $this->formElement($soLuong);
                                    ?>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-sm-4 right" for="form-field-4">Giá nhập</label>
                                <div class="col-sm-7">                                    
                                    <?php                                    
                                        $giaNhap=$form->get('giaNhap');
                                        echo $this->formElement($giaNhap);
                                    ?>
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="col-sm-10 col-sm-offset-1">
                                    <button type="button" id="btnNhapHang" class="btn h5a-btn btn-primary full">Nhập hàng</button>
                                </div>
                            </div>
                        </div>
                </div>                
            </div>
        </div>
</div>

<div class="container h5a-container">
        <div class="row">
            <div class="col-md-2">
            </div>
            <div class="col-md-10">
                <h1>Danh sách nhập</h1>
                <div class="box">
                    <table id="tbNhapHang" class="invoice pricelist bottom20">
                        <thead>
                            <th>Sản phẩm</th>
                            <th>Đơn vị tính</th>
                            <th>Số lượng</th>
                            <th>Giá nhập</th>
                        </thead>
                        <tbody>
                        </tbody>
                    </table>
                </div>
                <div class="page-footer">
                    <div class="row bottom20">
                        <div class="col-sm-6 col-sm-offset-6">
                            <div class="col-sm-10 col-sm-offset-1"><!-- class="pull-right" -->
                                <button type="submit" class="btn h5a-btn btn-primary full">Lưu</button>
                            </div>
                        </div>
                    </div>
                </div> 
            </div>
        </div>
</div>
<?php
    echo $this->form()->closeTag();
?>
    <!-- jQuery -->
    <script src="<?php echo $this->basePath();?>/js/jquery.js"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="<?php echo $this->basePath();?>/js/bootstrap.min.js"></script>

    <!-- DataTables JavaScript -->
    <script src="<?php echo $this->basePath();?>/js/plugins/dataTables/jquery.dataTables.js"></script>

    <!-- Page-Level Demo Scripts - Tables - Use for reference -->
    <script>
    $(document).ready(function() {
        $('#dataTables-example').dataTable({
            "pagingType": "simple",
            "bPaginate": true,
            "bLengthChange": true,
            "bFilter": true,
            "bInfo": true,
            "bAutoWidth": true
        });
        $('#btnNhapHang').click(function(){            
            var idSanPham=$('#idSanPham').val();
            var maHang=$('#idMaHang').val();
            var tenHang=$('#tenHang').val();
            var soLuong=$('#soLuong').val(); 
            var giaNhap=$('#giaNhap').val();
            var donViTinh=$('#donViTinh').val();
            alert(idSanPham+' '+maHang+' '+tenHang+' '+soLuong+' '+giaNhap+' '+donViTinh);

            var soDong = $('#tbNhapHang > tbody > tr').length;
            var template = '<tr class="price">'+
                '<td>'+tenHang+'</td>'+
                '<td>'+donViTinh+'</td>'+
                '<td>'+
                    '<input type="hidden" name="phieu-nhap&#x5B;ctPhieuNhap&#x5D;&#x5B;__index__&#x5D;&#x5B;idSanPham&#x5D;&#x5B;idSanPham&#x5D;" value="'+idSanPham+'">'+
                    '<input type="hidden" name="phieu-nhap&#x5B;ctPhieuNhap&#x5D;&#x5B;__index__&#x5D;&#x5B;soLuong&#x5D;" value="'+soLuong+'">'+
                    '<span>'+soLuong+'</span>'+
                '</td>'+
                '<td>'+
                    '<input type="hidden" name="phieu-nhap&#x5B;ctPhieuNhap&#x5D;&#x5B;__index__&#x5D;&#x5B;gia&#x5D;" value="'+giaNhap+'">'+
                    '<span>'+giaNhap+'</span>'+
                '</td>'+
                '</tr>';

                $('input[name="phieu-nhap[idDoiTac][idDoiTac]"]').val(idKhachhang);


            template = template.replace(/__index__/g, soDong);
            $('#tbNhapHang tbody').append(template);

            return false;
        });

        var xhr;
        var xhr1;
    //Hiển thị, chọn sản phẩm
        $('#idMaHang').keyup(function(){            
            var maHang=$(this).val();            
            if(xhr && xhr.readyState != 4){
                xhr.abort(); //huy lenh ajax truoc do
            }

           xhr = $.ajax({
                url:'<?php echo $this->url('hang_hoa/crud', array('action'=>'searchSanPham')); ?>',
                type:'POST',
                dataType:'json',
                data:{
                    'maHang':maHang
                },

                success:function(data){                
                    $.each(data, function(key,val){
                        $('#ma-hang-search-result').empty(); //lam rong khung ket qua

                        var pos = $('#idMaHang').position(); //lấy tọa độ của ô mã sản phẩm
                        $('#ma-hang-search-result').css({
                            position:'absolute',
                            top:pos.top + 35,
                            left:pos.left+177,
                            'z-index': 100 // đặt search-result lên layout ngoài nhất
                        });

                        $.each(data, function(key, val){
                            $('#ma-hang-search-result').append('<div class="list-group-item"><span class="hide">'+val.idSanPham+'</span><span>'+val.maHang+'</span><span class="hide">'+val.tenSanPham+'</span><span class="hide">'+val.giaNhap+'</span><span class="hide">'+val.donViTinh+'</span></div>');
                            // thêm một dòng vào search result, mỗi một dòng là 1 sản phẩm
                        })
                    });
                }
            });
            return false;
        });

        $('#ma-hang-search-result').on('click', '.list-group-item', function(){
            var id = $(this).find('span:eq(0)').text();
            var ma = $(this).find('span:eq(1)').text();
            var ten = $(this).find('span:eq(2)').text();            
            var giaNhap = $(this).find('span:eq(3)').text();
            var donViTinh = $(this).find('span:eq(4)').text();
            alert(ma);
            $('#idSanPham').val(id);
            $('#idMaHang').val(ma);
            $('#tenHang').val(ten);
            $('#giaNhap').val(giaNhap);
            $('#donViTinh').val(donViTinh);

            $('#ma-hang-search-result').empty();
        });
    //./Hiển thị, chọn sản phẩm

    //Hiển thị, chọn nhà cung cấp
        $('#nhaCungCap').keyup(function()
        {
            var nhaCungCap=$(this).val();            
            if(xhr1 && xhr1.readyState != 4){
                xhr1.abort(); //huy lenh ajax truoc do
            }

            xhr1 = $.ajax({
                url:'<?php echo $this->url('hang_hoa/crud', array('action'=>'searchNhaCungCap')); ?>',
                type:'POST',
                dataType:'json',
                data:{
                    'nhaCungCap':nhaCungCap
                },

                success:function(data){  
                             
                    $.each(data, function(key,val){
                        $('#nha-cung-cap-search-result').empty(); //lam rong khung ket qua

                        var pos = $('#nhaCungCap').position(); //lấy tọa độ của ô mã sản phẩm
                        $('#nha-cung-cap-search-result').css({
                            position:'absolute',
                            top:pos.top + 109,
                            left:pos.left+177,
                            'z-index': 100 // đặt search-result lên layout ngoài nhất
                        });

                        $.each(data, function(key, val){
                            $('#nha-cung-cap-search-result').append('<div class="list-group-item"><span class="hide">'+val.idDoiTac+'</span><span>'+val.hoTen+'</span></div>');
                        })
                    });
                }
            });            
            return false;
        });

        $('#nha-cung-cap-search-result').on('click', '.list-group-item', function(){
            var idDoiTac = $(this).find('span:eq(0)').text();
            var hoTen = $(this).find('span:eq(1)').text();
            $('#idNhaCungCap').val(idDoiTac); 
            $('#nhaCungCap').val(hoTen);            

            $('#nha-cung-cap-search-result').empty();
        });
    //./Hiển thị, chọn nhà cung cấp

    });
    </script>