<style type="text/css">
    table{width: 790px; font-size: 13px;}
    .tb{width: 95%;}
    .td{width: 85px;}
    table td{padding: 5px;}
</style>
<div class="row">
    <h3>Test</h3>
</div>
<table border="0">
    <tr style="text-align: -moz-center">
        <td>
            <table border="0" class="tb">
                <tr>
                    <td style="width:65%"><!-- <td style="width:515px"> -->
                        <b>
                            CTY CP SÁCH &amp; TB TRƯỜNG HỌC TRÀ VINH</br>
                            3A Trưng Nữ Vương Phường 1 TP.Trà Vinh</br>
                            Mã số thuế: 2100 290 521
                        </b>
                    </td>
                    <td style="text-align:center">
                        <b>Mẫ số: 01 - TT</b></br>
                        (Ban hành theo QĐ số: 15/2006/QĐ-BTC ngày 20/3/2006 của Bộ trưởng BTC)
                    </td>            
                </tr>
            </table>

            <table border="0" style="width:65%; margin-left:280px"  class="tb">
                <tr>
                    <td style="width:50%; padding-left:30px; font-size:16px; font-weight:bold">PHIẾU XUẤT KHO</td>
                    <td></td>
                </tr>
                <tr>
                    <td>Ngày  tháng  năm </td>
                    <td>Nợ: </td>
                </tr>
                <tr>
                    <td>Số: </td>
                    <td>Có: </td>
                </tr>
            </table>

            <table border="0"  class="tb">
                <tr>
                    <td colspan="4">
                        - Họ và tên người giao:...............................................................................................................................................
                    </td>
                </tr>
                <tr>
                    <td style="width:200px">
                        - Theo.........................
                    </td>
                    <td style="width:130px">
                        số............................
                    </td>
                    <td style="width:320px">
                        ngày........tháng........năm 20....
                    </td>
                    <td>
                        của...........................................
                    </td>
                </tr>
                <tr>
                    <td colspan="2">                        
                        Nhập tại kho:....................................................
                    </td>                    
                    <td colspan="2">
                        Địa điểm......................................................................................
                    </td>
                </tr>
                <tr><td></td></tr>
            </table>

            <table border="1">
                <tr style="text-align:center">
                    <td rowspan="2" style="width:45px">STT</td>
                    <td rowspan="2">Tên, nhãn hiệu quy cách, phẩm chất vật tư, dụng cụ sản phẩm, hàng hóa</td>
                    <td rowspan="2" class="td">Mã số</td>
                    <td rowspan="2" class="td">Đơn vị tính</td>
                    <td colspan="2" style="width:150px">Số lượng</td>
                    <td rowspan="2" class="td">Đơn giá</td>
                    <td rowspan="2" class="td">Thành tiền</td>
                </tr>
                <tr style="text-align:center">
                    <td>Theo chứng từ</td>
                    <td>Thực nhập</td>
                </tr>
                <tr style="text-align:center">
                    <td>A</td>
                    <td>B</td>
                    <td>C</td>
                    <td>D</td>
                    <td>1</td>
                    <td>2</td>
                    <td>3</td>
                    <td>4</td>
                </tr>
                <tr>
                    <td></td>
                    <td><b>Cộng</b></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                </tr>
            </table>
        </td>
    </tr>
    <tr>
        <td style="padding-left:20px">- Tổng số tiền (viết bằng chữ): </td>        
    </tr>
    <tr>
        <td style="padding-left:20px">- Số chứng từ gốc kèm theo: </td>
    </tr>
    <tr style="text-align: -moz-center">
        <td>
            <table border="0" class="tb">
                <tr>
                    <td colspan="4" style="text-align:right">Ngày tháng năm</td>
                </tr>
                <tr style="text-align: center;">
                    <td>
                        Người lập phiếu</br>(Ký, họ tên)
                    </td>
                    <td>
                        Người giao hàng</br>(Ký, họ tên)
                    </td>
                    <td>
                        Thủ kho</br>(Ký, họ tên)
                    </td>
                    <td>
                        Kế toán trưởng<br>(Hoặc bộ phận có nhu cầu nhập)</br>(Ký, họ tên)
                    </td>
                </tr>
                <tr>
                    <td style="height:100px"></td>
                </tr>
            </table>
        </td>
    </tr>
</table>