<head>
    <meta charset="UTF-8">    
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>Nhập Hàng</title>
</head>
<div class="container">
        <div class="row">
            <div class="col-md-2">
                <div class="h5a-sidebar affix">
                    <span class="breadcrumb row">
                        <a href="index.html">/ Kho</a>
                        <a href="<?php echo $this->url('hang_hoa');?>">/ Hàng hóa</a>
                         / Nhập hàng /
                    </span>
                    <ul class="nav h5a-sidenav nav-list accordion">
                        <!-- <li class="sidenav-messages dark">
                            <span class="pull-right"><i class="fa fa-times"></i></span>
                            <h4 class="underline red"><i class="fa fa-exclamation-triangle"></i> Warning!</h4>
                            <p class="black">This can be a perfect place for <strong>important communication</strong>, a response after a form has been sent...or anything else (like buttons, small forms, social sharing widget, etc.)<br></p>
                        </li> -->
                        <li>
                            <a href="<?php echo $this->url('hang_hoa');?>">
                                <i class="fa fa-cubes"></i> Danh sách hàng
                            </a>
                        </li>
                        <li>
                            <a href="<?php echo $this->url('hang_hoa/crud',array('action'=>'nhapHang'));?>">
                                <i class="fa fa-download"></i> Nhập hàng
                            </a>
                        </li>
                        <li>
                            <a href="<?php echo $this->url('hang_hoa/crud',array('action'=>'xuatHang'));?>">
                                <i class="fa fa-upload"></i> Xuất hàng
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
            <div class="col-md-10" role="main">
                <div class="h5a-docs-section">
                    <div class="page-header">
                        <div class="row">
                            <div class="col-sm-6">
                                <h1>Nhập hàng</h1>
                            </div>
                            <!-- <div class="col-sm-6">
                                <div class="pull-right">
                                    <div class="btn-group ">
                                        <button type="button" class="h5a-btn btn btn-default btn-sm">
                                            <i class="fa fa-chevron-left"></i>
                                        </button>                                    
                                        <button type="button" class="h5a-btn btn btn-default btn-sm">
                                            <i class="fa fa-chevron-right"></i>
                                        </button>
                                    </div>
                                    <div class="btn-group ">
                                        <button type="button" class="h5a-btn btn btn-default btn-sm">Import</button>
                                        <button type="button" class="h5a-btn btn btn-default btn-sm">Export</button>
                                    </div>
                                </div>
                            </div> -->
                        </div>
                    </div>
                    <form class="form-horizontal" role="form">
                        <div class="col-sm-6">
                            <div class="form-group">
                                <label class="col-sm-4 right" for="form-field-1">Mã hàng</label>
                                <div class="col-sm-7">
                                    <input type="text" id="form-field-1" placeholder="Mã hàng" class="h5a-input form-control input-sm">
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-sm-4 right" for="form-field-2">Tên hàng</label>
                                <div class="col-sm-7">
                                    <input type="text" id="form-field-2" placeholder="Tên hàng" class="h5a-input form-control input-sm">
                                </div>
                            </div>
                        </div>
                        <div class="col-sm-6">
                            <div class="form-group">
                                <label class="col-sm-4 right" for="form-field-3">Số lượng</label>
                                <div class="col-sm-7">
                                    <input type="text" id="form-field-3" class="h5a-input form-control input-sm" value="120">
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-sm-4 right" for="form-field-4">Giá nhập</label>
                                <div class="col-sm-7">
                                    <input type="text" id="form-field-4" class="h5a-input form-control input-sm" value="325.000">
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="col-sm-10 col-sm-offset-1">
                                    <button class="btn h5a-btn btn-primary full">Nhập hàng</button>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>