<?php
     $this->headTitle('Sản phẩm');
     
     $form->setAttribute('action', $this->url('hang_hoa/crud', array('action' => 'sanPham','id'=>$sanPhams->getIdSanPham())));
     $form->setAttribute('role','form');
     $form->prepare();
     echo $this->form()->openTag($form);
     $sanPham=$form->get('san-pham');
?>

<div class="container">
        <div class="row">
            <div class="col-md-2">
                <div class="h5a-sidebar affix">
                    <span class="breadcrumb row">
                        <a href="<?php echo $this->url('hang_hoa/crud',array('action'=>'index'));?>">/ Kho</a>
                        <a href="<?php echo $this->url('hang_hoa/crud',array('action'=>'hangHoa'));?>">/ Hàng hóa</a>
                         / #xxx /
                    </span>
                    <ul class="nav h5a-sidenav nav-list accordion">
                    </ul>
                </div>
            </div>
            <div class="col-md-10" role="main">
                <div class="h5a-docs-section">
                </div>
            </div>
        </div>
</div>
<!-- /.container -->
<div class="container h5a-container gray">
    <div class="row">
        <div class="col-md-10 col-md-offset-2">
            <h1>
                <img class="pull-left img-circle" width="40px" height="40px" src="<?php echo $this->basePath();?>/img/<?php echo $sanPhams->getHinhAnh(); ?>" alt=""> <?php echo $sanPhams->getTenSanPham(); ?>
            </h1>
            <div class="btn-group pull-right">
                <a href="<?php echo $this->url('hang_hoa/crud', array('action'=>'xoaSanPham','id'=>$sanPhams->getIdSanPham())); ?>" class="btn h5a-btn btn-danger btn-xs" onclick="return xacNhanXoa()"><i class="fa fa-times"></i> Xóa sản phẩm</a>                
            </div>
            	<p>
                    <?php echo $sanPhams->getMoTa(); ?>
            	</p>
            <div class="tabbable">
                <ul class="nav nav-tabs" role="tablist" id="myTab">
                    <li role="presentation" class="active">
                        <a href="#home" role="tab" data-toggle="tab">Xem chi tiết</a>
                    </li>
                    <li role="presentation">
                        <a href="#1" role="tab" data-toggle="tab">Cập nhật</a>
                    </li>
                </ul>
                <div class="tab-content">
                    <div role="tabpanel" class="tab-pane active" id="home">
                        <div class="row">
                            <div class="col-md-6">
                                <div class="thumbnail">
                                    <img class="img-responsive" src="<?php echo $this->basePath();?>/img/<?php echo $sanPhams->getHinhAnh(); ?>" alt="Whatever Item">
                                </div>
                            </div>
                            <div class="col-md-6">
                                <h4>Sản phẩm: <?php echo $sanPhams->getTenSanPham(); ?></h4>
                                <h4 class="underline">Thông tin chi tiết</h4>
                                <table class="item">
                                    <tbody>
                                        <tr>
                                            <td> ID: </td>
                                            <td><?php echo $sanPhams->getIdSanPham(); ?></td>
                                        </tr>
                                        <tr>
                                            <td>Tên sản phẩm: </td>
                                            <td><?php echo $sanPhams->getTenSanPham(); ?></td>
                                        </tr>
                                        <tr>
                                            <td> Mã sản phẩm: </td>
                                            <td class="red"><?php echo $sanPhams->getMaSanPham(); ?></td>
                                        </tr>                                  
                                        <tr>
                                            <td>Mô tả: </td>
                                            <td>
                                                <?php
                                                    echo $sanPhams->getMoTa(); 
                                                ?>
                                            </td>
                                        </tr>
                                        <tr>
                                            <td>Loại: </td>
                                            <td><?php echo $sanPhams->getIdLoai()->getTermId()->getName(); ?></td>
                                        </tr>
                                        <tr>
                                            <td>Nhãn: </td>
                                            <td><?php echo $sanPhams->getNhan(); ?></td>
                                        </tr>
                                        <tr>
                                            <td>Đơn vị tính: </td>
                                            <td><?php echo $sanPhams->getIdDonViTinh()->getTermId()->getName(); ?></td>
                                        </tr>
                                        <tr>
                                            <td>Thông tin khác</td>
                                            <td></td>
                                        </tr>
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                    <div role="tabpanel" class="tab-pane" id="1">
                        <div class="row">
                            <div class="col-md-6">                            
                                	<input type="text" class="form-control h5a-input" placeholder="Tiêu đề" value="Mô tả sản phẩm" disabled="disabled">
                                    <p>
                                        <?php                                        
                                            echo $this->formHidden($sanPham->get('idSanPham'));
                                            echo $this->formHidden($sanPham->get('tonKho'));
                                            echo $this->formHidden($sanPham->get('giaNhap'));
                                            

                                            $moTa=$sanPham->get('moTa');
                                            $moTa->setAttribute('class','form-control h5a');
                                            $moTa->setAttribute('id','editor');
                                            $moTa->setAttribute('rows','5');
                                            echo $this->formElement($moTa);                                                
                                        ?>
                                            <br><br>

                                    </p>
		                            <h4 class="underline">More Info</h4>
		                            <table class="item">
		                                <tbody>
		                                    <tr>
		                                        <td>Tên sản phẩm</td>
		                                        <td>
                                                    <?php 
                                                        $tenSanPham=$sanPham->get('tenSanPham');
                                                        $tenSanPham->setAttribute('class','form-control h5a');
                                                        $tenSanPham->setAttribute('id','editor');
                                                        echo $this->formElement($tenSanPham);                                                
                                                    ?>
		                                        </td>
		                                    </tr>
		                                    <tr>
		                                        <td>Mã sản phẩm</td>
		                                        <td>
                                                    <?php 
                                                        $maSanPham=$sanPham->get('maSanPham');
                                                        $maSanPham->setAttribute('class','form-control h5a');
                                                        $maSanPham->setAttribute('id','editor');
                                                        echo $this->formElement($maSanPham);                                                
                                                    ?>
                                                </td>
		                                    </tr>

                                            <tr>
                                                <td>Hình ảnh</td>
                                                <td>
                                                    <img width="350px" height="350px" src="<?php echo $this->basePath();?>/img/<?php echo $sanPhams->getHinhAnh(); ?>" alt="Whatever Item">
                                                </td>
                                            </tr>
		                                    
		                                    <tr>
		                                        <td>Đổi hình ảnh: </td>
		                                        <td>
                                                    <?php                                                                  
                                                        $hinhAnh=$sanPham->get('hinhAnh');     
                                                        $hinhAnh->setAttribute('class','h5a-btn btn btn-primary');
                                                        echo $this->formElement($hinhAnh);                                                
                                                    ?>  
		                                        </td>
		                                    </tr>
		                                    <tr>
		                                        <td>Loại</td>
		                                        <td class="green"> 
		                                           <?php                                                                  
                                                        $idLoai=$sanPham->get('idLoai');                                                
                                                        $idLoai->setAttribute('class','form-control h5a-input');
                                                        $idLoai->setValueOptions($this->MakeArrayOptionTaxonomy($loais));
                                                        echo $this->formElement($idLoai);                                                
                                                    ?>                 
		                                        </td>
		                                    </tr>                                      
		                                    <tr>
		                                        <td>Nhãn</td>
		                                        <td class="red">                           
		                                            <?php 
                                                        $nhan=$sanPham->get('nhan');
                                                        $nhan->setAttribute('class','form-control h5a');
                                                        $nhan->setAttribute('id','editor');
                                                        echo $this->formElement($nhan);                                                
                                                    ?>
		                                        </td>
		                                    </tr>
		                                    <tr>
		                                        <td>Đơn vị tính</td>
		                                        <td>
                                                    <?php                                                                  
                                                        $donViTinh=$sanPham->get('idDonViTinh');                                                
                                                        $donViTinh->setAttribute('class','form-control h5a-input');
                                                        $donViTinh->setValueOptions($this->MakeArrayOptionTaxonomy($donViTinhs));
                                                        echo $this->formElement($donViTinh);                                                
                                                    ?>
		                                        </td>
		                                    </tr>
                                            <?php
                                                foreach ($kenhPhanPhois as $kenhPhanPhoi) 
                                                {
                                                    if($kenhPhanPhoi['cap']>0)
                                                    {
                                                        echo '<tr>';
                                                            echo '<td>'.$kenhPhanPhoi['termId']['name'].'</td>';
                                                            echo '<td>'; 
                                                                $giaXuat=$this->InGiaXuat($sanPhams->getIdSanPham(),$kenhPhanPhoi['termTaxonomyId']);                                      
                                                                echo '<input type="text" class="form-control h5a-input" name="'.$kenhPhanPhoi['termTaxonomyId'].'" value="'.$giaXuat.'"/>';
                                                            echo '</td>';
                                                        echo '</tr>';
                                                    }
                                                }
                                            ?>
		                                    <tr>
                                                <td colspan="2">
                                                    <br>
                                                    <?php 
                                                        $form->get('submit')->setAttribute('class','full btn h5a-btn btn-success');
                                                        $form->get('submit')->setAttribute('value','LƯU THAY ĐỔI');
                                                        echo $this->formSubmit($form->get('submit'));
                                                    ?>
                                                </td>
                                            </tr>
		                                </tbody>
		                            </table>
		                        
                            </div>
                            <div class="col-md-6">

                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<?php
    echo $this->form()->closeTag();
?>

<!-- jQuery -->
<script src="<?php echo $this->basePath();?>/js/jquery.js"></script>

<!-- Bootstrap Core JavaScript -->
<script src="<?php echo $this->basePath();?>/js/bootstrap.min.js"></script>

<!-- DataTables JavaScript -->
<script src="<?php echo $this->basePath();?>/js/plugins/dataTables/jquery.dataTables.js"></script>

<!-- editor -->
<script src="<?php echo $this->basePath();?>/js/summernote.min.js"></script>

<script>
$(document).ready(function() {
    $('#dataTables-example').dataTable({
        "pagingType": "simple",
        "bPaginate": true,
        "bLengthChange": true,
        "bFilter": true,
        "bInfo": true,
        "bAutoWidth": true
    });
});
$("#editor").summernote({height:150});
</script>
<script language="JavaScript">
    function xacNhanXoa() {
      var xacNhan=confirm("Bạn thật sự muốn xóa sản phẩm này?");
      if(xacNhan==true)
      {
        return true;
      }
      return false;
    }
</script>