<head>
    <meta charset="UTF-8">    
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>Thêm sản phẩm</title>
</head>
<?php
 $sanPham=$form->get('san-pham');
 echo $this->formHidden($sanPham->get('idSanPham'));
?>
<div class="container">
        <div class="row">
            <div class="col-md-2">
                <div class="h5a-sidebar affix">
                    <span class="breadcrumb row">
                        <a href="<?php echo $this->url('hang_hoa/crud',array('action'=>'index'));?>">/ Kho</a>
                        <a href="<?php echo $this->url('hang_hoa');?>">/ Hàng hóa</a>
                         / Thêm sản phẩm /
                    </span>
                    <ul class="nav h5a-sidenav nav-list accordion">                        
                        <li>
                            <a href="<?php echo $this->url('hang_hoa');?>">
                                <i class="fa fa-cubes"></i> Danh sách hàng
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
            <div class="col-md-10" role="main">
                <div class="h5a-docs-section">
                    <div class="page-header">
                        <div class="row">
                            <div class="col-sm-6">
                                <h1>Thêm sản phẩm</h1>
                            </div>
                            <div class="col-sm-6">
                                <div class="pull-right">
                                    <button type="button" class="h5a-btn btn btn-default btn-sm">Hủy</button>
                                    <button type="button" class="h5a-btn btn btn-primary btn-sm">Lưu
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <form>
                            <h4 class="underline">More Info</h4>
                            <table class="item">
                                <tbody>
                                    <tr>
                                        <td>Tên sản phẩm</td>
                                        <td>
                                            <input type="text" id="txtTenSanPham" placeholder="Tên sản phẩm" class="h5a-input form-control input-sm">
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>Mã sản phẩm</td>
                                        <td><input type="text" class="form-control h5a-input" placeholder="Mã sản phẩm"></td>
                                    </tr>
                                    <tr>
                                        <td>Mô tả</td>
                                        <td>
                                            <textarea class="form-control h5a" rows="5" id="editor"></textarea>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>Hình ảnh</td>
                                        <td>
                                            <input type="filepicker" data-fp-button-text="<i class='fa fa-cloud-upload'></i> Files UPLOAD from ANYWERE" data-fp-apikey="fakeAPIkey" name="filePicker" id="filePicker" class="h5a-btn btn btn-primary" style="display: none;">
                                            <button type="button" class="h5a-btn btn btn-primary"><i class="fa fa-cloud-upload"></i>Tải lên</button>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>Loại</td>
                                        <td class="green"> 
                                            <select class="form-control h5a-input" name="loai">
                                            </select>                      
                                        </td>
                                    </tr>                                      
                                    <tr>
                                        <td>Nhãn</td>
                                        <td class="red">                           
                                            <input type="text" class="form-control h5a-input" placeholder="Nhãn">
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>Đơn vị tính</td>
                                        <td>
                                            <select class="form-control h5a-input" name="don_vi_tinh">
                                            </select>
                                        </td>
                                    </tr>
                                </tbody>
                            </table>
                        </form>
                    </div>
                    <div class="page-footer">
                        <div class="row bottom20">
                            <div class="col-sm-6 col-sm-offset-6">
                                <div class="pull-right">
                                    <button type="button" class="h5a-btn btn btn-default btn-sm">Hủy</button>
                                    <button type="button" class="h5a-btn btn btn-primary btn-sm">Lưu
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
        
    <!-- jQuery -->
    <script src="<?php echo $this->basePath();?>/js/jquery.js"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="<?php echo $this->basePath();?>/js/bootstrap.min.js"></script>

    <!-- DataTables JavaScript -->
    <script src="<?php echo $this->basePath();?>/js/plugins/dataTables/jquery.dataTables.js"></script>

    <!-- Summernot JavaScript -->
    <script src="<?php echo $this->basePath();?>/js/summernote.min.js"></script>

    <script>
    $(document).ready(function() {
        $('#dataTables-example').dataTable({
            "pagingType": "simple",
            "bPaginate": true,
            "bLengthChange": true,
            "bFilter": true,
            "bInfo": true,
            "bAutoWidth": true
        });
    });

    $("#editor").summernote({height:150});
    </script>