<head>
    <meta charset="UTF-8">    
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>Thêm sản phẩm</title>
</head>
<?php
    $sanPham=$form->get('san-pham');
    //die(var_dump($sanPham));
    echo $this->formHidden($sanPham->get('idSanPham'));    
?>
<div class="container">
        <div class="row">
            <div class="col-md-2">
                <div class="h5a-sidebar affix">
                    <span class="breadcrumb row">
                        <a href="<?php echo $this->url('hang_hoa/crud',array('action'=>'index'));?>">/ Kho</a>
                        <a href="<?php echo $this->url('hang_hoa');?>">/ Hàng hóa</a>
                         / Thêm sản phẩm /
                    </span>
                    <ul class="nav h5a-sidenav nav-list accordion">                        
                        <li>
                            <a href="<?php echo $this->url('hang_hoa');?>">
                                <i class="fa fa-cubes"></i> Danh sách hàng
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
            <div class="col-md-10" role="main">
                <div class="h5a-docs-section">                    
                    <form name="frmThemSanPham" action="<?php echo $this->url('hang_hoa/crud', array('action' => 'themSanPham'));?>" method="post">
                        <div class="page-header">
                            <div class="row">
                                <div class="col-sm-6">
                                    <h1>Thêm sản phẩm</h1>
                                </div>
                                <div class="col-sm-6">
                                    <div class="pull-right">
                                        <button type="button" class="h5a-btn btn btn-default btn-sm">Hủy</button>                                    
                                        <button type="submit" class="h5a-btn btn btn-primary btn-sm">Lưu</button>                                        
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <table class="item">
                                <tbody>
                                    <tr>
                                        <td>Tên sản phẩm</td>
                                        <td>
                                            <!-- <input type="text" name="txtTenSanPham" placeholder="Tên sản phẩm" class="h5a-input form-control input-sm"> -->
                                            <?php 
                                                $tenSanPham=$sanPham->get('tenSanPham');
                                                $tenSanPham->setAttribute('class','h5a-input form-control input-sm');
                                                $tenSanPham->setAttribute('placeholder','Tên sản phẩm');
                                                echo $this->formElement($tenSanPham);
                                            ?>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>Mã sản phẩm</td>
                                        <td>
                                            <!-- <input type="text" class="form-control h5a-input" name="txtMaSanPham" placeholder="Mã sản phẩm"> -->
                                            <?php 
                                                $maSanPham=$sanPham->get('maSanPham');
                                                $maSanPham->setAttribute('class','form-control h5a-input');
                                                $maSanPham->setAttribute('placeholder','Mã sản phẩm');
                                                echo $this->formElement($maSanPham);
                                            ?>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>Mô tả</td>
                                        <td>
                                            <!-- <textarea class="form-control h5a" rows="5" id="editor" name="moTa"></textarea> -->
                                            <?php 
                                                $moTa=$sanPham->get('moTa');
                                                $moTa->setAttribute('class','form-control h5a');                                                
                                                $moTa->setAttribute('id','editor');
                                                echo $this->formElement($moTa);
                                            ?>
                                        </td>
                                    </tr>
                                    <!-- <tr>
                                        <td>Hình ảnh</td>
                                        <td>
                                            <input type="filepicker" data-fp-button-text="<i class='fa fa-cloud-upload'></i> Files UPLOAD from ANYWERE" data-fp-apikey="fakeAPIkey" name="filePicker" id="filePicker" class="h5a-btn btn btn-primary" style="display: none;">
                                            <button type="button" class="h5a-btn btn btn-primary"><i class="fa fa-cloud-upload"></i>Tải lên</button>
                                        </td>
                                    </tr> -->
                                    <tr>
                                        <td>Loại</td>
                                        <td>
                                            <?php
                                                //$loais=$this->MakeArrayOptionTaxonomy($loais);                                                
                                            ?>                                                                                        
                                            <!-- <select name="loai" style="text-align:center; color: rgb(85, 85, 85); display: block; height: 34px; padding: 6px 12px; font-size: 14px; line-height: 1.42857; background-color: rgb(255, 255, 255); background-image: none; border: 1px solid rgb(204, 204, 204); border-radius: 4px; box-shadow: 0px 1px 1px rgba(0, 0, 0, 0.075) inset; transition: border-color 0.15s ease-in-out 0s, box-shadow 0.15s ease-in-out 0s; width: 50%;">
                                                <option value="">---Loại---</option>
                                            <?php foreach($loais as $idLoai=>$loai){ ?>
                                                <option style="text-align:left" value="<?php echo $idLoai; ?>"><?php echo $loai;?></option>      
                                            <?php } ?>
                                            </select> -->

                                            <?php                                                
                                                $loai=$sanPham->get('idLoai');                                                
                                                $loai->setAttribute('style','width:35%;height:35px');                                                
                                                //die(var_dump($donViTinh));
                                                $loai->setValueOptions($this->MakeArrayOptionTaxonomy($loais));
                                                echo $this->formElement($loai);
                                            ?>
                                        </td>
                                    </tr>                                      
                                    <tr>
                                        <td>Nhãn</td>
                                        <td class="red">                           
                                            <!-- <input type="text" class="form-control h5a-input" name="txtNhan" placeholder="Nhãn"> -->
                                            <?php 
                                                $nhan=$sanPham->get('nhan');
                                                $nhan->setAttribute('class','form-control h5a-input');
                                                $nhan->setAttribute('placeholder','Nhãn sản phẩm');
                                                echo $this->formElement($nhan);
                                            ?>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>Đơn vị tính</td>
                                        <td>
                                            <?php
                                                //$donViTinhs=$this->MakeArrayOptionTaxonomy($donViTinhs);                                              
                                            ?>                                                                                        
                                            <!-- <select name="loai" style="text-align:center; color: rgb(85, 85, 85); display: block; height: 34px; padding: 6px 12px; font-size: 14px; line-height: 1.42857; background-color: rgb(255, 255, 255); background-image: none; border: 1px solid rgb(204, 204, 204); border-radius: 4px; box-shadow: 0px 1px 1px rgba(0, 0, 0, 0.075) inset; transition: border-color 0.15s ease-in-out 0s, box-shadow 0.15s ease-in-out 0s; width: 50%;">
                                                <option value="">---Đơn vị tính---</option>
                                            <?php foreach($donViTinhs as $idDonViTinh=>$donViTinh){ ?>
                                                <option style="text-align:left" value="<?php echo $idDonViTinh; ?>"><?php echo $donViTinh;?></option>      
                                            <?php } ?>
                                            </select> -->

                                            <?php                                                                  
                                                $donViTinh=$sanPham->get('idDonViTinh');                                                
                                                $donViTinh->setAttribute('style','width:35%;height:35px');                                                
                                                $donViTinh->setValueOptions($this->MakeArrayOptionTaxonomy($donViTinhs));
                                                echo $this->formElement($donViTinh);
                                            ?>
                                        </td>
                                    </tr>
                                </tbody>
                            </table>                            
                        </div>
                        <div class="page-footer">
                            <div class="row bottom20">
                                <div class="col-sm-6 col-sm-offset-6">
                                    <div class="pull-right">
                                        <button type="reset" class="h5a-btn btn btn-default btn-sm">Hủy</button>
                                        <button type="submit" class="h5a-btn btn btn-primary btn-sm">Lưu</button>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
</div>

<!-- jQuery -->
<script src="<?php echo $this->basePath();?>/js/jquery.js"></script>

<!-- Bootstrap Core JavaScript -->
<script src="<?php echo $this->basePath();?>/js/bootstrap.min.js"></script>

<!-- DataTables JavaScript -->
<script src="<?php echo $this->basePath();?>/js/plugins/dataTables/jquery.dataTables.js"></script>

<!-- Summernot JavaScript -->
<!--<script src="<?php echo $this->basePath();?>/js/summernote.min.js"></script>-->

<!-- Page-Level Demo Scripts - Tables - Use for reference -->
<script>
$(document).ready(function() {
    $('#dataTables-example').dataTable({
        "pagingType": "simple",
        "bPaginate": true,
        "bLengthChange": true,
        "bFilter": true,
        "bInfo": true,
        "bAutoWidth": true
    });
});

$("#editor").summernote({height:150});
</script>