<script>
   
    kiemTracheckbox = function(){
        var tam=document.getElementById("loaiGia").checked;
        if(tam)
        {
            // có check thì hiển thị và giá trị bằng 1
            document.getElementById("loaiGia").value=1;
            document.getElementById("trGiaBia").hidden=false;
            document.getElementById("trChiecKhau").hidden=false;
            document.getElementById('trGiaNhap').hidden=true;
        }
        else
        {
            // không có check thì ẩn và giá trị bằng 0
            document.getElementById("loaiGia").value=0;
            document.getElementById("trGiaBia").hidden=true;
            document.getElementById("trChiecKhau").hidden=true;
            document.getElementById('trGiaNhap').hidden=false;
        }
        return true;
    }

</script>
<?php
 $this->headTitle('Thêm sản phẩm');

 $form->setAttribute('action', $this->url('hang_hoa/crud', array('action' => 'themSanPham')));
 $form->setAttribute('role','form');
 $form->prepare();
 echo $this->form()->openTag($form);

 $sanPham=$form->get('san-pham');    
 echo $this->formHidden($sanPham->get('idSanPham'));
 echo $this->formHidden($sanPham->get('tonKho'));
 echo $this->formHidden($sanPham->get('giaNhap'));
?>

<div class="row">
    <div class="col-md-2">
        <div class="h5a-sidebar affix">
            <span class="breadcrumb row">
                <a href="<?php echo $this->url('hang_hoa/crud',array('action'=>'index'));?>">/ Kho</a>
                <a href="<?php echo $this->url('hang_hoa');?>">/ Hàng hóa</a>
                 / Thêm sản phẩm /
            </span>
            <ul class="nav h5a-sidenav nav-list accordion">                        
                <li>
                    <a href="<?php echo $this->url('hang_hoa/crud',array('action'=>'hangHoa'));?>">
                        <i class="fa fa-cubes"></i> Danh sách hàng
                    </a>
                </li>
            </ul>
        </div>
    </div>
    <div class="col-md-10" role="main">
        <div class="h5a-docs-section">                
            <div class="page-header">
                <div class="row">
                    <div class="col-sm-6">
                        <h1>Thêm sản phẩm</h1>
                    </div>
                    <div class="col-sm-6">
                        <div class="pull-right">
                            <button type="reset" class="h5a-btn btn btn-default btn-sm">Hủy</button>
                            <button type="submit" class="h5a-btn btn btn-primary btn-sm">Lưu</button>                                
                        </div>
                    </div>
                </div>
                <?php
                    $flash=$this->flashMessenger();
                    $flash->setMessageOpenFormat('<div%s>
                     <button type="button" class="close" data-dismiss="alert" aria-hidden="true">
                         &times;
                     </button>
                     <ul><li>')
                     ->setMessageSeparatorString('</li><li>')
                     ->setMessageCloseString('</li></ul></div>');

                     echo $flash->render('error',   array('alert', 'alert-dismissable', 'alert-danger'));
                     echo $flash->render('info',    array('alert', 'alert-dismissable', 'alert-info'));
                     echo $flash->render('default', array('alert', 'alert-dismissable', 'alert-warning'));
                     echo $flash->render('success', array('alert', 'alert-dismissable', 'alert-success'));
                ?>
            </div>
            <div class="row">
                <table class="item">
                    <tbody>
                        <tr>
                            <td>Tên sản phẩm</td>
                            <td>                                            
                                <?php 
                                    $tenSanPham=$sanPham->get('tenSanPham');
                                    $tenSanPham->setAttribute('class','h5a-input form-control input-sm');
                                    $tenSanPham->setAttribute('placeholder','Tên sản phẩm');
                                    echo $this->formElement($tenSanPham);
                                    
                                ?>
                            </td>
                        </tr>
                        <tr>
                            <td>Mã sản phẩm</td>
                            <td>                                            
                                <?php 
                                    $maSanPham=$sanPham->get('maSanPham');
                                    $maSanPham->setAttribute('class','form-control h5a-input');
                                    $maSanPham->setAttribute('placeholder','Mã sản phẩm');
                                    echo $this->formElement($maSanPham);
                                    if($kiemTraTonTai==1)
                                    {
                                        echo '<p class="badge red" style="color:white">Mã sản phẩm đã tồn tại</p>';
                                    }                                                
                                ?>
                            </td>
                        </tr>
                        <tr>
                            <td>Nhãn</td>
                            <td class="red">                                                                       
                                <?php 
                                    $nhan=$sanPham->get('nhan');
                                    $nhan->setAttribute('class','form-control h5a-input');
                                    $nhan->setAttribute('placeholder','Nhãn sản phẩm');
                                    echo $this->formElement($nhan);                                                
                                ?>
                            </td>
                        </tr>
                        <tr>
                            <td>Loại</td>
                            <td>
                                <?php                                                
                                    $loai=$sanPham->get('idLoai');                                                
                                    $loai->setAttribute('style','width:35%;height:35px');
                                    $loai->setValueOptions($this->MakeArrayOptionTaxonomy($loais));
                                    echo $this->formElement($loai);                                                
                                ?>
                            </td>
                        </tr>                                    
                        <tr>
                            <td>Đơn vị tính</td>
                            <td>
                                <?php                                                                  
                                    $donViTinh=$sanPham->get('idDonViTinh');                                                
                                    $donViTinh->setAttribute('style','width:35%;height:35px');
                                    $donViTinh->setValueOptions($this->MakeArrayOptionTaxonomy($donViTinhs));
                                    echo $this->formElement($donViTinh);                                                
                                ?>
                            </td>
                        </tr>  
                        <tr>
                            <td></td>
                            <td>
                                <?php                                                                  
                                    $loaiGia=$sanPham->get('loaiGia');
                                    $loaiGia->setAttribute('id','loaiGia');
                                    $loaiGia->setAttribute('onChange','return kiemTracheckbox();');

                                    echo $this->formElement($loaiGia);                                               
                                ?>
                                <!--<input type="checkbox" id='loaiChiecKhau' name="loaiChiecKhau" onChange="return kiemTracheckbox();">-->
                                Sản phẩm thuộc loại có giá in trên bìa
                            </td>
                        </tr> 
                        <tr id="trGiaNhap">
                            <td>Giá nhập</td>
                            <td>
                                <?php                                                                  
                                    $giaNhap=$sanPham->get('giaNhap');
                                    $giaNhap->setAttribute('class','h5a-input form-control input-sm');
                                    echo $this->formElement($giaNhap);                                               
                                ?>
                            </td>
                        </tr> 
                        <tr hidden="true" id='trGiaBia'>
                            <td>Giá bìa</td>
                            <td>
                                <?php                                                                  
                                    $giaNhap=$sanPham->get('giaBia');
                                    $giaNhap->setAttribute('class','h5a-input form-control input-sm');
                                    echo $this->formElement($giaNhap);                                               
                                ?>
                            </td>
                        </tr> 
                        <tr hidden='true' id='trChiecKhau'>
                            <td>Chiếc khấu (%)</td>
                            <td>
                                <?php                                                                  
                                    $chiecKhau=$sanPham->get('chiecKhau');
                                    $chiecKhau->setAttribute('class','h5a-input form-control input-sm');
                                    echo $this->formElement($chiecKhau);                                               
                                ?>                               
                            </td>
                        </tr>   
                        <tr>
                            <td>Mô tả</td>
                            <td>                                        
                                <?php 
                                    $moTa=$sanPham->get('moTa');
                                    $moTa->setAttribute('class','form-control h5a');
                                    $moTa->setAttribute('id','editor');
                                    echo $this->formElement($moTa);                                                
                                ?>
                            </td>
                        <tr>
                            <td>Hình ảnh</td>
                            <td>
                                <?php                                                
                                    $hinhAnh=$sanPham->get('hinhAnh');
                                    $hinhAnh->setAttribute('class','h5a-btn btn btn-primary');
                                    echo $this->formElement($hinhAnh);                                                
                                ?>
                            </td>
                        </tr>                                    
                                                         
                    </tbody>
                </table>                            
            </div>
            <div class="page-footer">
                <div class="row bottom20">
                    <div class="col-sm-6 col-sm-offset-6">
                        <div class="pull-right">
                            <button type="reset" class="h5a-btn btn btn-default btn-sm">Hủy</button>
                            <button type="submit" class="h5a-btn btn btn-primary btn-sm">Lưu</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<?php
    echo $this->form()->closeTag();
?>
<!-- jQuery -->
<script src="<?php echo $this->basePath();?>/js/jquery.js"></script>

<!-- Bootstrap Core JavaScript -->
<script src="<?php echo $this->basePath();?>/js/bootstrap.min.js"></script>

<!-- DataTables JavaScript -->
<script src="<?php echo $this->basePath();?>/js/plugins/dataTables/jquery.dataTables.js"></script>

<!-- Summernot JavaScript -->
<script src="<?php echo $this->basePath();?>/js/summernote.min.js"></script>

<!-- Page-Level Demo Scripts - Tables - Use for reference -->
<script>
$(document).ready(function() {
    $('#dataTables-example').dataTable({
        "pagingType": "simple",
        "bPaginate": true,
        "bLengthChange": true,
        "bFilter": true,
        "bInfo": true,
        "bAutoWidth": true,
    });
    $('#loaiGia').val(0);

});

$("#editor").summernote({height:150});
</script>