<?php
$title = 'Xuất hàng';
$this->headTitle($title);
 $form->setAttribute('action', $this->url('hang_hoa/crud', array('action' => 'xuatHang')));
 $form->setAttribute('role','form');
 $form->setAttribute('id','formXuatHang');
 $form->setAttribute('class','form-horizontal');
 $form->prepare();
 echo $this->form()->openTag($form);
?>

<style type="text/css">
   
    @media print {       
        .col-sm-3 {display: none;}

        .form-group{display: none;}

        .col-md-2{display: none;}
        h1{display: none;}
        .page-header{display: none;}
        .an{display: none;}
        .print{display: block; text-align: left;}
        #h5a-container{display: none;}
        .printHoTen {display: block;}
        .printDiaChi {display: block;}
        .printNgayXuat{display: block;}
        table {display: table;}
    }
    #san-pham-search-result{ cursor:pointer;}
    #search-result{cursor:pointer;}
</style>

<div class="row">
    <div class="col-md-2">
        <div class="h5a-sidebar affix">
            <span class="breadcrumb row">
                <a href="<?php echo $this->url('hang_hoa/crud',array('action'=>'index'));?>">/ Kho</a>                        
                <a href="<?php echo $this->url('hang_hoa/crud',array('action'=>'hangHoa'));?>">/ Hàng hóa</a>
                 / Xuất hàng /
            </span>
            <ul class="nav h5a-sidenav nav-list accordion">                        
                <li>
                    <a href="<?php echo $this->url('hang_hoa/crud',array('action'=>'hangHoa'));?>">
                        <i class="fa fa-cubes"></i> Danh sách hàng
                    </a>
                </li>
                <li>
                    <a href="<?php echo $this->url('hang_hoa/crud',array('action'=>'nhapHang'));?>">
                        <i class="fa fa-download"></i> Nhập hàng
                    </a>
                </li>
                <li>
                    <a href="<?php echo $this->url('hang_hoa/crud',array('action'=>'xuatHang'));?>">
                        <i class="fa fa-upload"></i> Xuất hàng
                    </a>
                </li>
            </ul>
        </div>
    </div>

    <div class="col-md-10" role="main">
        <div class="h5a-docs-section">
            <div class="page-header">
                <div class="row">
                    <div class="col-sm-6">
                        <h1>Xuất hàng</h1>
                    </div>                  
                </div>
                <?php
                    $flash=$this->flashMessenger();
                    $flash->setMessageOpenFormat('<div%s>
                     <button type="button" id="btFm" class="close" data-dismiss="alert" aria-hidden="true">
                         &times;
                     </button>
                     <ul><li>')
                     ->setMessageSeparatorString('</li><li>')
                     ->setMessageCloseString('</li></ul></div>');

                     $error=$flash->render('error',   array('alert', 'alert-dismissable', 'alert-danger'));
                     echo $error;

                     $info=$flash->render('info',    array('alert', 'alert-dismissable', 'alert-info'));
                     echo $info;

                     $default=$flash->render('default', array('alert', 'alert-dismissable', 'alert-warning'));
                     echo $default;

                     $success=$flash->render('success', array('alert', 'alert-dismissable', 'alert-success'));
                     echo $success;                     
                    if($error||$success||$info||$default)
                    {
                        echo '
                        <script type="text/javascript">
                            setTimeout(function(){
                                document.getElementById("btFm").click();
                            },5000);
                        </script>';                        
                    }
                ?>
            </div>

                <div class="col-sm-6">
                    <div class="form-group">
                        <label class="col-sm-4 right" for="form-field-3">Khách hàng</label>
                        <div class="col-sm-7">
                            <!--<input type="text" id="form-field-3" class="h5a-input form-control input-sm" value="Trường Đại học Trà Vinh">-->
                        <?php
                            $hoaDon = $form->get('hoa-don');
                            echo $this->formHidden($form->get('idKhachHang'));
                            echo $this->formHidden($form->get('idSanPham'));
                            echo $this->formHidden($form->get('donViTinh'));
                            echo $this->formRow($form->get('khachHang'));
                            echo $this->formHidden($hoaDon->get('idDoiTac')->get('idDoiTac'));
                            echo $this->formHidden($hoaDon->get('status'));
                            //echo $this->formCollection($hoaDon->get('ctHoaDons'));
                        ?>
                        <input type='hidden' name="" />
                        <div id="search-result"></div>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-4 right" for="form-field-4">Địa chỉ</label>
                        <div class="col-sm-7">
                            <!--<input type="text" id="form-field-4" class="h5a-input form-control input-sm" value="Số 126 Quốc lộ 53, khóm 4, phường 5, Tp.Trà Vinh, tỉnh Trà Vinh">-->
                        <?php
                            echo $this->formRow($form->get('diaChi'));
                        ?>
                        </div>
                    </div>
                </div>
                <div class="col-sm-6 box">
                    <div class="form-group">
                        <label class="col-sm-4 right" for="form-field-1">Mã hàng</label>
                        <div class="col-sm-7">
                            <!--<input type="text" id="form-field-1" placeholder="Mã hàng" class="h5a-input form-control input-sm">-->
                        <?php
                            echo $this->formRow($form->get('maHang'));
                        ?>
                        <div id="san-pham-search-result"></div>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-4 right" for="form-field-2">Tên hàng</label>
                        <div class="col-sm-7">
                            <!--<input type="text" id="form-field-2" placeholder="Tên hàng" class="h5a-input form-control input-sm">-->
                        <?php
                            echo $this->formRow($form->get('tenHang'));
                        ?>
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="col-sm-4 right" for="form-field-3">Số lượng</label>
                        <div class="col-sm-7">
                            <!--<input type="text" id="form-field-3" class="h5a-input form-control input-sm" value="120">-->
                        <?php
                            echo $this->formRow($form->get('soLuong'));
                        ?>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-4 right" for="form-field-4">Giá xuất</label>
                        <div class="col-sm-7">
                            <!--<input type="text" id="form-field-4" class="h5a-input form-control input-sm" value="325.000">-->
                        <?php
                            echo $this->formRow($form->get('giaXuat'));
                        ?>
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-sm-10 col-sm-offset-1">
                            <input type="hidden" id="tonKho"/>
                            <input type="hidden" id="kenhPhanPhoi" value=""/>
                            <input type="hidden" id="giaXuat" value=""/>
                            <button id="btnThemHang" class="btn h5a-btn btn-primary full">Thêm vào đơn hàng</button>
                        </div>
                    </div>

                </div>

        </div>

    </div>
</div>
<div id="h5a-container" class="h5a-container"></div>
<div class="row">
    <div class="col-md-2"></div>
    <div class="col-md-10">
        <!-- print -->
        <h1 class="print" style="color:red;" hidden="true">THÔNG TIN KHÁCH HÀNG</h1>
        <span class="printHoTen" id="printHoTen" hidden="true">Họ tên: </span>
        <span class="printDiaChi" id="printDiaChi" hidden="true" style="margin-left:0px">Địa chỉ: </span>
        <span class="printNgayXuat" hidden="true">Ngày xuất: <?php echo date("d/m/Y"); ?> </span> 
        <h1 class="print" style="color:red;" hidden="true">HÓA ĐƠN</h1>
    <!-- close print -->
        
        <h1>Danh sách xuất</h1>
       
        <div class="box">
            <table id="tbXuatHang" class="invoice pricelist bottom20">
                <thead>
                    <tr>
                        <th>Sản phẩm</th>
                        <th>Đơn vị tính</th>
                        <th>Số lượng</th>
                        <th>Giá xuất</th>
                        <th class="an" id="btnHuy">Hủy</th>
                    </tr>
                </thead>
                <tbody>
                </tbody>
            </table>
            <div class="row">
                <div class="col-sm-3">
                    <a href="<?php echo $this->url('hang_hoa/crud',array('action'=>'xuatHang'));?>"><button type="button" class="btn h5a-btn btn-danger full"  onclick="return xacNhanHuy()"><i class="fa fa-times"></i> Hủy đơn hàng</button></a>
                </div>
                <div class="col-sm-3 pull-right">
                    <button type="submit" class="btn h5a-btn btn-primary full" onclick="return inDonHangFunction();"><i class="fa fa-print"></i> In đơn hàng</button>
                </div>
            </div>
        </div>
    </div>
</div>
    
<!-- </div> -->
<?php echo $this->form()->closeTag(); ?>
    <!-- jQuery -->
    <script src="<?php echo $this->basePath();?>/js/jquery.js"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="<?php echo $this->basePath();?>/js/bootstrap.min.js"></script>

    <!-- DataTables JavaScript -->
    <script src="<?php echo $this->basePath();?>/js/plugins/dataTables/jquery.dataTables.js"></script>
    <!-- Page-Level Demo Scripts - Tables - Use for reference -->
    <script>
    $(document).ready(function() {
        $('#dataTables-example').dataTable({
            "pagingType": "simple",
            "bPaginate": true,
            "bLengthChange": true,
            "bFilter": true,
            "bInfo": true,
            "bAutoWidth": true
        });

        $('#btnThemHang').click(function(){
            var idKhachhang=$('#idKhachhang').val();
            var tenKhachHang=$('#tenKhachHang').val();
            var diaChi=$('#diaChiKhachHang').val();
            var idSanPham=$('#idSanPham').val();
            var tenHang=$('#tenHang').val();
            var donViTinh=$('#donViTinh').val();
            var soLuong=$('#soLuong').val(); 
            var giaXuat=$('#giaXuat').val();   
            var tonKho=$('#tonKho').val(); 
            var soDong = $('#tbXuatHang > tbody > tr').length; 
            if(soDong>0)
            {
                for(var i=0; i<soDong; i++)
                {
                    var id='#soDong'+i;
                    var idSP=$(id).val();
                    if(idSanPham==idSP)
                    {
                        alert('Sản phẩm đã được thêm rồi. Vui lòng kiểm tra lại!');
                        return false;
                    }
                }

            }
            

            if(idKhachhang==''||tenKhachHang==''||diaChi==''||idSanPham==''||tenHang==''||donViTinh==''||soLuong==''||giaXuat==''||tonKho==''||idKhachhang==null||tenKhachHang==null||diaChi==null||idSanPham==null||tenHang==null||donViTinh==null||soLuong==null||giaXuat==null||tonKho==null)
            {
                alert('Vui lòng điền đầy đủ thông tin');
                return false;
            }
            if(parseInt(tonKho)<parseInt(soLuong)||parseInt(soLuong)==0||parseInt(tonKho)==0)
            {
                
                if(parseInt(tonKho)==0)
                {
                    alert('Số lượng sản phẩm trong kho đã hết, Vui lòng kiểm tra lại!');
                    return false;
                }
                if(parseInt(soLuong)==0)
                {
                    alert('Vui lòng nhập số lượng!');
                    return false;
                }
                if(parseInt(tonKho)<parseInt(soLuong))
                {
                    alert('Tồn kho: '+tonKho+' < Số lượng đã nhập: '+soLuong);
                    return false;
                }
                
                
            }
            else
            {
                var soDong = $('#tbXuatHang > tbody > tr').length;   

                var template = '<tr class="price">'+
                    '<td>'+tenHang+'</td>'+
                    '<td>'+donViTinh+'</td>'+
                    '<td>'+
                        '<input type="hidden" id="soDong'+soDong+'" name="hoa-don&#x5B;ctHoaDons&#x5D;&#x5B;__index__&#x5D;&#x5B;idSanPham&#x5D;&#x5B;idSanPham&#x5D;" value="'+idSanPham+'">'+
                        '<input type="hidden" name="hoa-don&#x5B;ctHoaDons&#x5D;&#x5B;__index__&#x5D;&#x5B;soLuong&#x5D;" value="'+soLuong+'">'+
                        '<span>'+soLuong+'</span>'+
                    '</td>'+
                    '<td>'+
                        '<input type="hidden" name="hoa-don&#x5B;ctHoaDons&#x5D;&#x5B;__index__&#x5D;&#x5B;gia&#x5D;" value="'+giaXuat+'">'+
                        '<span>'+giaXuat+'</span>'+
                    '</td>'+
                    '<td class="an" style="text-align:left;">'+
                        '<a class="btnHuy"><img src="<?php echo $this->basePath(); ?>/img/delete.png" width="30px" height="30px"></a>'+
                    '</td>'+
                    '</tr>';

                    $('input[name="hoa-don[idDoiTac][idDoiTac]"]').val(idKhachhang);


                template = template.replace(/__index__/g, soDong);
                $('#tbXuatHang tbody').append(template);
                if(soDong==0)
                {
                    $('#printHoTen').append(tenKhachHang);
                    $('#printDiaChi').append(diaChi);
                }
            }
            
            return false;
        });

        var xhr;
//Hiển thị, chọn khách hàng
        $('#tenKhachHang').keyup(function(){
            var tenKhachHang=$(this).val();

            if(xhr && xhr.readyState != 4){
                xhr.abort(); //huy lenh ajax truoc do
            }

            xhr = $.ajax({
                url:'<?php echo $this->url('hang_hoa/crud', array('action'=>'searchKhachHang')); ?>',
                type:'POST',
                dataType:'json',
                data:{
                    'tenKhachHang':tenKhachHang
                },
                success:function(data){
                    $.each(data, function(key,val){
                        $('#search-result').empty(); //lam rong khung ket qua

                        var pos = $('#tenKhachHang').position(); //lấy tọa độ của ô tên khách hàng
                        $('#search-result').css({
                            position:'absolute',
                            top:pos.top + 35,
                            left:pos.left,
                            'z-index': 100 // đặt search-result lên layout ngoài nhất
                        });
                        $.each(data, function(key, val){
                            $('#search-result').append('<div class="list-group-item"><span class="hide">'+val.idKhachHang+'</span><span>'+val.tenKhachHang+'</span><span class="hide">'+val.diaChiKhachHang+'</span><span class="hide">'+val.kenhPhanPhoi+'</span></div>'); // thêm một dòng vào search result, mỗi một dòng là 1 khách hàng
                        })
                    });
                }
            });
            return false;
        });

        

        $('#search-result').on('click', '.list-group-item', function(){

            var id = $(this).find('span:eq(0)').text(); 
            var ten = $(this).find('span:eq(1)').text();
            var diaChi = $(this).find('span:eq(2)').text();
            var kenhPhanPhoi=$(this).find('span:eq(3)').text();

            $('#idKhachhang').val(id);
            $('#tenKhachHang').val(ten);
            $('#diaChiKhachHang').val(diaChi);
            $('#kenhPhanPhoi').val(kenhPhanPhoi);

            $('#search-result').empty();
        });
//./Hiển thị, chọn khách hàng

        //Hiển thị, chọn sản phẩm
        $('#maHang').keyup(function(){
            var maHang=$(this).val();            
            if(xhr && xhr.readyState != 4){
                xhr.abort(); //huy lenh ajax truoc do
            }

            xhr = $.ajax({
                url:'<?php echo $this->url('hang_hoa/crud', array('action'=>'searchSanPham')); ?>',
                type:'POST',
                dataType:'json',
                data:{
                    'maHang':maHang
                },
                success:function(data){
                    $('#san-pham-search-result').empty(); //lam rong khung ket qua

                    var pos = $('#maHang').position(); //lấy tọa độ của ô tên sản phẩm
                    $('#san-pham-search-result').css({
                        position:'absolute',
                        top:pos.top + 35,
                        left:pos.left,
                        'z-index': 100 // đặt search-result lên layout ngoài nhất
                    });
                    $.each(data, function(key,val){
                            var gx='';
                            //alert(val.giaXuat[39]);
                            
                            $.each(val.giaXuat, function(k, v)
                            {
                                if($('#kenhPhanPhoi').val()==k)
                                {
                                    gx+='<span class="hide">'+v+'</span>';
                                }
                                
                            });

                            $('#san-pham-search-result').append('<div class="list-group-item"><span class="hide">'+val.idSanPham+'</span><span class="hide">'+val.tenSanPham+'</span><span>'+val.maHang+'</span><span class="hide">'+val.donViTinh+'</span><span class="hide">'+val.tonKho+'</span>'+gx+'</div>'); // thêm một dòng vào search result, mỗi một dòng là 1 sản phẩm
                        
                    });
                }
            });
            return false;
        });

        $('#san-pham-search-result').on('click', '.list-group-item', function(){
            var id = $(this).find('span:eq(0)').text();
            var ten = $(this).find('span:eq(1)').text();
            var ma = $(this).find('span:eq(2)').text();          
            var donViTinh = $(this).find('span:eq(3)').text();
            var tonKho = $(this).find('span:eq(4)').text();// tồn kho trong cơ sở dữ liệu
            
            var giaXuat= $(this).find('span:eq(5)').text(); 
            

            $('#idSanPham').val(id);
            $('#maHang').val(ma);
            $('#tenHang').val(ten);
            $('#giaXuat').val(giaXuat);
            $('#donViTinh').val(donViTinh);
            $('#tonKho').val(tonKho);
            $('#soLuong').val(tonKho);


            $('#san-pham-search-result').empty();
        });
    });
//./Hiển thị, chọn sản phẩm


    </script>

    <script>
        inDonHangFunction=function()
        {

            var soDong = $('#tbXuatHang > tbody > tr').length; 
            if(soDong==0)
            {
                alert('Xin lỗi bạn chưa nhập sản phẩm...');
                return false;
            }
            else
            {
                window.print();
                document.getElementById('formXuatHang').submit();
                return true;
            }                
        }

    </script>
    <script>
        $(document).ready(function(){
          $(document).on('click', '.btnHuy', function(){
            $(this).closest('tr').remove();
            return false;
          });
        });
    </script>

    <script language="JavaScript">
        function xacNhanHuy() {
            var soDong = $('#tbXuatHang > tbody > tr').length; 
            if(soDong==0)
            {
                return false;
            }
            else
            {
                var xacNhan=confirm("Bạn thật sự muốn hủy đơn hàng này?");
                if(xacNhan==true)
                {
                    return true;
                }
                return false;
            }
        }
    </script>