<?php
$title = 'Xuất hàng';
$this->headTitle($title);
 $form->setAttribute('action', $this->url('hang_hoa/crud', array('action' => 'xuatHang')));
 $form->setAttribute('role','form');
 $form->setAttribute('class','form-horizontal');
 $form->prepare();
 echo $this->form()->openTag($form);
?>
<div class="container">
        <div class="row">
            <div class="col-md-2">
                <div class="h5a-sidebar affix">
                    <span class="breadcrumb row">
                        <a href="<?php echo $this->url('hang_hoa/crud',array('action'=>'index'));?>">/ Kho</a>                        
                        <a href="<?php echo $this->url('hang_hoa/crud',array('action'=>'hangHoa'));?>">/ Hàng hóa</a>
                         / Xuất hàng /
                    </span>
                    <ul class="nav h5a-sidenav nav-list accordion">                        
                        <li>
                            <a href="<?php echo $this->url('hang_hoa/crud',array('action'=>'hangHoa'));?>">
                                <i class="fa fa-cubes"></i> Danh sách hàng
                            </a>
                        </li>
                        <li>
                            <a href="<?php echo $this->url('hang_hoa/crud',array('action'=>'nhapHang'));?>">
                                <i class="fa fa-download"></i> Nhập hàng
                            </a>
                        </li>
                        <li>
                            <a href="<?php echo $this->url('hang_hoa/crud',array('action'=>'xuatHang'));?>">
                                <i class="fa fa-upload"></i> Xuất hàng
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
            <div class="col-md-10" role="main">
                <div class="h5a-docs-section">
                    <div class="page-header">
                        <div class="row">
                            <div class="col-sm-6">
                                <h1>Xuất hàng</h1>
                            </div>
                           
                        </div>
                    </div>                    
                        <div class="col-sm-6">
                            <div class="form-group">
                                <label class="col-sm-4 right" for="form-field-3">Khách hàng</label>
                                <div class="col-sm-7">
                                    <!--<input type="text" id="form-field-3" class="h5a-input form-control input-sm" value="Trường Đại học Trà Vinh">-->
                                <?php
                                    $hoaDon = $form->get('hoa-don');
                                    echo $this->formHidden($form->get('idKhachHang'));
                                    echo $this->formHidden($form->get('idSanPham'));
                                    echo $this->formHidden($form->get('donViTinh'));
                                    echo $this->formRow($form->get('khachHang'));
                                    echo $this->formHidden($hoaDon->get('idDoiTac')->get('idDoiTac'));
                                    //echo $this->formCollection($hoaDon->get('ctHoaDon'));
                                ?>
                                <input type='hidden' name="" />
                                <div id="search-result"></div>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-sm-4 right" for="form-field-4">Địa chỉ</label>
                                <div class="col-sm-7">
                                    <!--<input type="text" id="form-field-4" class="h5a-input form-control input-sm" value="Số 126 Quốc lộ 53, khóm 4, phường 5, Tp.Trà Vinh, tỉnh Trà Vinh">-->
                                <?php
                                    echo $this->formRow($form->get('diaChi'));
                                ?>
                                </div>
                            </div>
                        </div>
                        <div class="col-sm-6 box">
                            <div class="form-group">
                                <label class="col-sm-4 right" for="form-field-1">Mã hàng</label>
                                <div class="col-sm-7">
                                    <!--<input type="text" id="form-field-1" placeholder="Mã hàng" class="h5a-input form-control input-sm">-->
                                <?php
                                    echo $this->formRow($form->get('maHang'));
                                ?>
                                <div id="san-pham-search-result"></div>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-sm-4 right" for="form-field-2">Tên hàng</label>
                                <div class="col-sm-7">
                                    <!--<input type="text" id="form-field-2" placeholder="Tên hàng" class="h5a-input form-control input-sm">-->
                                <?php
                                    echo $this->formRow($form->get('tenHang'));
                                ?>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-sm-4 right" for="form-field-3">Số lượng</label>
                                <div class="col-sm-7">
                                    <!--<input type="text" id="form-field-3" class="h5a-input form-control input-sm" value="120">-->
                                <?php
                                    echo $this->formRow($form->get('soLuong'));
                                ?>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-sm-4 right" for="form-field-4">Giá xuất</label>
                                <div class="col-sm-7">
                                    <!--<input type="text" id="form-field-4" class="h5a-input form-control input-sm" value="325.000">-->
                                <?php
                                    echo $this->formRow($form->get('giaXuat'));
                                ?>
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="col-sm-10 col-sm-offset-1">
                                    <button id="btnThemHang" class="btn h5a-btn btn-primary full">Thêm vào đơn hàng</button>
                                </div>
                            </div>
                        </div>
                </div>
            </div>
        </div>
</div>
<php echo $this->form()->closeTag(); ?>
<div class="container h5a-container">
        <div class="row">
            <div class="col-md-2">

            </div>
            <div class="col-md-10">
                <h1>Danh sách xuất</h1>
                <div class="box">
                    <table id="tbXuatHang" class="invoice pricelist bottom20">
                        <thead>
                            <tr>
                                <th>Sản phẩm</th>
                                <th>Đơn vị tính</th>
                                <th>Số lượng</th>
                                <th>Giá xuất</th>
                            </tr>
                        </thead>
                        <tbody>
                        </tbody>
                    </table>
                    <div class="row">
                        <div class="col-sm-3">
                            <button class="btn h5a-btn btn-danger full"><i class="fa fa-times"></i> Hủy đơn hàng</button>
                        </div>
                        <div class="col-sm-3 pull-right">
                            <button type="submit" class="btn h5a-btn btn-primary full"><i class="fa fa-print"></i> In đơn hàng</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
</div>
    
    <!-- jQuery -->
    <script src="<?php echo $this->basePath();?>/js/jquery.js"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="<?php echo $this->basePath();?>/js/bootstrap.min.js"></script>

    <!-- DataTables JavaScript -->
    <script src="<?php echo $this->basePath();?>/js/plugins/dataTables/jquery.dataTables.js"></script>
    <!-- Page-Level Demo Scripts - Tables - Use for reference -->
    <script>
    $(document).ready(function() {
        $('#dataTables-example').dataTable({
            "pagingType": "simple",
            "bPaginate": true,
            "bLengthChange": true,
            "bFilter": true,
            "bInfo": true,
            "bAutoWidth": true
        });

        $('#btnThemHang').click(function(){
            var idKhachhang=$('#idKhachhang').val();
            var tenKhachHang=$('#tenKhachHang').val();
            var idSanPham=$('#idSanPham').val();
            var tenHang=$('#tenHang').val();
            var donViTinh=$('#donViTinh').val();
            var soLuong=$('#soLuong').val(); 
            var giaXuat=$('#giaXuat').val();   

            var soDong = $('#tbXuatHang > tbody > tr').length;      

            var template = '<tr class="price">'+
                '<td>'+tenHang+'</td>'+
                '<td>'+donViTinh+'</td>'+
                '<td>'+
                    '<input type="hidden" name="hoa-don&#x5B;ctHoaDon&#x5D;&#x5B;__index__&#x5D;&#x5B;idSanPham&#x5D;&#x5B;idSanPham&#x5D;" value="'+idSanPham+'">'+
                    '<input type="hidden" name="hoa-don&#x5B;ctHoaDon&#x5D;&#x5B;__index__&#x5D;&#x5B;soLuong&#x5D;" value="'+soLuong+'">'+
                    '<span>'+soLuong+'</span>'+
                '</td>'+
                '<td>'+
                    '<input type="hidden" name="hoa-don&#x5B;ctHoaDon&#x5D;&#x5B;__index__&#x5D;&#x5B;gia&#x5D;" value="'+giaXuat+'">'+
                    '<span>'+giaXuat+'</span>'+
                '</td>'+
                '</tr>';

                $('input[name="hoa-don[idDoiTac][idDoiTac]"]').val(idKhachhang);


            template = template.replace(/__index__/g, soDong);
            $('#tbXuatHang tbody').append(template);
            return false;
        });

        var xhr;
//Hiển thị, chọn khách hàng
        $('#tenKhachHang').keyup(function(){
            var tenKhachHang=$(this).val();

            if(xhr && xhr.readyState != 4){
                xhr.abort(); //huy lenh ajax truoc do
            }

            xhr = $.ajax({
                url:'<?php echo $this->url('hang_hoa/crud', array('action'=>'searchKhachHang')); ?>',
                type:'POST',
                dataType:'json',
                data:{
                    'tenKhachHang':tenKhachHang
                },
                success:function(data){
                    $.each(data, function(key,val){
                        $('#search-result').empty(); //lam rong khung ket qua

                        var pos = $('#tenKhachHang').position(); //lấy tọa độ của ô tên khách hàng
                        $('#search-result').css({
                            position:'absolute',
                            top:pos.top + 35,
                            left:pos.left,
                            'z-index': 100 // đặt search-result lên layout ngoài nhất
                        });
                        $.each(data, function(key, val){
                            $('#search-result').append('<div class="list-group-item"><span class="hide">'+val.idKhachHang+'</span><span>'+val.tenKhachHang+'</span><span class="hide">'+val.diaChiKhachHang+'</span></div>'); // thêm một dòng vào search result, mỗi một dòng là 1 khách hàng
                        })
                    });
                }
            });
            return false;
        });

        $('#search-result').on('click', '.list-group-item', function(){

            var id = $(this).find('span:eq(0)').text(); 
            var ten = $(this).find('span:eq(1)').text();
            var diaChi = $(this).find('span:eq(2)').text();

            $('#idKhachhang').val(id);
            $('#tenKhachHang').val(ten);
            $('#diaChiKhachHang').val(diaChi);

            $('#search-result').empty();
        });
//./Hiển thị, chọn khách hàng

//Hiển thị, chọn sản phẩm
        $('#maHang').keyup(function(){
            var maHang=$(this).val();            
            if(xhr && xhr.readyState != 4){
                xhr.abort(); //huy lenh ajax truoc do
            }

            xhr = $.ajax({
                url:'<?php echo $this->url('hang_hoa/crud', array('action'=>'searchSanPham')); ?>',
                type:'POST',
                dataType:'json',
                data:{
                    'maHang':maHang
                },
                success:function(data){
                    $.each(data, function(key,val){
                        $('#san-pham-search-result').empty(); //lam rong khung ket qua

                        var pos = $('#maHang').position(); //lấy tọa độ của ô tên sản phẩm
                        $('#san-pham-search-result').css({
                            position:'absolute',
                            top:pos.top + 35,
                            left:pos.left,
                            'z-index': 100 // đặt search-result lên layout ngoài nhất
                        });

                        $.each(data, function(key, val){
                            $('#san-pham-search-result').append('<div class="list-group-item"><span class="hide">'+val.idSanPham+'</span><span class="hide">'+val.tenSanPham+'</span><span>'+val.maHang+'</span><span class="hide">'+val.giaXuat+'</span><span class="hide">'+val.donViTinh+'</span></div>'); // thêm một dòng vào search result, mỗi một dòng là 1 sản phẩm
                        })
                    });
                }
            });
            return false;
        });

        $('#san-pham-search-result').on('click', '.list-group-item', function(){
            var id = $(this).find('span:eq(0)').text();
            var ten = $(this).find('span:eq(1)').text();
            var ma = $(this).find('span:eq(2)').text();
            var giaXuat = $(this).find('span:eq(3)').text();
            var donViTinh = $(this).find('span:eq(4)').text();

            $('#idSanPham').val(id);
            $('#maHang').val(ma);
            $('#tenHang').val(ten);
            $('#giaXuat').val(giaXuat);
            $('#donViTinh').val(donViTinh);

            $('#san-pham-search-result').empty();
        });
    });
//./Hiển thị, chọn sản phẩm
    </script>