<?php
$title = 'Xuất hàng';
$this->headTitle($title);
 $form->setAttribute('action', $this->url('hang_hoa/crud', array('action' => 'xuat-hang')));
 $form->setAttribute('role','form');
 $form->setAttribute('id','formXuatHang');
 $form->setAttribute('class','form-horizontal');
 $form->prepare();
 echo $this->form()->openTag($form);
 echo '<span id="tenHienThi" hidden="false">'.$this->zfcUserIdentity()->getHoTen().'</span>';

 $datetime = new DateTime(null, new DateTimeZone('Asia/Ho_Chi_Minh')); 
 $y=$datetime->format('Y');          
 $m=$datetime->format('m');
 $d=$datetime->format('d'); 
?>

<style type="text/css">
    #san-pham-search-result{ cursor:pointer;}
    #search-result{cursor:pointer;}
    @media print {        
        .table{width: 790px; font-size: 13px; margin-top: -60px}
        .tb{width: 97%;}
        .td{width: 90px;}  
        table td{padding: 5px;}      
                
        .row{display: none;}
        .h5a-container{display: none;}
        .tbIn{display: block;}
        #formNhapHang{display: none;}
    }
    
</style>
<!-- In -->
<div  class="tbIn" hidden="true">
    <table class="table">
        <tr style="text-align: -moz-center; border-style:hidden">
            <td>
                <table border="0" class="tb">
                    <tr>
                        <td style="width:60%">
                            <b>
                                CTY CP SÁCH &amp; TB TRƯỜNG HỌC TRÀ VINH</br>
                                3A Trưng Nữ Vương Phường 1 TP.Trà Vinh</br>
                                Mã số thuế: 2100 290 521
                            </b>
                        </td>
                        <td style="text-align:center">
                            <b>Mẫ số: 02 - TT</b></br>
                            (Ban hành theo QĐ số: 15/2006/QĐ-BTC ngày 20/3/2006 của Bộ trưởng BTC)
                        </td>            
                    </tr>
                </table>

                <table border="0" style="width:65%; margin-left:220px"  class="tb">
                    <tr>
                        <td style="width:50%; padding:0px 0px 0px 30px; font-size:16px; font-weight:bold">PHIẾU XUẤT KHO</td>
                        <td></td>
                    </tr>
                    <tr>
                        <td style="padding:0px;">Ngày <?php echo $d;?> tháng <?php echo $m;?> năm <?php echo $y;?></td>
                        <td style="padding:0px;">
                            Nợ: ........................................
                        </td>
                    </tr>
                    <tr>
                        <td style="padding:0px;">
                            Số: ........................................
                        </td>
                        <td style="padding:0px;">
                            Có: ........................................
                        </td>
                    </tr>
                </table>

                <table border="0"  class="tb">
                    <tr>
                        <td colspan="4">- Họ và tên người nhận hàng:....................................................Địa chỉ (bộ phận)..................................................
                        </td>
                    </tr>
                    <tr>
                        <td style="width:200px">
                            - Theo.....................
                        </td>
                        <td style="width:100px">
                            số....................
                        </td>
                        <td style="width:215px">
                            ngày........tháng........năm 20....
                        </td>
                        <td>                            
                            của...............................................
                        </td>
                    </tr>
                    <tr>
                        <td colspan="2">                        
                            Xuất tại kho:........................................
                        </td>                    
                        <td colspan="2">                            
                            Địa điểm..........................................................................................
                        </td>
                    </tr>
                    <tr><td></td></tr>
                </table>

                <table border="1" id="tbSanPham">
                    <tr style="text-align:center">
                        <td rowspan="2" style="width:45px">STT</td>
                        <td rowspan="2">Tên, nhãn hiệu quy cách, phẩm chất vật tư, dụng cụ sản phẩm, hàng hóa</td>
                        <td rowspan="2" class="td">Mã số</td>
                        <td rowspan="2" class="td">Đơn vị tính</td>
                        <td colspan="2" style="width:300px">Số lượng</td>
                        <td rowspan="2" class="td">Đơn giá</td>
                        <td rowspan="2" class="td">Thành tiền</br>(vnđ)</td>
                    </tr>
                    <tr style="text-align:center">
                        <td>Theo chứng từ</td>
                        <td>Thực xuất</td>
                    </tr>
                    <tr style="text-align:center">
                        <td>A</td>
                        <td>B</td>
                        <td>C</td>
                        <td>D</td>
                        <td>1</td>
                        <td>2</td>
                        <td>3</td>
                        <td>4</td>
                    </tr>                    
                </table>
            </td>
        </tr>
        <tr style="border-style:hidden">
            <td style="padding-left:20px">- Tổng số tiền (viết bằng chữ): <span id="tongSoTien"></span>&nbsp;đồng</td>
        </tr>
        <tr style="border-style:hidden">
            <td style="padding-left:20px">
                - Số chứng từ gốc kèm theo: .....................................................................................................................................
            </td>
        </tr>
        <tr style="text-align: -moz-center">
            <td>
                <table border="0" class="tb" style="width:100%;">
                    <tr>
                        <td colspan="5" style="text-align:right">Ngày <?php echo $d;?> tháng <?php echo $m;?> năm <?php echo $y;?></td>
                    </tr>
                    <tr style="text-align: center;">
                        <td>
                            Người lập phiếu</br>(Ký, họ tên)
                        </td>
                        <td>
                            Người nhận hàng</br>(Ký, họ tên)
                        </td>
                        <td>
                            Thủ kho</br>(Ký, họ tên)
                        </td>
                        <td>
                            Kế toán trưởng</br>(Ký, họ tên)
                        </td>
                        <td>
                            Giám đốc</br>(Ký, họ tên)
                        </td>
                    </tr>
                    <tr>
                        <td style="height:100px"></td>
                    </tr>                    
                </table>
            </td>
        </tr>
    </table>
</div>
<!-- In-->

<div class="row">
    <div class="col-md-2">
        <div class="h5a-sidebar affix">
            <span class="breadcrumb row">
                <a href="<?php echo $this->url('hang_hoa/crud',array('action'=>'index'));?>">/ Kho</a>                        
                <a href="<?php echo $this->url('hang_hoa/crud',array('action'=>'hang-hoa'));?>">/ Hàng hóa</a>
                 / Xuất hàng /
            </span>
            <ul class="nav h5a-sidenav nav-list accordion">                        
                <li>
                    <a href="<?php echo $this->url('hang_hoa/crud',array('action'=>'hang-hoa'));?>">
                        <i class="fa fa-cubes"></i> Danh sách hàng
                    </a>
                </li>
                <li>
                    <a href="<?php echo $this->url('hang_hoa/crud',array('action'=>'nhap-hang'));?>">
                        <i class="fa fa-download"></i> Nhập hàng
                    </a>
                </li>
                <li>
                    <a href="<?php echo $this->url('hang_hoa/crud',array('action'=>'xuat-hang'));?>">
                        <i class="fa fa-upload"></i> Xuất hàng
                    </a>
                </li>
            </ul>
        </div>
    </div>

    <div class="col-md-10" role="main">
        <div class="h5a-docs-section">
            <div class="page-header">
                <div class="row">
                    <div class="col-sm-6">
                        <h1>Xuất hàng</h1>
                    </div>                  
                </div>
                <?php
                    $flash=$this->flashMessenger();
                    $flash->setMessageOpenFormat('<div%s>
                     <button type="button" id="btFm" class="close" data-dismiss="alert" aria-hidden="true">
                         &times;
                     </button>
                     <ul><li>')
                     ->setMessageSeparatorString('</li><li>')
                     ->setMessageCloseString('</li></ul></div>');

                     $error=$flash->render('error',   array('alert', 'alert-dismissable', 'alert-danger'));
                     echo $error;

                     $info=$flash->render('info',    array('alert', 'alert-dismissable', 'alert-info'));
                     echo $info;

                     $default=$flash->render('default', array('alert', 'alert-dismissable', 'alert-warning'));
                     echo $default;

                     $success=$flash->render('success', array('alert', 'alert-dismissable', 'alert-success'));
                     echo $success;                     
                    if($error||$success||$info||$default)
                    {
                        echo '
                        <script type="text/javascript">
                            setTimeout(function(){
                                document.getElementById("btFm").click();
                            },5000);
                        </script>';                        
                    }
                ?>
            </div>

            <div class="col-sm-6">
                    <div class="form-group">
                        <label class="col-sm-4 right" for="form-field-3">Khách hàng</label>
                        <div class="col-sm-7">
                            <!--<input type="text" id="form-field-3" class="h5a-input form-control input-sm" value="Trường Đại học Trà Vinh">-->
                        <?php
                            $hoaDon = $form->get('hoa-don');
                            echo $this->formHidden($form->get('idKhachHang'));
                            echo $this->formHidden($form->get('idSanPham'));
                            echo $this->formHidden($form->get('donViTinh'));
                            echo $this->formRow($form->get('khachHang'));
                            echo $this->formHidden($hoaDon->get('idDoiTac')->get('idDoiTac'));
                            echo $this->formHidden($hoaDon->get('status'));
                            //echo $this->formCollection($hoaDon->get('ctHoaDons'));
                        ?>
                        <input type='hidden' name="" />
                        <div id="search-result"></div>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-4 right" for="form-field-4">Địa chỉ</label>
                        <div class="col-sm-7">
                            <!--<input type="text" id="form-field-4" class="h5a-input form-control input-sm" value="Số 126 Quốc lộ 53, khóm 4, phường 5, Tp.Trà Vinh, tỉnh Trà Vinh">-->
                        <?php
                            echo $this->formRow($form->get('diaChi'));
                        ?>
                        </div>
                    </div>
            </div>

            <div class="col-sm-6 box">
                    <div class="form-group">
                        <label class="col-sm-4 right" for="form-field-1">Mã sản phẩm</label>
                        <div class="col-sm-7">
                            <!--<input type="text" id="form-field-1" placeholder="Mã hàng" class="h5a-input form-control input-sm">-->
                        <?php
                            $form->get('maHang')->setAttribute('disabled','true');
                            echo $this->formRow($form->get('maHang'));                            
                        ?>
                        <div id="san-pham-search-result"></div>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-4 right" for="form-field-1">Mã vạch</label>
                        <div class="col-sm-7">
                        <?php
                            $form->get('maVach')->setAttribute('disabled','true');
                            echo $this->formRow($form->get('maVach'));
                        ?>
                        <div id="ma-vach-search-result"></div>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-4 right" for="form-field-2">Tên hàng</label>
                        <div class="col-sm-7">
                            <!--<input type="text" id="form-field-2" placeholder="Tên hàng" class="h5a-input form-control input-sm">-->
                        <?php
                            $form->get('tenHang')->setAttribute('disabled','true');
                            echo $this->formRow($form->get('tenHang'));
                        ?>
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="col-sm-4 right" for="form-field-3">Số lượng</label>
                        <div class="col-sm-7">
                            <!--<input type="text" id="form-field-3" class="h5a-input form-control input-sm" value="120">-->
                        <?php
                            $form->get('soLuong')->setAttribute('disabled','true');
                            echo $this->formRow($form->get('soLuong'));
                        ?>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-4 right" for="form-field-4">Giá xuất</label>
                        <div class="col-sm-7">
                            <!--<input type="text" id="form-field-4" class="h5a-input form-control input-sm" value="325.000">-->
                        <?php
                            $form->get('giaXuat')->setAttribute('disabled','true');
                            echo $this->formRow($form->get('giaXuat'));
                        ?>
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-sm-10 col-sm-offset-1">
                            <input type="hidden" id="tonKho"/>
                            <input type="hidden" id="kenhPhanPhoi" value=""/>
                            <input type="hidden" id="giaXuat" value=""/>
                            <button id="btnThemHang" class="btn h5a-btn btn-primary full">Thêm vào đơn hàng</button>
                        </div>
                    </div>
            </div>
        </div>
    </div>
</div>
<div id="h5a-container" class="h5a-container"></div>
<div class="row">
    <div class="col-md-2"></div>
    <div class="col-md-10">        
        <h1>Danh sách xuất</h1>
       
        <div class="box">
            <table id="tbXuatHang" class="invoice pricelist bottom20">
                <thead>
                    <tr>
                        <th>Sản phẩm</th>
                        <th>Đơn vị tính</th>
                        <th>Số lượng</th>
                        <th>Giá xuất</th>
                        <th class="an" id="btnHuy">Hủy</th>
                    </tr>
                </thead>
                <tbody>
                </tbody>
            </table>
            <div class="row">
                <div class="col-sm-3">
                    <a href="<?php echo $this->url('hang_hoa/crud',array('action'=>'xuat-hang'));?>"><button type="button" class="btn h5a-btn btn-danger full"  onclick="return xacNhanHuy()"><i class="fa fa-times"></i> Hủy đơn hàng</button></a>
                </div>
                <div class="col-sm-3 pull-right">
                    <button type="submit" class="btn h5a-btn btn-primary full" onclick="return inDonHangFunction();"><i class="fa fa-print"></i> In đơn hàng</button>
                </div>
            </div>
        </div>
    </div>
</div>
    
<!-- </div> -->
<?php echo $this->form()->closeTag(); ?>

    <!-- FormatNumber -->
    <script src="<?php echo $this->basePath();?>/js/formatnumber.js"></script>

    <!-- convernumbertostring -->
    <script src="<?php echo $this->basePath();?>/js/convernumbertostring.js"></script>

    <!-- jQuery -->
    <script src="<?php echo $this->basePath();?>/js/jquery.js"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="<?php echo $this->basePath();?>/js/bootstrap.min.js"></script>

    <!-- DataTables JavaScript -->
    <script src="<?php echo $this->basePath();?>/js/plugins/dataTables/jquery.dataTables.js"></script>
    <!-- Page-Level Demo Scripts - Tables - Use for reference -->
    <script>

    $(document).ready(function(){
        $('#dataTables-example').dataTable({
            "pagingType": "simple",
            "bPaginate": true,
            "bLengthChange": true,
            "bFilter": true,
            "bInfo": true,
            "bAutoWidth": true
        });

        $('#btnThemHang').click(function(){
            var idKhachhang=$('#idKhachhang').val();
            var tenKhachHang=$('#tenKhachHang').val();
            var diaChi=$('#diaChiKhachHang').val();
            var idSanPham=$('#idSanPham').val();
            var maSanPham=$('#maHang').val();
            var tenHang=$('#tenHang').val();
            var donViTinh=$('#donViTinh').val();
            var soLuong=$('#soLuong').val(); 
            var giaXuat=$('#giaXuat').val();   
            var tonKho=$('#tonKho').val(); 
            var soDong = $('#tbXuatHang > tbody > tr').length; 
            if(soDong>0)
            {
                for(var i=0; i<soDong; i++)
                {
                    var id='#soDong'+i;
                    var idSP=$(id).val();
                    if(idSanPham==idSP)
                    {
                        alert('Sản phẩm đã được thêm rồi. Vui lòng kiểm tra lại!');
                        return false;
                    }
                }

            }
            

            if(idKhachhang==''||tenKhachHang==''||diaChi==''||idSanPham==''||tenHang==''||donViTinh==''||soLuong==''||giaXuat==''||tonKho==''||idKhachhang==null||tenKhachHang==null||diaChi==null||idSanPham==null||tenHang==null||donViTinh==null||soLuong==null||giaXuat==null||tonKho==null)
            {
                alert('Vui lòng điền đầy đủ thông tin');
                return false;
            }
            if(parseInt(tonKho)<parseInt(soLuong)||parseInt(soLuong)==0||parseInt(tonKho)==0)
            {
                
                if(parseInt(tonKho)==0)
                {
                    alert('Số lượng sản phẩm trong kho đã hết, Vui lòng kiểm tra lại!');
                    return false;
                }
                if(parseInt(soLuong)==0)
                {
                    alert('Vui lòng nhập số lượng!');
                    return false;
                }
                if(parseInt(tonKho)<parseInt(soLuong))
                {
                    alert('Tồn kho: '+tonKho+' < Số lượng đã nhập: '+soLuong);
                    return false;
                }
                
                
            }
            else
            {
                var soDong = $('#tbXuatHang > tbody > tr').length;   

                var template = '<tr class="price">'+
                    '<td>'+tenHang+'</td>'+
                    '<td>'+donViTinh+'</td>'+
                    '<td>'+
                        '<span hidden="true" class="maSanPham">'+maSanPham+'</span>'+
                        '<input type="hidden" id="soDong'+soDong+'" name="hoa-don&#x5B;ctHoaDons&#x5D;&#x5B;__index__&#x5D;&#x5B;idSanPham&#x5D;&#x5B;idSanPham&#x5D;" value="'+idSanPham+'">'+
                        '<input type="hidden" name="hoa-don&#x5B;ctHoaDons&#x5D;&#x5B;__index__&#x5D;&#x5B;soLuong&#x5D;" value="'+soLuong+'">'+
                        '<span class="soLuong">'+soLuong+'</span>'+
                    '</td>'+
                    '<td>'+
                        '<input type="hidden" name="hoa-don&#x5B;ctHoaDons&#x5D;&#x5B;__index__&#x5D;&#x5B;gia&#x5D;" value="'+giaXuat+'">'+
                        '<span class="giaXuat">'+giaXuat+'</span>'+
                    '</td>'+
                    '<td class="an" style="text-align:left;">'+
                        '<a class="btnHuy"><img src="<?php echo $this->basePath(); ?>/img/delete.png" width="30px" height="30px"></a>'+
                    '</td>'+
                    '</tr>';

                    $('input[name="hoa-don[idDoiTac][idDoiTac]"]').val(idKhachhang);
                template = template.replace(/__index__/g, soDong);
                $('#tbXuatHang tbody').append(template);                
            }
            
            return false;
        });

        var xhr;
        var xhr1;
        //Hiển thị, chọn khách hàng
            $('#tenKhachHang').keyup(function(){
                var tenKhachHang=$(this).val();
                if(tenKhachHang==''||tenKhachHang==null){
                    $('#maHang').prop('disabled',true);
                    $('#tenHang').prop('disabled',true);
                    $('#maVach').prop('disabled',true);
                    $('#soLuong').prop('disabled',true);
                    $('#giaXuat').prop('disabled',true);
                    $('#tbXuatHang > tbody > tr').remove();
                }

                if(xhr && xhr.readyState != 4){
                    xhr.abort(); //huy lenh ajax truoc do
                }

                xhr = $.ajax({
                    url:'<?php echo $this->url('hang_hoa/crud', array('action'=>'searchKhachHang')); ?>',
                    type:'POST',
                    dataType:'json',
                    data:{
                        'tenKhachHang':tenKhachHang
                    },
                    success:function(data){
                        $.each(data, function(key,val){
                            $('#search-result').empty(); //lam rong khung ket qua

                            var pos = $('#tenKhachHang').position(); //lấy tọa độ của ô tên khách hàng
                            $('#search-result').css({
                                position:'absolute',
                                top:pos.top + 35,
                                left:pos.left,
                                'z-index': 100 // đặt search-result lên layout ngoài nhất
                            });
                            $.each(data, function(key, val){
                                $('#search-result').append('<div class="list-group-item"><span class="hide">'+val.idKhachHang+'</span><span>'+val.tenKhachHang+'</span><span class="hide">'+val.diaChiKhachHang+'</span><span class="hide">'+val.kenhPhanPhoi+'</span></div>'); // thêm một dòng vào search result, mỗi một dòng là 1 khách hàng
                            })
                        });
                    }
                });
                return false;
            });

            $('#search-result').on('click', '.list-group-item', function(){

                $('#tbXuatHang > tbody > tr').remove();
                var id = $(this).find('span:eq(0)').text(); 
                var ten = $(this).find('span:eq(1)').text();
                var diaChi = $(this).find('span:eq(2)').text();
                var kenhPhanPhoi=$(this).find('span:eq(3)').text();

                $('#idKhachhang').val(id);
                $('#tenKhachHang').val(ten);
                $('#diaChiKhachHang').val(diaChi);
                $('#kenhPhanPhoi').val(kenhPhanPhoi);

                $('#search-result').empty();
                var tenKhachHang=$('#tenKhachHang').val();
                if(tenKhachHang){
                    $('#maHang').prop('disabled',false);
                    $('#tenHang').prop('disabled',false);
                    $('#maVach').prop('disabled',false);
                    $('#soLuong').prop('disabled',false);
                    $('#giaXuat').prop('disabled',false);
                }
            });
        //./Hiển thị, chọn khách hàng

        //Hiển thị, chọn sản phẩm
            $('#maHang').keyup(function(){
                var maHang=$(this).val();            
                if(xhr1 && xhr1.readyState != 4){
                    xhr1.abort(); //huy lenh ajax truoc do
                }

                xhr1 = $.ajax({
                    url:'<?php echo $this->url('hang_hoa/crud', array('action'=>'searchSanPham')); ?>',
                    type:'POST',
                    dataType:'json',
                    data:{
                        'maHang':maHang
                    },
                    success:function(data){
                        $('#san-pham-search-result').empty(); //lam rong khung ket qua        
                        $('#ma-vach-search-result').empty();

                        var pos = $('#maHang').position(); //lấy tọa độ của ô tên sản phẩm
                        $('#san-pham-search-result').css({
                            position:'absolute',
                            top:pos.top + 35,
                            left:pos.left,
                            'z-index': 100 // đặt search-result lên layout ngoài nhất
                        });
                        $.each(data, function(key,val){
                                var gx='';
                                //alert(val.giaXuat[39]);
                                
                                $.each(val.giaXuat, function(k, v)
                                {
                                    if($('#kenhPhanPhoi').val()==k)
                                    {
                                        gx+='<span class="hide">'+v+'</span>';
                                    }
                                    
                                });

                                $('#san-pham-search-result').append('<div class="list-group-item"><span class="hide">'+val.idSanPham+'</span><span class="hide">'+val.tenSanPham+'</span><span>'+val.maHang+'</span><span class="hide">'+val.donViTinh+'</span><span class="hide">'+val.tonKho+'</span>'+gx+'<span class="hide">'+val.maVach+'</span></div>'); // thêm một dòng vào search result, mỗi một dòng là 1 sản phẩm
                            
                        });
                    }
                });
                return false;
            });

            $('#san-pham-search-result').on('click', '.list-group-item', function(){
                var id = $(this).find('span:eq(0)').text();
                var ten = $(this).find('span:eq(1)').text();
                var ma = $(this).find('span:eq(2)').text();          
                var donViTinh = $(this).find('span:eq(3)').text();
                var tonKho = $(this).find('span:eq(4)').text();// tồn kho trong cơ sở dữ liệu
                
                var giaXuat= $(this).find('span:eq(5)').text(); 
                var maVach= $(this).find('span:eq(6)').text(); 
                

                $('#idSanPham').val(id);
                $('#maHang').val(ma);
                $('#maVach').val(maVach);
                $('#tenHang').val(ten);
                $('#giaXuat').val(giaXuat);
                $('#donViTinh').val(donViTinh);
                $('#tonKho').val(tonKho);
                $('#soLuong').val(tonKho);


                $('#san-pham-search-result').empty();            
                $('#ma-vach-search-result').empty();
            });

            // Khi gõ vào mã vạch
        var xhrMaVach;
        $('#maVach').keyup(function(){
            var maVach=$(this).val();
            if(maVach){
                if(xhrMaVach && xhrMaVach.readyState != 4){
                    xhrMaVach.abort(); //huy lenh ajax truoc do
                }
                xhrMaVach = $.ajax({
                    url:'<?php echo $this->url('hang_hoa/crud', array('action'=>'search-san-pham-theo-ma-vach')); ?>',
                    type:'POST',
                    dataType:'json',
                    data:{
                        'maVach':maVach
                    },
                    success:function(data){     

                        $.each(data, function(key,val){
                            $('#ma-vach-search-result').empty(); //lam rong khung ket qua
                            $('#san-pham-search-result').empty();

                            var pos = $('#maVach').position(); //lấy tọa độ của ô mã sản phẩm
                            $('#ma-vach-search-result').css({
                                position:'absolute',
                                top:pos.top + 35,
                                left:pos.left,
                                'z-index': 100 // đặt search-result lên layout ngoài nhất
                            });

                            $.each(data, function(key,val){
                                var gx='';
                                //alert(val.giaXuat[39]);
                                
                                $.each(val.giaXuat, function(k, v)
                                {
                                    if($('#kenhPhanPhoi').val()==k)
                                    {
                                        gx+='<span class="hide">'+v+'</span>';
                                    }
                                    
                                });

                                $('#ma-vach-search-result').append('<div class="list-group-item"><span class="hide">'+val.idSanPham+'</span><span class="hide">'+val.tenSanPham+'</span><span>'+val.maHang+'</span><span class="hide">'+val.donViTinh+'</span><span class="hide">'+val.tonKho+'</span>'+gx+'<span class="hide">'+val.maVach+'</span><span >('+val.maVach+')</span></div>'); // thêm một dòng vào search result, mỗi một dòng là 1 sản phẩm
                            });
                        });
                    }
                });

            }
            else{//ngược lại mã vạch == null
                $('#ma-vach-search-result').empty();
            }
        });
        
        $('#ma-vach-search-result').on('click', '.list-group-item', function(){
            var id = $(this).find('span:eq(0)').text();
                var ten = $(this).find('span:eq(1)').text();
                var ma = $(this).find('span:eq(2)').text();          
                var donViTinh = $(this).find('span:eq(3)').text();
                var tonKho = $(this).find('span:eq(4)').text();// tồn kho trong cơ sở dữ liệu                
                var giaXuat= $(this).find('span:eq(5)').text(); 
                var maVach= $(this).find('span:eq(6)').text(); 

                $('#idSanPham').val(id);
                $('#maHang').val(ma);
                $('#maVach').val(maVach);
                $('#tenHang').val(ten);
                $('#giaXuat').val(giaXuat);
                $('#donViTinh').val(donViTinh);
                $('#tonKho').val(tonKho);
                $('#soLuong').val(tonKho);


                $('#san-pham-search-result').empty();            
                $('#ma-vach-search-result').empty();
        });
        
    });

    </script>

    <script>
        inDonHangFunction=function()
        {

            var soDong = $('#tbXuatHang > tbody > tr').length; 
            if(soDong==0)
            {
                alert('Xin lỗi bạn chưa nhập sản phẩm...');
                return false;
            }
            else
            {
                var soLuong=new Array();
                var donGia=new Array();                
                var maSanPham=new Array();
                var thanhTien=new Array();
                var i=1;
                var j=1;
                var k=1;
                var sL=0;
                var gX=0;
                var maSP='';
                var tongTien=0;

                var sD = $('#tbSanPham > tbody > tr').length;
                var temp = '<tr class="price">';                
                $("#tbXuatHang tbody tr").each(function()
                {
                    var timSoLuong=$(this).find(".soLuong");
                    var timGiaXuat=$(this).find(".giaXuat");
                    var timMaSanPham=$(this).find(".maSanPham");
                    timSoLuong.each(function(){                        
                        sL=parseInt($(this).html());                        
                    });
                    timGiaXuat.each(function(){
                        gX=parseInt($(this).html());                        
                    });
                    timMaSanPham.each(function(){                        
                        maSP=$(this).html();                        
                    });
                    soLuong[k]=sL;
                    donGia[k]=gX;
                    thanhTien[k]=sL*gX;
                    maSanPham[k]=maSP;
                    //alert(maSanPham[k].toString());
                    k++;
                });
                //------------------------------------------------
                $("#tbXuatHang tbody tr td").each(function()
                {
                    var t=$(this).html();
                    var c= parseInt(i%5);
                    if(c==1)
                    {
                        temp = temp +'<td style="text-align: center;">'+j+'</td>';
                    }                   
                    if(c!=0)                    
                    {
                        if(c==2||c==3||c==4)
                        {                            
                             if(c==2)
                             {
                                temp= temp+
                                '<td style="text-align: right;">'+$(this).html()+'</td>';
                             }
                             if(c==3)
                             {
                                temp= temp+
                                '<td style="text-align: right;">'+formatNumber(soLuong[j])+'</td>';
                             }
                             if(c==4)
                             {
                                temp= temp+
                                '<td style="text-align: right;">'+formatNumber(donGia[j])+'</td>';
                             }                             
                        }
                        else
                        {
                            temp= temp+
                             '<td>'+$(this).html()+'</td>';
                        }

                        if(c==1)
                        {
                            temp=temp+
                            '<td style="text-align: right;">'+maSanPham[j]+'</td>';
                        }
                        if(c==2)
                        {
                            temp=temp+'<td></td>';
                        }                            
                        if(c==4)
                        {
                            temp=temp+'<td style="text-align: right;"><span class="thanhTien">'+formatNumber(thanhTien[j])+'</span</td>';
                            tongTien=tongTien+parseInt(thanhTien[j]);
                        }
                    }
                    if(c==0)
                    {
                        temp=temp+'</tr>';                        
                        j++;                        
                    }                    
                    i++;
                });

                temp=temp+'<tr><td></td><td style="text-align: center;">TỔNG</td><td></td><td></td><td></td><td></td><td></td><td style="text-align: right;">'+formatNumber(tongTien)+'</td></tr>';
                //------------------------------------------------
                temp = temp.replace(/__index__/g, sD);                    
                $('#tbSanPham tbody').append(temp);
                var soTienBangChu=docso(tongTien);                                
                $('#tongSoTien').text(soTienBangChu);
                                
                window.print();                
                document.getElementById('formXuatHang').submit();
                return true;
            }                
        }

    </script>
    <script>
        $(document).ready(function(){
          $(document).on('click', '.btnHuy', function(){
            $(this).closest('tr').remove();
            return false;
          });
        });
    </script>

    <script language="JavaScript">
        function xacNhanHuy() {
            var soDong = $('#tbXuatHang > tbody > tr').length; 
            if(soDong==0)
            {
                return false;
            }
            else
            {
                var xacNhan=confirm("Bạn thật sự muốn hủy đơn hàng này?");
                if(xacNhan==true)
                {
                    return true;
                }
                return false;
            }
        }
    </script>