<div class="row">
    <div class="col-md-2">
       <div class="h5a-sidebar affix">
            <span class="breadcrumb row">
                <a href="<?php echo $this->url('hang_hoa/crud',array('action'=>'index'));?>">/ Kho</a>
                 / Hàng hóa /
            </span>
            <ul class="nav h5a-sidenav nav-list accordion">
                        
            </ul>
        </div>
    </div>
    <div class="col-md-10" role="main">
        <div class="h5a-docs-section">
            <div class="page-header">
                <div class="row">
                    <div class="col-sm-7">
						 <h1>thêm taxonomy con</h1>
                    </div>
                    <div class="col-sm-5">                       
                        <div class="pull-right">
                            <div class="btn-group ">
                                <button id="btPrev" type="button" class="h5a-btn btn btn-default btn-sm">
                                    <i class="fa fa-chevron-left"></i>
                                </button>                                    
                                <button id="btNext" type="button" class="h5a-btn btn btn-default btn-sm">
                                    <i class="fa fa-chevron-right"></i>
                                </button>
                                <a href="<?php echo $this->url('taxonomy/childTaxonomy', array('tax'=>$taxs));?>"><button type="button" class="h5a-btn btn btn-primary btn-sm">Trở về</button></a>&nbsp;
                            </div>                                
                        </div>
                    </div>
                </div>
                             
            </div>
           
            <div class="row">                 
				 <div class="row">
					 <div class="col-lg-6">
					 <?php
					 //die(var_dump($taxs));
					 $form->setAttribute('tax', $this->url('taxonomy/childTaxonomy/crudChildTaxonomy', array('tax'=>$taxs,'action' => 'taxonomyAdd')));
					 $form->setAttribute('role','form');
					 $form->prepare();

					 echo $this->form()->openTag($form);
					 if($coKiemTraTonTai==1)
					 {
					 	echo 'Tên vừa nhập đã tồn tại trong Taxonomy này';
					 }
					 $termTaxonomy=$form->get('term-taxonomy');
					 $term=$termTaxonomy->get('termId');
					 //$term=$termTaxonomy->get('termTaxonomyId');
					 echo $this->formHidden($termTaxonomy->get('termTaxonomyId'));
					 echo $this->formHidden($term->get('slug'));?>

					<div class"form-group">
					 <?php $tenTaxonomy=$term->get('name');?>
					 <?php $tenTaxonomy->setAttribute('class','form-control'); ?>
					 <label><?php echo $tenTaxonomy->getLabel(); ?></label>
					 <?php echo $this->formElement($tenTaxonomy); 
					?>
					</div>

					<div>
						<?php $moTaTaxonomy=$termTaxonomy->get('description');?>
						<?php $moTaTaxonomy->setAttribute('class','form-control'); ?>
					 	<label><?php echo $moTaTaxonomy->getLabel();?></label>
					 	<?php echo $this->formElement($moTaTaxonomy);?>
					</div>

					<div hidden="true">
						<?php $parentTaxonomy=$termTaxonomy->get('parent');?>
						<?php $parentTaxonomy->setAttribute('class','form-control'); ?>
					 	<label><?php echo $parentTaxonomy->getLabel();?></label>
					 	<?php
					 		 //die(var_dump($termTaxonomys[0]->getTermId()->getName()));
					 		 $parentTaxonomy->setValueOptions($this->makeArrayCollection($termTaxonomys)); 
					 	?>
					 	<?php echo $this->formElement($parentTaxonomy);?>

					</div><br>
					<div style="text-align:right;">
						<?php 
					 $submit=$form->get('submit');
					 $submit->setValue('Thêm');
					 $submit->setAttribute('class','h5a-btn btn btn-primary btn-sm');
					  $submit->setAttribute('style','width: 100px;');
					 echo $this->formSubmit($submit);
					 echo $this->form()->closeTag();?>
					</div>
					 

					</div>
				</div>

            </div>
        </div>                
    </div>
</div>
<!-- FormatNumber -->
    <script src="<?php echo $this->basePath();?>/js/formatnumber.js"></script>

    <!-- convernumbertostring -->
    <script src="<?php echo $this->basePath();?>/js/convernumbertostring.js"></script>

    <!-- jQuery -->
    <script src="<?php echo $this->basePath();?>/js/jquery.js"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="<?php echo $this->basePath();?>/js/bootstrap.min.js"></script>

    <!-- DataTables JavaScript -->
    <script src="<?php echo $this->basePath();?>/js/plugins/dataTables/jquery.dataTables.js"></script>