<?php
    $this->headTitle('Đăng nhập'); 
    $url = $this->url('application/default', array(
        'controller'=>'Index',
        'action' => 'login'
     ));
?>
<div class="container" style="margin-top: 50px;">    
    <div class="col-sm-3">
    </div>

    <div class="col-sm-6">
        <div>
            <div >
                <label style="font-size:40px; margin-bottom:-5px;">Đăng Nhập</label>
            </div>        
        </div>
        <div>
            <div class="col-sm-3">
            </div>
            <div class="col-sm-7">
                <form role="form" method="post" action="<?php echo $url; ?>">
                  <div class="form-group">
                    <label for="email">Email</label>
                    <input type="email" name="identity" required="required" class="form-control" id="email" placeholder="Nhập email"/>
                  </div>

                  <div class="form-group">
                    <label for="matKhau">Mật khẩu</label>
                    <input type="password" name="credential" required="required" class="form-control" id="matKhau" placeholder="Nhập mật khẩu">
                  </div>                  
                  <button type="submit" class="btn btn-primary col-sm-12">Đăng nhập</button>
                  <a href="#">Quên mật khẩu</a> 
                </form>
            </div>
        </div>
    </div>

    <div class="col-sm-3">
    </div>
</div>
<!-- jQuery -->
<script src="<?php echo $this->basePath();?>/js/jquery.js"></script>

<!-- Bootstrap Core JavaScript -->
<script src="<?php echo $this->basePath();?>/js/bootstrap.min.js"></script>

<!-- DataTables JavaScript -->
<script src="<?php echo $this->basePath();?>/js/plugins/dataTables/jquery.dataTables.js"></script>
