<?php
    $this->headTitle('Quản lý tài khoản');
    $form->setAttribute('action', $this->url('application/default', array('controller'=>'index','action' => 'reset-password','id'=>$user->getId())));
     $form->setAttribute('role','form');
     //$form->setAttribute('class','form-horizontal');
     $form->prepare();
     echo $this->form()->openTag($form);
?>

         
    <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">                        
            <h4 class="modal-title" id="exampleModalLabel">Reset mật khẩu</h4>
          </div>
          <div class="modal-body">
            <form>
              <div class="form-group">
                <label for="recipient-name" class="control-label">Nhập mật khẩu mới:</label>
                <?php
                  $resetPassword=$form->get('reset-password');
                  
                  $userId=$resetPassword->get('userId');
                  echo $this->formHidden($userId);

                  $password=$resetPassword->get('password');
                  $password->setAttribute('id','password');
                  $password->setAttribute('class','form-control');
                  echo $this->formElement($password);
                ?>
                <span id="passwordError"></span>
              </div>
              <div class="form-group">
                <label for="message-text" class="control-label">Nhập lại mật khẩu:</label>
                <?php
                  $form->get('passwordVerify')->setAttribute('class','form-control');
                  $form->get('passwordVerify')->setAttribute('id','passwordVerify');
                  echo $this->formElement($form->get('passwordVerify'));
                ?>
                &nbsp;&nbsp;&nbsp;&nbsp;<span id="passwordVerifyError"></span>
              </div>
            </form>
          </div>
          <div class="modal-footer">
            <a href="<?php echo $this->url('application/default',array('controller'=>'index','action'=>'quan-ly-tai-khoan')); ?>"><button type="button" class="btn btn-default">Close</button></a>
            <button type="submit" class="btn btn-primary" id="reset">Reset</button>
          </div>
        </div>
      </div>
    </div>
<?php
    echo $this->form()->closeTag();
?>
            
        

<!-- jQuery -->
<script src="<?php echo $this->basePath();?>/js/jquery.js"></script>

<!-- Bootstrap Core JavaScript -->
<script src="<?php echo $this->basePath();?>/js/bootstrap.min.js"></script>

<!-- DataTables JavaScript -->
<script src="<?php echo $this->basePath();?>/js/plugins/dataTables/jquery.dataTables.js"></script>

<!-- Page-Level Demo Scripts - Tables - Use for reference -->
<script type="text/javascript">
    $(document).ready(function(){

        $('#exampleModal').modal({
            backdrop:'static',
            keyboard:false
        }).modal('show');


        $('#reset').on('click',function(){
          var password=$('#password').val();
          var passwordVerify=$('#passwordVerify').val();
          //alert(password+'  '+passwordVerify);
          if(password==passwordVerify){
            return true;
          }
          else{
            $('#passwordVerifyError').text(' * Vui lòng kiểm tra lại mật khẩu xác nhận');
            return false;
          }
        })

    })
</script>