<h1><?php echo $this->translate('Đăng nhập'); ?></h1>

<?php
$this->layout('layout/giaodien');
$form = $this->loginForm;
$form->prepare();
$form->setAttribute('action', $this->url('zfcuser/login'));
$form->setAttribute('method', 'post');
?>

<?php echo $this->form()->openTag($form) ?>

    <dl class="zend_form">
        <?php echo $this->formElementErrors($form->get('identity')) ?>

        <dt><?php echo $this->formLabel($form->get('identity')) ?></dt>
        <dd><?php echo $this->formInput($form->get('identity')) ?></dd>

        <dt><?php echo $this->formLabel($form->get('credential')) ?></dt>
        <dd><?php echo $this->formInput($form->get('credential')) ?></dd>

        <?php if ($this->redirect): ?>
            <input type="hidden" name="redirect" value="<?php echo $this->escapeHtml($this->redirect) ?>" />
        <?php endif ?>

        <dd>
            <?php                
                echo $this->formButton($form->get('submit')); 
            ?>
        </dd>
    </dl>

<?php echo $this->form()->closeTag() ?>

<!-- jQuery -->
<script src="<?php echo $this->basePath();?>/js/jquery.js"></script>

<!-- Bootstrap Core JavaScript -->
<script src="<?php echo $this->basePath();?>/js/bootstrap.min.js"></script>

<!-- DataTables JavaScript -->
<script src="<?php echo $this->basePath();?>/js/plugins/dataTables/jquery.dataTables.js"></script>
