<?php $this->layout('layout/giaodien');?>
<?php
if (!$this->enableRegistration) {
    print "Registration is disabled";
    return;
}
$form = $this->registerForm;
$form->prepare();
$form->setAttribute('action', $this->url('zfcuser/register'));
$form->setAttribute('method', 'post');
?>
<?php echo $this->form()->openTag($form) ?>

<div class="container">
        <div class="row">
            <div class="col-md-2">
                <div class="h5a-sidebar affix">
                    <span class="breadcrumb row">
                        <a href="<?php echo $this->url('hang_hoa/crud',array('action'=>'index'));?>">/ Kho</a> 
                        <a href="<?php echo $this->url('kenh_phan_phoi',array('action'=>'index'));?>">/ Khách hàng</a>
                         / Thêm khách hàng /
                    </span>
                    <ul class="nav h5a-sidenav nav-list accordion">                        
                        <li>
                            <a href="<?php echo $this->url('kenh_phan_phoi/crud',array('action'=>'index'));?>">
                                <i class="glyphicon glyphicon-open"></i> Khách hàng
                            </a>
                        </li> 
                        <li>
                            <a href="<?php echo $this->url('kenh_phan_phoi/crud',array('action'=>'nhaCungCap'));?>">
                                <i class="glyphicon glyphicon-save"></i> Nhà cung cấp
                            </a>
                        </li>                 
                        <li>
                            <a href="<?php echo $this->url('loi_nhuan/crud',array('action'=>'donHang'));?>">
                                <i class="fa fa-cubes"></i> Đơn hàng
                            </a>
                        </li>
                        <li>
                            <a href="<?php echo $this->url('loi_nhuan/crud',array('action'=>'index'));?>">
                                <i class="fa fa-flag-checkered"></i> Doanh thu
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
            <div class="col-md-10" role="main">
                <div class="h5a-docs-section">
                    <div class="page-header">
                        <div class="row">
                            <div class="col-sm-6">
                                <h1>TẠO TÀI KHOẢN</h1>
                            </div>
                            <div class="col-sm-6">
                                <div class="pull-right">
                                    <button type="button" class="h5a-btn btn btn-default btn-sm">Hủy</button>
                                    <button type="submit" class="h5a-btn btn btn-primary btn-sm">Lưu
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row">                        
                            <h4 class="underline">More Info</h4>
                            <table class="item">
                                <tbody>
                                   <!--  <tr>
                                        <td>Họ tên</td>
                                        <td>  
                                                                                                         
                                        <input type="text" class="h5a-input form-control input-sm" name="hoTen" id="form-field-1">          
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>Email</td>
                                        <td>  
                                                                                                         
                                        <input type="email" class="h5a-input form-control input-sm" name="username" id="form-field-1">          
                                        </td>
                                    </tr>
                                
                                    <tr>
                                        <td>Tên đăng nhập</td>
                                        <td>                                                                   
                                        <input type="text" class="h5a-input form-control input-sm" name="username" id="form-field-1">          
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>Mật khẩu</td>
                                        <td>                                                                   
                                        <input type="password" class="h5a-input form-control input-sm" name="password" id="form-field-1">          
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>Nhập lại mật khẩu</td>
                                        <td>                                                                   
                                        <input type="password" class="h5a-input form-control input-sm" name="passwordVerify" id="form-field-1">          
                                        </td>
                                    </tr>

                                    <tr>
                                        <td>Tên hiển thị</td>
                                        <td>  
                                                                                                         
                                        <input type="text" class="h5a-input form-control input-sm" name="displayName" id="form-field-1">          
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>Địa chỉ</td>
                                        <td>
                                              <input type="text" class="h5a-input form-control input-sm" name="diaChi" id="form-field-1">  
                                              <input type="hidden" name="state" value="0">          
                                                                         
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>Mô tả</td>
                                        <td>                                         
                                        <input type="TextArea" class="form-control h5a" id="editor" row="5">
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>Hình ảnh</td>
                                        <td>                                        
                                            <input type="file" class="h5a-btn btn btn-primary">
                                        </td>
                                    </tr>                                    
                                    
                                    <tr>
                                        <td>Di động</td>
                                        <td>                                        
                                            <input type="number" name="diDong" class="h5a-input form-control input-sm" id="form-field-1">                       
                                        </td>
                                    </tr>


                                    <tr>
                                        <td>Điện thoại cố định</td>
                                        <td>                                       
                                            <input type="number" name="dienThoaiCoDinh" class="h5a-input form-control input-sm" id="form-field-1">
                                        </td>
                                    </tr>


                                    <tr>
                                        <td>Twitter</td>
                                        <td>                                        
                                            <input type="number" name="twitter" class="h5a-input form-control input-sm" id="form-field-1">                                       
                                        </td>
                                    </tr> -->

                                    <?php foreach ($form as $element): ?>
                                    <tr>
                                    <?php if (!$element instanceof Zend\Form\Element\Button): ?>
                                        <td>
                                          <span><label for="email" style="width:150px;"><?php echo $this->formLabel($element) ?></label></span>
                                        </td>
                                    <?php endif ?>
                                    <?php if ($element instanceof Zend\Form\Element\Button): ?> 
                                            
                                        <td>
                                            <?php $element->setAttribute('class','btn btn-primary');?>
                                            <?php echo $this->formButton($element); ?>
                                        </td>
                                    <?php elseif ($element instanceof Zend\Form\Element\Captcha): ?>
                                        <td>   
                                             <?php $element->setAttribute('class','form-control');?> 
                                             <?php echo $this->formCaptcha($element); ?>
                                             <?php echo $this->formElementErrors($element); ?>

                                        </td>
                                    <?php else: ?>
                                        <td>
                                          <?php $element->setAttribute('class','form-control');?>
                                          <?php echo $this->formInput($element); ?>
                                          <?php echo  $this->formElementErrors($element); ?>
                                        </td>
                                    <?php endif ?>
                                    <tr>
                                <?php endforeach ?>
                                </tbody>
                            </table>
                    </div>
                    <div class="page-footer">
                        <div class="row bottom20">
                            <div class="col-sm-6 col-sm-offset-6">
                                <div class="pull-right">
                                    <button type="button" class="h5a-btn btn btn-default btn-sm">Hủy</button>
                                    <button type="submit" class="h5a-btn btn btn-primary btn-sm">Lưu
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    
    <?php if ($this->redirect): ?>
        <input type="hidden" name="redirect" value="<?php echo $this->escapeHtml($this->redirect) ?>" />
    <?php endif ?>
<?php echo $this->form()->closeTag() ?>

 <!-- /.container -->

    <!-- jQuery -->
    <script src="<?php echo $this->basePath();?>/js/jquery.js"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="<?php echo $this->basePath();?>/js/bootstrap.min.js"></script>

    <!-- DataTables JavaScript -->
    <script src="<?php echo $this->basePath();?>/js/plugins/dataTables/jquery.dataTables.js"></script>

    <!-- Summernot JavaScript -->
    <script src="<?php echo $this->basePath();?>/js/summernote.min.js"></script>

    <!-- Page-Level Demo Scripts - Tables - Use for reference -->
    <script>
    $(document).ready(function() {
        $('#dataTables-example').dataTable({
            "pagingType": "simple",
            "bPaginate": true,
            "bLengthChange": true,
            "bFilter": true,
            "bInfo": true,
            "bAutoWidth": true
        });
    });

    $("#editor").summernote({height:150});
    </script>
       
