<?php echo $this->headTitle('Công nợ'); ?>

    <div class="row">
        <div class="col-md-2">
            <div class="h5a-sidebar affix">
                <span class="breadcrumb row">
                    <a href="<?php echo $this->url('hang_hoa/crud',array('action'=>'index'));?>">/ Kho</a>
                    <a href="<?php echo $this->url('cong_no');?>">/ Khách hàng</a>
                     / Công nợ /
                </span>
                <ul class="nav h5a-sidenav nav-list accordion">
                    
                    <li>
                        <a href="<?php echo $this->url('cong_no/crud',array('action'=>'index'));?>">
                            <i class="glyphicon glyphicon-open"></i> Công nợ Khách hàng
                        </a>
                    </li> 
                    <li>
                        <a href="<?php echo $this->url('cong_no/crud',array('action'=>'congNoNhaCungCap'));?>" title="Công nợ nhà cung cấp">
                            <i class="glyphicon glyphicon-save"></i> Công nợ NCC
                        </a>
                    </li>                 
                    
                </ul>
            </div>
        </div>
        <div class="col-md-10" role="main">
            <div class="h5a-docs-section">
                <div class="page-header">
                    <div class="row">
                        <div class="col-sm-6">
                            <h1>Chi tiết công nợ</h1>
                        </div>

                        <div class="col-sm-6">
                            <div class="pull-right">
                                <div class="btn-group ">
                                    <button id="btPrev" type="button" class="h5a-btn btn btn-default btn-sm">
                                        <i class="fa fa-chevron-left"></i>
                                    </button>                                    
                                    <button id="btNext" type="button" class="h5a-btn btn btn-default btn-sm">
                                        <i class="fa fa-chevron-right"></i>
                                    </button>
                                </div>
                                <a href="#"><button type="button" class="h5a-btn btn btn-default btn-sm">Export</button></a>
                                
                            </div>
                        </div>                        
                    </div>
                    <?php 
                        $flash=$this->flashMessenger();
                        $flash->setMessageOpenFormat('<div%s>
                         <button type="button" class="close" data-dismiss="alert" aria-hidden="true">
                             &times;
                         </button>
                         <ul><li>')
                         ->setMessageSeparatorString('</li><li>')
                         ->setMessageCloseString('</li></ul></div>');

                         echo $flash->render('error',   array('alert', 'alert-dismissable', 'alert-danger'));
                         echo $flash->render('info',    array('alert', 'alert-dismissable', 'alert-info'));
                         echo $flash->render('default', array('alert', 'alert-dismissable', 'alert-warning'));
                         echo $flash->render('success', array('alert', 'alert-dismissable', 'alert-success'));
                    ?> 
                
                </div>
                &nbsp;&nbsp; Tên nhà cung cấp: <a href="<?php echo $this->url('cong_no/crud',array('action'=>'thanhToanNhaCungCap','id'=>$doiTac->getIdDoiTac())); ?>"><?php echo $doiTac->getHoTen(); ?></a>
                <div class="box">
                    <ul class="nav nav-tabs" role="tablist" id="myTab">
                        <li role="presentation" class="active">
                            <a href="#home" role="tab" data-toggle="tab">Tất cả</a>
                        </li>                                                 
                    </ul>
                    <div class="tab-content">
                        <div role="tabpanel" class="tab-pane active" id="home">
                            <div class="container">

                                <div class="row">
                                    <table id="" class="dataTables-example">
                                        <thead>
                                            <th>Hóa đơn</th>
                                            <th>Tên sản phẩm</th>
                                            <th>Giá</th>
                                            <th>Số lượng</th>
                                            <th>Thành tiền</th>                                                
                                        </thead>
                                        <tbody>
                                        <?php
                                        //die(var_dump($hoaDons));
                                        foreach ($phieuNhaps as $phieuNhap) {
                                       
                                            foreach ($phieuNhap->getCtPhieuNhaps() as $ctPhieuNhap) {
                                        ?>
                                            <tr>
                                                <td><a href="<?php echo $this->url('kenh_phan_phoi/crud',array('action'=>'chiTietPhieuNhap','id'=>$phieuNhap->getIdPhieuNhap())); ?>"><?php echo '#'.$phieuNhap->getMaPhieuNhap(); ?></a></td>
                                                <td><?php echo $ctPhieuNhap->getIdSanPham()->getTenSanPham(); ?></td>
                                                <td><?php echo $ctPhieuNhap->getGiaNhap(); ?></td>
                                                <td><?php echo $ctPhieuNhap->getSoLuong(); ?></td>
                                                <td>
                                                    <?php $thanhTien=(float)$ctPhieuNhap->getGiaNhap()*(float)$ctPhieuNhap->getSoLuong(); 
                                                        echo $thanhTien;
                                                    ?>
                                                </td>
                                            </tr>
                                        <?php  
                                            }
                                        }
                                        ?>
                                        
                                        </tbody>
                                    </table>
                                </div>
                                <div class="row">
                                    <h3>Lịch sử công nợ nhà cung cấp</h3>
                                    <table border="1" width="100%">
                                        <thead>
                                            <th>Khách hàng</th>
                                            <th>Ngày đầu kì</th>
                                            <th>Đầu kì</th>
                                            <th>Phát sinh</th>
                                            <th>Cuối kì</th>
                                            <th>Thanh toán</th>
                                            <th>Dư nợ</th>
                                            <th>Ngày thanh toán</th>
                                        </thead>
                                        <tbody>
                                        <?php 
                                            foreach ($response as $rp) { 
                                            ?>
                                                <tr>                                                    
                                                    <td>
                                                    <?php
                                                        if($rp['noCuoiKi']>0&&$rp['thanhToan']=='Chưa Thanh Toán')
                                                        {
                                                    ?>
                                                        <a href="<?php echo $this->url('cong_no/crud',array('action'=>'thanhToanNhaCungCap','id'=>$doiTac->getIdDoiTac())); ?>"><?php echo $doiTac->getHoTen(); ?></a></td>
                                                    <?php
                                                        }
                                                        else
                                                        {
                                                            echo $doiTac->getHoTen();
                                                        }
                                                    ?>
                                                    <td><?php  echo $rp['ngayDauKi']; ?></td>
                                                    <td><?php  echo $rp['noDauKi']; ?></td>
                                                    <td><?php  echo $rp['noPhatSinh']; ?></td>
                                                    <td><?php  echo $rp['noCuoiKi']; ?></td>
                                                    <td><?php  echo $rp['thanhToan']; ?></td>
                                                    <td><?php  echo $rp['duNo']; ?></td>
                                                    <td>
                                                    <?php  
                                                        if($rp['ngayThanhToan'])
                                                        {
                                                            echo $rp['ngayThanhToan']->format('Y-m-d');
                                                        }
                                                    ?>
                                                    </td>
                                                    
                                                </tr>
                                            <?php    
                                            }
                                        ?>
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>                        
                    </div>
                </div>
            </div>
        </div>
    </div>    
    <!-- /.container -->

    <!-- jQuery -->
    <script src="<?php echo $this->basePath();?>/js/jquery.js"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="<?php echo $this->basePath();?>/js/bootstrap.min.js"></script>

    <!-- DataTables JavaScript -->
    <script src="<?php echo $this->basePath();?>/js/plugins/dataTables/jquery.dataTables.js"></script>

    <!-- Page-Level Demo Scripts - Tables - Use for reference -->
    <script>
    $(document).ready(function() {
        $('.dataTables-example').dataTable({
            "pagingType": "simple",
            "bPaginate": true,
            "bLengthChange": true,
            "bFilter": true,
            "bInfo": true,
            "bAutoWidth": true,

            "language": {
                "lengthMenu": "Hiển thị _MENU_ mục",
                "zeroRecords": "Không có dữ liệu",
                "info": "_PAGE_ / _PAGES_",
                "infoEmpty": "",
                "infoFiltered": "",
                "decimal": ",",
                "thousands": ".",
                "search":"Tìm kiếm:",
            }
        });
    });

    $('#btPrev').click(function(){
    document.getElementById('dataTables-example_previous').click();
    });

    $('#btNext').click(function(){
        document.getElementById('dataTables-example_next').click();
    });
    </script>