 <style type="text/css">
    #notifications{
         width: 215px; 
         margin-left: 20px;
    }
</style>
<?php echo $this->headTitle('Công nợ'); ?>
    <div class="row">
        <div class="col-md-2">
            <div class="h5a-sidebar affix">
                <span class="breadcrumb row">
                    <a href="<?php echo $this->url('hang_hoa/crud',array('action'=>'index'));?>">/ Kho</a>
                    <a href="<?php echo $this->url('cong_no');?>">/ Khách hàng</a>
                     / Công nợ /
                </span>
                <ul class="nav h5a-sidenav nav-list accordion">
                    <li>
                        <a href="<?php echo $this->url('cong_no/crud',array('action'=>'tong-hop-thu-chi'));?>">
                            Tổng hợp thu chi
                        </a>
                    </li> 
                    <li>
                        <a href="<?php echo $this->url('cong_no/crud',array('action'=>'index'));?>">
                            Khách hàng
                        </a>
                    </li> 
                    <li>
                        <a href="<?php echo $this->url('cong_no/crud',array('action'=>'cong-no-nha-cung-cap'));?>" title="Công nợ nhà cung cấp">
                            Nhà cung cấp
                        </a>
                    </li> 
                    <li>
                        <a href="<?php echo $this->url('cong_no/crud',array('action'=>'lap-phieu-thu'));?>" title="Công nợ nhà cung cấp">
                           Phiếu thu
                        </a>
                    </li> 
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                            Phiếu chi
                        </a>
                         <ul class="dropdown-menu" id="notifications">   
                            <li>
                                <a href="<?php echo $this->url('cong_no/crud',array('action'=>'lap-phieu-chi-nha-cung-cap')); ?>">Lập phiếu chi Nhà cung cấp
                                </a>
                                
                            </li>
                            <li class="divider"></li>
                            <li>
                                <a href="<?php echo $this->url('cong_no/crud',array('action'=>'lap-phieu-chi-khach-hang')); ?>">Lập phiếu chi Khách hàng
                                </a>
                                
                            </li>
                        </ul>
                    </li> 
                </ul>
            </div>
        </div>
        <div class="col-md-10" role="main">
            <div class="h5a-docs-section">
                <div class="page-header">
                    <div class="row">
                        <div class="col-sm-6">
                            <h1>Khách hàng</h1>
                        </div>

                        <div class="col-sm-6">
                            <div class="pull-right">
                                <div class="btn-group ">
                                    <button id="btPrev" type="button" class="h5a-btn btn btn-default btn-sm">
                                        <i class="fa fa-chevron-left"></i>
                                    </button>                                    
                                    <button id="btNext" type="button" class="h5a-btn btn btn-default btn-sm">
                                        <i class="fa fa-chevron-right"></i>
                                    </button>
                                </div>
                                <a href="<?php echo $this->url('cong_no/crud',array('action'=>'export-cong-no-khach-hang')); ?>"><button type="button" class="h5a-btn btn btn-default btn-sm">Export</button></a>
                                
                            </div>
                        </div>                        
                    </div>
                    <?php 
                        $flash=$this->flashMessenger();
                        $flash->setMessageOpenFormat('<div%s>
                         <button type="button" class="close" data-dismiss="alert" aria-hidden="true">
                             &times;
                         </button>
                         <ul><li>')
                         ->setMessageSeparatorString('</li><li>')
                         ->setMessageCloseString('</li></ul></div>');

                         echo $flash->render('error',   array('alert', 'alert-dismissable', 'alert-danger'));
                         echo $flash->render('info',    array('alert', 'alert-dismissable', 'alert-info'));
                         echo $flash->render('default', array('alert', 'alert-dismissable', 'alert-warning'));
                         echo $flash->render('success', array('alert', 'alert-dismissable', 'alert-success'));
                     ?>
                </div>
                <div class="box">
                    <ul class="nav nav-tabs" role="tablist" id="myTab">
                        <li role="presentation" class="active">
                            <a href="#home" role="tab" data-toggle="tab">Tất cả</a>
                        </li>
                        <?php 
                        foreach ($kenhPhanPhois as $kenhPhanPhoi) { 
                            if($kenhPhanPhoi['cap']>0)
                            {
                        ?>
                                <li role="presentation">
                                    <a href="#<?php echo $kenhPhanPhoi['termTaxonomyId']; ?>" role="tab" data-toggle="tab"><?php echo $kenhPhanPhoi['termId']['name'] ?></a>
                                </li>
                        <?php
                            }
                        }
                        ?>                            
                    </ul>
                    <div class="tab-content">
                        <div role="tabpanel" class="tab-pane active" id="home">
                            <div class="container">
                                <div class="row">
                                    <table id="" class="dataTables-example">
                                        <thead>
                                            <th><input type="checkbox"/></th>
                                            <th>Khách hàng</th>
                                            <th>Ngày</th>
                                            <th>Nợ đầu kì</th>
                                            <th>Phát sinh</th>
                                            <th>Cuối kì</th>
                                            <!-- <th>Chi tiết</th> -->
                                        </thead>
                                        <tbody>
                                        <?php 
                                            
                                            foreach ($response as $rp) { 
                                            ?>
                                                <tr>
                                                    <td><input type="checkbox"/></td>
                                                    <td>
                                                        <a href="<?php echo $this->url('cong_no/crud',array('action'=>'chi-tiet-cong-no-khach-hang','id'=>$rp['idDoiTac'])); ?>"><?php echo $rp['hoTenDoiTac']; ?></a>          
                                                    </td>
                                                    <td><?php  echo $rp['ngayDauKi']; ?></td>
                                                    <td><?php  echo number_format($rp['noDauKi'],'0','',' '); ?></td>
                                                    <td><?php  echo number_format($rp['noPhatSinh'],'0','',' '); ?></td>
                                                    <td><?php  echo number_format($rp['noCuoiKi'],'0','',' '); ?></td>
                                                    <!-- <td></td> -->
                                                    
                                                </tr>
                                            <?php    
                                            }
                                        ?>
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                        <?php 
                        foreach ($kenhPhanPhois as $kenhPhanPhoi) { 
                            if($kenhPhanPhoi['cap']>0)
                            {
                        ?>
                                <div role="tabpanel" class="tab-pane" id="<?php echo $kenhPhanPhoi['termTaxonomyId']; ?>">
                                    <p class="note">
                                        <table id="<?php echo $kenhPhanPhoi['termTaxonomyId']; ?>" class="dataTables-example">
                                        <thead>
                                            <th><input type="checkbox"/></th>
                                            <th>Khách hàng</th>
                                            <th>Ngày</th>
                                            <th>Nợ đầu kì</th>
                                            <th>Phát sinh</th>
                                            <th>Cuối kì</th>
                                        </thead>
                                        <tbody>
                                        <?php 
                                            
                                            foreach ($response as $rp) { 
                                                if($kenhPhanPhoi['termTaxonomyId']==$rp['idKenhPhanPhoi'])
                                                {
                                                ?>
                                                    <tr>
                                                        <td><input type="checkbox"/></td>
                                                        <td>
                                                            <a href="<?php echo $this->url('cong_no/crud',array('action'=>'chi-tiet-cong-no-khach-hang','id'=>$rp['idDoiTac'])); ?>"><?php echo $rp['hoTenDoiTac']; ?></a>
                                                        </td>
                                                        <td><?php  echo $rp['ngayDauKi']; ?></td>                                                        
                                                        <td><?php  echo number_format($rp['noDauKi'],'0','',' '); ?></td>
                                                        <td><?php  echo number_format($rp['noPhatSinh'],'0','',' '); ?></td>
                                                        <td><?php  echo number_format($rp['noCuoiKi'],'0','',' '); ?></td>
                                                    </tr>
                                                <?php    
                                                }
                                            }
                                            ?>
                                        </tbody>
                                    </table>
                                    </p>
                                </div>
                        <?php
                            }
                        }
                        ?>
                    </div>
                </div>
            </div>
        </div>
    </div>    
    <!-- /.container -->

    <!-- jQuery -->
    <script src="<?php echo $this->basePath();?>/js/jquery.js"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="<?php echo $this->basePath();?>/js/bootstrap.min.js"></script>

    <!-- DataTables JavaScript -->
    <script src="<?php echo $this->basePath();?>/js/plugins/dataTables/jquery.dataTables.js"></script>

    <!-- Page-Level Demo Scripts - Tables - Use for reference -->
    <script>
    $(document).ready(function() {
        $('.dataTables-example').dataTable({
            "pagingType": "simple",
            "bPaginate": true,
            "bLengthChange": true,
            "bFilter": true,
            "bInfo": true,
            "bAutoWidth": true,

            "language": {
                "lengthMenu": "Hiển thị _MENU_ mục",
                "zeroRecords": "Không có dữ liệu",
                "info": "_PAGE_ / _PAGES_",
                "infoEmpty": "",
                "infoFiltered": "",
                "decimal": ",",
                "thousands": ".",
                "search":"Tìm kiếm:",
            }
        });
    });

    $('#btPrev').click(function(){
    document.getElementById('dataTables-example_previous').click();
    });

    $('#btNext').click(function(){
        document.getElementById('dataTables-example_next').click();
    });
    </script>