<style type="text/css">
    #search-result-khach-hang{cursor:pointer;}
    #notifications{
         width: 215px; 
         margin-left: 20px;
    }
</style>
<?php
    $this->headTitle('Lập phiếu thu');
    $dateTime=new DateTime(null,new DateTimeZone('Asia/Ho_Chi_Minh'));
    $form->setAttribute('action', $this->url('cong_no/crud', array('action' => 'lap-phieu-thu')));
     $form->setAttribute('role','form');
     $form->setAttribute('id','formThanhToan');
     $form->setAttribute('class','form-horizontal');
     $form->prepare();
     echo $this->form()->openTag($form);
     
     echo $this->formHidden($form->get('phieu-thu')->get('idPhieuThu'));
     $form->get('phieu-thu')->get('maPhieuThu')->setAttribute('value',$maPhieuThu);
     echo $this->formHidden($form->get('phieu-thu')->get('maPhieuThu'));
     
     $congNo=$form->get('phieu-thu')->get('idCongNo');
     echo $this->formHidden($congNo->get('idCongNo'));

     echo $this->formHidden($congNo->get('idDoiTac'));


     $congNo->get('ki')->setAttribute('hidden','true');
     $congNo->get('ki')->setAttribute('id','ki');
     echo $this->formHidden($congNo->get('ki'));

     $congNo->get('noDauKi')->setAttribute('id','noDauKi');
     echo $this->formHidden($congNo->get('noDauKi'));

     $congNo->get('noPhatSinh')->setAttribute('id','noPhatSinh');
     echo $this->formHidden($congNo->get('noPhatSinh'));
     $idUserNv=0;
     if($this->zfcUserIdentity()){
        $idUserNv=$this->zfcUserIdentity()->getId();
     }
     $form->get('phieu-thu')->get('idUserNv')->setAttribute('value',$idUserNv);
     echo $this->formHidden($form->get('phieu-thu')->get('idUserNv'));

     $form->get('phieu-thu')->get('ngayThanhToan')->setAttribute('value', $dateTime);
     echo $this->formHidden($form->get('phieu-thu')->get('ngayThanhToan'));     
?>
<style type="text/css">    
    #khach-hang-search-result{ cursor:pointer;}
     @media print {    
        .in{display: block;}   
        .khongin{display: none;}
        .in table tr td{
            padding: 0px;
        }
        
    }
</style>
<div class="in" hidden="true" align="center" style="font-size:13px;">
    <table width="791px" hieght="567">
        <tr><td width="400px">NHÀ SÁCH VINH QUANG</td><td></td><td width="200px" style="text-align:right;">Mẫu số: 01 - TT</td></tr>
        <tr><td>45A Phạm Ngũ Lão, Phường 1, TP. Trà Vinh</td><td></td><td width="200px" style="text-align:right;"></td></tr>
        <tr><td>Mã số thuế:</td><td></td><td width="200px" style="text-align:right;"></td></tr>
        
    </table>
    <table width="791px" style="font-size:13px;">
        <tr><td width="250px">&nbsp;</td><td style="font-size:16px; text-align:center;"><b>PHIẾU THU</b></td><td width="250px"><span ><b>Số: <?php echo $maPhieuThu; ?></b></span></td></tr>
    </table>
    <table width="791px" style="font-size:13px;">
        <tr>
            <td width="541px">
                <table >
                    <tr><td width="240px">&nbsp;</td><td align="center" width="300px"><i>Ngày <?php echo date("d") ?> tháng <?php echo date("m") ?> năm <?php echo date("Y") ?><i/></td></tr>
                    <tr><td width="240px">&nbsp;</td><td align="center" width="300px">Liên 1: Lưu</td></tr>
                    <tr><td colspan="2"><span ><b>Họ tên người nộp tiền:</b> </span><div id="hoTenNguoiNopTien" style="margin-top: -18px; margin-left:150px;"></div></td></tr>
                    <tr><td colspan="2"><span ><b>Địa chỉ:</b></span><div id="diaChi" style="margin-top: -18px; margin-left:70px;"></div></td></tr>
                    <tr><td colspan="2"><span ><b>lý do nộp:</b> <div style="margin-top:-18px; margin-bottom:0px; margin-left:70px;" id="lyDoNop"></div></span></td></tr>
                    <tr><td colspan="2"><span ><b>Số tiền:</b> <span class="soTienBangSo"></span></span></td></tr>
                    
                </table>
            </td>
            <td width="250px">
                <!-- <table border="1" align="right" width="100%" height="200px" style="margin-top:0px; border-width:thin; border-style:dotted">
                    <tr>
                        <td height="20px" style="margin-top:0px; border-width:thin; border-style:dotted">TK Có</td><td style="margin-top:0px; border-width:thin; border-style:dotted">Số tiền</td>
                    </tr>
                    <tr>
                        <td style=" border-width:thin; border-style:dotted"><div style="margin-top:-70px;">1311</div></td><td align="right" ><div style="margin-top:-70px;" class="soTienBangSo"></div></td>
                    </tr> 
                    
                </table>-->
            </td>
        </tr>
        <tr><td colspan="2"><span><b>Bằng chữ:</b> <div style="margin-top:-18px; margin-bottom:0px; margin-left:70px;" class="soTienBangChu"></div></span></td></tr>
        <tr><td colspan="2"><span>&nbsp;</span></td></tr>
        <tr><td colspan="2"><span><i>Kèm theo:.....................................................................................................................................chứng từ gốc.</i></span></td></tr>
        <tr><td colspan="2"><span><b>Đã nhận đủ:</b> <div style="margin-top:-18px; margin-bottom:0px; margin-left:80px;" class="soTienBangChu"></div></span></td></tr>
        <tr><td colspan="2" align="right"><i><span>Ngày <?php echo date("d") ?> tháng <?php echo date("m") ?> năm <?php echo date("Y") ?></span></i></td></tr>
    </table>
    <table width="791px" style="text-align:center;">
        <tr><td><b>Giám đốc</b></td><td><b>Kế toán trưởng</b></td><td><b>Người nộp tiền</b></td><td><b>Người lập phiếu</b></td><td><b>Thủ quỹ</b></td></tr>
        <tr><td>(Ký, họ tên, đóng dấu)</td><td>(Ký, họ tên)</td><td>(Ký, họ tên)</td><td>(Ký, họ tên)</td><td>(Ký, họ tên)</td></tr>
        <tr><td colspan="5" height="50px"></td></tr>
        <!-- 
        <?php 
            /*if($this->zfcUserIdentity()) 
            {
                $nguoiLapPhieu=$this->zfcUserIdentity()->getHoTen();
            }*/
        ?>
        <tr><td><b>Lâm Văn Bạch</b></td><td><b>Phạm Thị Ngọc Ánh</b></td><td><b id="nguoiNopTien"></b></td><td><b><?php //echo $nguoiLapPhieu; ?></b></td><td><b>Dương Thị Hồng Thắm</b></td></tr> -->
    </table>
</div>
<div class="khongin">
    <div class="row">
        <div class="col-md-2">
            <div class="h5a-sidebar affix">
                <span class="breadcrumb row">
                    <a href="<?php echo $this->url('hang_hoa/crud',array('action'=>'index'));?>">/ Kho</a>
                    <a href="<?php echo $this->url('cong_no');?>">/ Khách hàng</a>
                     / Thanh toán /
                </span>
                <ul class="nav h5a-sidenav nav-list accordion">
                    <li>
                        <a href="<?php echo $this->url('cong_no/crud',array('action'=>'tong-hop-thu-chi'));?>">
                            Tổng hợp thu chi
                        </a>
                    </li>
                    <li>
                        <a href="<?php echo $this->url('cong_no/crud',array('action'=>'index'));?>">
                            Khách hàng
                        </a>
                    </li> 
                    <li>
                        <a href="<?php echo $this->url('cong_no/crud',array('action'=>'cong-no-nha-cung-cap'));?>" title="Công nợ nhà cung cấp">
                             Nhà cung cấp
                        </a>
                    </li> 
                    <li>
                        <a href="<?php echo $this->url('cong_no/crud',array('action'=>'lap-phieu-thu'));?>" title="Công nợ nhà cung cấp">
                            Phiếu thu
                        </a>
                    </li> 
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                            Phiếu chi
                        </a>
                         <ul class="dropdown-menu phieu-chi" id="notifications">   
                            <li>
                                <a href="<?php echo $this->url('cong_no/crud',array('action'=>'lap-phieu-chi-nha-cung-cap')); ?>">Lập phiếu chi nhà cung cấp
                                </a>
                                
                            </li>
                            <li class="divider"></li>
                            <li>
                                <a href="<?php echo $this->url('cong_no/crud',array('action'=>'lap-phieu-chi-khach-hang')); ?>">Lập phiếu chi khách hàng
                                </a>
                                
                            </li>
                        </ul>
                    </li>               
                </ul>
            </div>
        </div>
        <div class="col-md-10" role="main">
            <div class="h5a-docs-section">
                <div class="page-header">
                    <div class="row">
                        <div class="col-sm-6">
                            <h1>Lập phiếu thu</h1>
                        </div>
                        <div class="col-sm-6">
                            <div class="pull-right">
                                
                                                             
                            </div>
                            
                        </div>
                    </div>                    
                </div>   
                <table border="1" width="100%">
                    <tr>
                        <td width="15%"><b>Tên khách hàng</b> </td>
                        <td>
                            <input type="text" id="tenKhachHang" class="h5a-input form-control input-sm" placeholder="Nhập tên khách hàng">
                            <div id="search-result-khach-hang"></div>
                        </td>
                    </tr>
                    <tr>
                        <td><b>Ngày đầu kì</b> </td>
                        <td>
                           <span id="viewNgayDauKi">
                        </td>
                    </tr>
                    <tr><td><b>Nợ đầu kì</b> </td><td><span id="viewNoDauKi"></td></tr>
                    <tr><td><b>Nợ phát sinh</b> </td><td><span id="viewNoPhatSinh"></td></tr>
                    <tr><td><b>Nợ cuối kì</b> </td><td><span id="viewNoCuoiKi"></span> </td></tr>
                    <tr>
                        <td><b>Thanh toán</b> </td>
                        <td> 
                            <?php
                            $form->get('phieu-thu')->get('soTien')->setAttribute('class',' h5a-input form-control input-sm');
                                
                            $form->get('phieu-thu')->get('soTien')->setAttribute('disabled','true');
                                
                                echo $this->formElement($form->get('phieu-thu')->get('soTien'));
                            ?>
                        </td>
                    </tr>
                    <tr>
                        <td><b>Số dư</b> </td><td><span id="soDu"></span>
                        <?php
                            echo $this->formHidden($congNo->get('duNo'));  
                        ?>
                        </td>
                    </tr>
                    <tr>
                        <td><b>Lý do</b></td>
                        <td>
                            <?php     
                                $form->get('phieu-thu')->get('lyDo')->setAttribute('disabled',true);                               
                                echo $this->formElement($form->get('phieu-thu')->get('lyDo'));
                            ?>
                        </td>
                    </tr>
                    <tr><td><b>Ngày thanh toán</b> </td><td><?php echo date("d-m-Y"); ?></td></tr>                        
                </table>   
                <button type="submit" style="margin-top:5px;"  class="full btn h5a-btn btn-success" id="submitbutton" disabled='true'><i class="fa fa-print"></i> Lưu</button>        
        </div>
    </div>
</div>
<?php
    echo $this->form()->closeTag();
?>
    <!-- /.container -->

    <!-- jQuery -->
    <script src="<?php echo $this->basePath();?>/js/jquery.js"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="<?php echo $this->basePath();?>/js/bootstrap.min.js"></script>

    <!-- conver number to string vietnam -->
    <script src="<?php echo $this->basePath();?>/js/convernumbertostring.js"></script>

    <!-- DataTables JavaScript -->
    <script src="<?php echo $this->basePath();?>/js/plugins/dataTables/jquery.dataTables.js"></script>

    <!-- Page-Level Demo Scripts - Tables - Use for reference -->
    <script>
    $(document).ready(function() {

        var xhr;


        $('#tenKhachHang').keyup(function(){
            var tenKhachHang=$(this).val();  

            if(xhr && xhr.readyState != 4){
                xhr.abort(); //huy lenh ajax truoc do
            }
            xhr = $.ajax({
                url:'<?php echo $this->url('hang_hoa/crud', array('action'=>'search-khach-hang')); ?>',
                type:'POST',
                dataType:'json',
                data:{
                    'tenKhachHang':tenKhachHang
                },
                success:function(data){          
                    $.each(data, function(key,val){
                        $('#search-result-khach-hang').empty(); //lam rong khung ket qua

                        var pos = $('#tenKhachHang').position(); //lấy tọa độ của ô tên khách hàng
                        $('#search-result-khach-hang').css({
                            position:'absolute',
                            top:pos.top + 35,
                            left:pos.left,
                            'z-index': 100 // đặt search-result lên layout ngoài nhất
                        });
                        $.each(data, function(key, val){
                            $('#search-result-khach-hang').append('<div class="list-group-item"><span class="hide">'+val.idKhachHang+'</span><span>'+val.tenKhachHang+'</span><span class="hide">'+val.diaChiKhachHang+'</span><span class="hide">'+val.kenhPhanPhoi+'</span></div>'); // thêm một dòng vào search result, mỗi một dòng là 1 khách hàng
                        })
                    });

                }
            });    
        });     
        $('#search-result-khach-hang').on('click','.list-group-item',function(){
            var idKhachHang = $(this).find('span:eq(0)').text();
            var tenKhachHang = $(this).find('span:eq(1)').text();
            var diaChi=$(this).find('span:eq(2)').text();
            $('#idDoiTac').val(idKhachHang);
            $('#tenKhachHang').val(tenKhachHang);
            $('#hoTenNguoiNopTien').text(tenKhachHang);
            $('#diaChi').text(diaChi);
            $('#nguoiNopTien').text(tenKhachHang);

            $('#search-result-khach-hang').empty(); //lam rong khung ket qua

            var xhr1;
            if(xhr1 && xhr1.readyState != 4){
                xhr1.abort(); //huy lenh ajax truoc do
            }
            xhr1 = $.ajax({
                url:'<?php echo $this->url('cong_no/crud', array('action'=>'search-cong-no-khach-hang')); ?>',
                type:'POST',
                dataType:'json',
                data:{
                    'idKhachHang':idKhachHang
                },
                success:function(data){                      
                    $('#ki').val(data.ngayDauKi);
                    $('#noDauKi').val(data.noDauKi);
                    $('#noPhatSinh').val(data.noPhatSinh);

                    $('#viewNgayDauKi').text(data.ngayDauKi);
                    $('#viewNoDauKi').text(addPeriod(data.noDauKi));
                    $('#viewNoPhatSinh').text(addPeriod(data.noPhatSinh));
                    $('#viewNoCuoiKi').text(addPeriod(data.noCuoiKi));  

                    
                    var noCuoiKi=parseInt(data.noCuoiKi);
                    if(noCuoiKi>0&&!isNaN(noCuoiKi)){
                        $('#soTien').prop('disabled',false);
                        $('#lyDo').prop('disabled',false);
                        $('#submitbutton').prop('disabled',false);
                    }
                }
            });

        });

        $('#soTien').keyup(function(){

            var soTien=parseFloat($(this).val());
            var noCuoiKi=parseFloat($('#viewNoCuoiKi').text().replace(/ /g,''));
            var duNo=noCuoiKi-soTien;
            //alert(noCuoiKi+' '+soTien+' '+duNo);
            if(isNaN(soTien)||isNaN(noCuoiKi)||isNaN(duNo)||duNo<0){}
            else{
                $('#duNo').val(duNo);
                $('#soDu').text(addPeriod(duNo));
            }

        });

        // khi click vào nút submit lưu
        $('#submitbutton').click(function(){
            var noCuoiKi=parseFloat($('#viewNoCuoiKi').text().replace(/ /g,''));
            var soTien=parseFloat($('#soTien').val());
            //alert('số tiền: '+soTien+' Nợ cuối kì: '+noCuoiKi);
            if(isNaN(soTien)||isNaN(noCuoiKi)||noCuoiKi<=0||soTien==null||soTien==''||soTien==0||soTien>noCuoiKi){
                return false;
            }
            else{
                var lyDo=$('#lyDo').val();
                $('#lyDoNop').text(lyDo);
                var soTienBangSo=$('#soTien').val();
                $('.soTienBangSo').text(addPeriod(soTienBangSo));

                var soTienBangChu=docso(soTienBangSo);
                $('.soTienBangChu').text(soTienBangChu);

                window.print();
                return true;
            }


        });
               
    });

    function addPeriod(nStr){
        nStr += '';
        var x = nStr.split(' ');
        var x1 = x[0];
        var x2 = x.length > 1 ? ' ' + x[1] : '';
        var rgx = /(\d+)(\d{3})/;
        while (rgx.test(x1)) {
            x1 = x1.replace(rgx, '$1' + ' ' + '$2');
        }
        return x1 + x2;
    }
    </script>