<?php
    $this->headTitle('Thanh toán công nợ vs Nhà cung cấp');
    $form->setAttribute('action', $this->url('cong_no/crud', array('action' => 'thanhToanNhaCungCap')));
     $form->setAttribute('role','form');
     $form->setAttribute('id','formThanhToan');
     $form->setAttribute('class','form-horizontal');
     $form->prepare();
     echo $this->form()->openTag($form);
     echo $this->formHidden($form->get('phieu-chi')->get('idPhieuChi'));
     echo $this->formHidden($form->get('phieu-chi')->get('idUserNv'));

     $form->get('phieu-chi')->get('ngayThanhToan')->setAttribute('hidden','true');
     $form->get('phieu-chi')->get('ngayThanhToan')->setAttribute('value', date("Y-m-d"));
     echo $this->formElement($form->get('phieu-chi')->get('ngayThanhToan'));
     

     $congNo=$form->get('phieu-chi')->get('idCongNo');
     echo $this->formHidden($congNo->get('idCongNo'));

     $congNo->get('idDoiTac')->setAttribute('value',$thongTinDoiTac->getIdDoiTac());
     echo $this->formHidden($congNo->get('idDoiTac'));

     $congNo->get('ki')->setAttribute('hidden','true');
     $congNo->get('ki')->setAttribute('value',$response['ngayDauKi']);
     echo $this->formHidden($congNo->get('ki'));

     $congNo->get('noDauKi')->setAttribute('value',$response['noDauKi']);
     echo $this->formHidden($congNo->get('noDauKi'));

     $congNo->get('noPhatSinh')->setAttribute('value',$response['noPhatSinh']);
     echo $this->formHidden($congNo->get('noPhatSinh'));

?>
<style type="text/css">    
    #nha-cung-cap-search-result{ cursor:pointer;}
</style>

<div class="row">
    <div class="col-md-2">
        <div class="h5a-sidebar affix">
            <span class="breadcrumb row">
                <a href="<?php echo $this->url('hang_hoa/crud',array('action'=>'index'));?>">/ Kho</a>
                <a href="<?php echo $this->url('cong_no');?>">/ Khách hàng</a>
                 / Thanh toán /
            </span>
            <ul class="nav h5a-sidenav nav-list accordion">
                <li>
                    <a href="<?php echo $this->url('cong_no/crud',array('action'=>'congNoNhaCungCap'));?>" title="Công nợ nhà cung cấp">
                        <i class="glyphicon glyphicon-save"></i> Công nợ NCC
                    </a>
                </li>
            </ul>
        </div>
    </div>
    <div class="col-md-10" role="main">
        <div class="h5a-docs-section">
            <div class="page-header">
                <div class="row">
                    <div class="col-sm-6">
                        <h1>Thanh toán</h1>
                    </div>
                    <div class="col-sm-6">
                        <div class="pull-right">
                                     
                        </div>
                        
                    </div>
                </div>                    
            </div>
            <table border="1" width="100%">
                <tr>
                    <td><b>Tên nhà cung cấp </b></td>
                    <td>
                        <?php echo $thongTinDoiTac->getHoTen(); ?>
                    </td>
                </tr>
                <tr>
                    <td><b>Ngày đầu kì</b></td>
                    <td><?php echo $response['ngayDauKi']; ?>
                    </td>
                </tr>
                
                <tr>
                    <td><b>Nợ phát sinh</b></td>
                    <td>
                        <?php echo $response['noPhatSinh']; ?>
                    </td>
                </tr>
                <tr>
                    <td><b>Nợ cuối kì</b></td>
                    <td> <span id="noCuoiKi"><?php echo $response['noCuoiKi']; ?></span>
                    </td>
                </tr>
                <tr>
                    <td><b>Thanh toán</b></td>
                    <td> 
                    <?php
                        $form->get('phieu-chi')->get('soTien')->setAttribute('min',0); 
                        $form->get('phieu-chi')->get('soTien')->setAttribute('class','h5a-input form-control input-sm'); 
                        if((float)$response['noCuoiKi']<=0)
                        {
                            $form->get('phieu-chi')->get('soTien')->setAttribute('disabled',true);
                        }
                        $form->get('phieu-chi')->get('soTien')->setAttribute('value', 0 );
                        echo $this->formElement($form->get('phieu-chi')->get('soTien')); 
                    ?>
                    </td>
                </tr>
   
                <tr>
                    <td><b>Số dư</b></td>
                    <td>
                     <span  id="soDu"></span>
                     <?php
                        $congNo->get('duNo')->setAttribute('hidden','true');
                        $congNo->get('duNo')->setAttribute('value',$response['noCuoiKi']);
                        echo $this->formHidden($congNo->get('duNo'));
                    ?>
                    </td>
                </tr>
                <tr>
                    <td><b>Lý do</b></td>
                    <td>
                    <?php 
                        $form->get('phieu-chi')->get('lyDo')->setAttribute('class','h5a-input form-control input-sm'); 
                        echo $this->formElement($form->get('phieu-chi')->get('lyDo')); 
                    ?>
                    </td>
                </tr>
                <tr>
                    <td><b>Ngày thanh toán</b></td>
                    <td>
                     <?php echo date("d/m/Y"); ?>
                    </td>
                </tr>
            </table>
             <button type="submit" style="margin-top:5px;" class="full btn h5a-btn btn-success" id="submitbutton"
                <?php 
                    if((float)$response['noCuoiKi']<=0)
                    {
                        echo 'disabled';
                    }
                ?>
                >
                    <i class="fa fa-print"></i> Lưu</button>
    </div>
</div>

<?php
    echo $this->form()->closeTag();
?>
    <!-- /.container -->

    <!-- jQuery -->
    <script src="<?php echo $this->basePath();?>/js/jquery.js"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="<?php echo $this->basePath();?>/js/bootstrap.min.js"></script>

    <!-- DataTables JavaScript -->
    <script src="<?php echo $this->basePath();?>/js/plugins/dataTables/jquery.dataTables.js"></script>

    <!-- Page-Level Demo Scripts - Tables - Use for reference -->
    <script>
    $(document).ready(function() {

        $('#submitbutton').click(function(){
            var soTienThanhToan=parseInt($('#soTien').val());// là số tiền thanh toán nhập zô
            if(soTienThanhToan==0||soTienThanhToan==''||soTienThanhToan==null)
            {
                alert('Bạn chưa nhập số tiền thanh toán!');
                return false;
            }
            return true;
            
        });
               
        $('#soTien').change(function(){   
            var noCuoiKi=parseInt($('#noCuoiKi').text());                  
            var tienThanhToan=parseInt($(this).val());
            if(tienThanhToan<=noCuoiKi)
            {
                $('#duNo').val(noCuoiKi-tienThanhToan);
                $('#soDu').text(noCuoiKi-tienThanhToan);
            }
            else
            {
                alert('Số tiền thanh toán lớn hơn số dư cuối kì');
                $('#duNo').val('');
                $('#soTien').val(0);
                $('#soDu').text(noCuoiKi);
            }
        });
        $('#soTien').keyup(function(){    
            var noCuoiKi=parseInt($('#noCuoiKi').text());                  
            var tienThanhToan=parseInt($(this).val());
            if(tienThanhToan<=noCuoiKi)
            {
                $('#duNo').val(noCuoiKi-tienThanhToan);
                $('#soDu').text(noCuoiKi-tienThanhToan);
            }
            else
            {
                alert('Số tiền thanh toán lớn hơn số dư cuối kì');
                $('#duNo').val('');
                $('#soTien').val(0);
                $('#soDu').text(noCuoiKi);
            }
        });                
               
    });
   
    </script>