<?php
    $this->headTitle('Thanh toán');
    $form->setAttribute('action', $this->url('cong_no/crud', array('action' => 'thanhToan')));
     $form->setAttribute('role','form');
     $form->setAttribute('id','formThanhToan');
     $form->setAttribute('class','form-horizontal');
     $form->prepare();
     echo $this->form()->openTag($form);
     
     echo $this->formHidden($form->get('phieu-thu')->get('idPhieuThu'));
     
     $congNo=$form->get('phieu-thu')->get('idCongNo');
     echo $this->formHidden($congNo->get('idCongNo'));

     $congNo->get('idDoiTac')->setAttribute('value',$thongTinDoiTac->getIdDoiTac());
     echo $this->formHidden($congNo->get('idDoiTac'));


     $congNo->get('ki')->setAttribute('hidden','true');
     $congNo->get('ki')->setAttribute('value',$response['ngayDauKi']);
     echo $this->formHidden($congNo->get('ki'));

     $congNo->get('noDauKi')->setAttribute('value',$response['noDauKi']);
     echo $this->formHidden($congNo->get('noDauKi'));

     $congNo->get('noPhatSinh')->setAttribute('value',$response['noPhatSinh']);
     echo $this->formHidden($congNo->get('noPhatSinh'));

     echo $this->formHidden($form->get('phieu-thu')->get('idUserNv'));

     $form->get('phieu-thu')->get('ngayThanhToan')->setAttribute('value', date("Y-m-d"));
     echo $this->formHidden($form->get('phieu-thu')->get('ngayThanhToan'));     
?>
<style type="text/css">    
    #khach-hang-search-result{ cursor:pointer;}
</style>
<div class="container">
    <div class="row">
        <div class="col-md-2">
            <div class="h5a-sidebar affix">
                <span class="breadcrumb row">
                    <a href="<?php echo $this->url('hang_hoa/crud',array('action'=>'index'));?>">/ Kho</a>
                    <a href="<?php echo $this->url('cong_no');?>">/ Khách hàng</a>
                     / Thanh toán /
                </span>
                <ul class="nav h5a-sidenav nav-list accordion">
                    <li>
                        <a href="<?php echo $this->url('cong_no/crud',array('action'=>'index'));?>">
                            <i class="glyphicon glyphicon-open"></i> Công nợ Khách hàng
                        </a>
                    </li>                    
                </ul>
            </div>
        </div>
        <div class="col-md-10" role="main">
            <div class="h5a-docs-section">
                <div class="page-header">
                    <div class="row">
                        <div class="col-sm-6">
                            <h1>Thanh toán</h1>
                        </div>
                        <div class="col-sm-6">
                            <div class="pull-right">
                                <div class="btn-group ">
                                    <button type="button" class="h5a-btn btn btn-default btn-sm">
                                        <i class="fa fa-chevron-left"></i>
                                    </button>                                    
                                    <button type="button" class="h5a-btn btn btn-default btn-sm">
                                        <i class="fa fa-chevron-right"></i>
                                    </button>
                                </div>
                                <button type="button" class="h5a-btn btn btn-default btn-sm">Export</button>   
                                <!-- <a href="<?php echo $this->url('cong_no/crud', array('action'=>'thanhToan')); ?>"><button type="button" class="h5a-btn btn btn-default btn-sm">Thanh Toán</button></a>  -->                                
                            </div>
                            
                        </div>
                    </div>                    
                </div>   

                <div class="panel-info col-sm-12" style="margin-bottom:15px; text-align:center;"> 
                    <div class="panel-heading"> 
                        <h3 class="panel-title">Tên khách hàng: <?php echo $thongTinDoiTac->getHoTen(); ?>  </h3> 
                    </div>                     
                </div><br>

                <div class="col-sm-6">
                    <div class="panel panel-info">                    
                        <div class="panel-body"> 
                            <h3 class="panel-title">Ngày đầu kì: <?php echo $response['ngayDauKi']; ?></h3>
                        </div> 
                    </div>
                    <div class="panel panel-info">
                        <div class="panel-body"> 
                            <h3 class="panel-title">
                            Nợ đầu kì: <?php echo $response['noDauKi']; ?>
                            </h3>
                        </div>
                    </div>
                    <div class="panel panel-info">
                        <div class="panel-body"> 
                            <h3 class="panel-title">Nợ phát sinh: <?php echo $response['noPhatSinh']; ?></h3> 
                        </div> 
                    </div>
                    <div class="panel panel-info">                        
                        <div class="panel-body" style="padding-bottom: 8px;"> 
                            <div>
                                <h3 class="panel-title" style="width: 90px;">Lý do: </h3>
                            </div> 
                            <div style="margin-top: -23px; margin-left: 55px;">
                                <?php                                    
                                    echo $this->formElement($form->get('phieu-thu')->get('lyDo'));
                                ?>
                            </div>                           
                        </div>
                    </div>
                </div> 

                <div class="col-sm-6">
                    <div class="panel panel-info">
                        <div class="panel-body"> 
                            <h3 class="panel-title">Ngày thanh toán: <?php echo date("d/m/Y"); ?></h3> 
                        </div> 
                    </div>

                    <div class="panel panel-info">
                        <div class="panel-body"> 
                            <h3 class="panel-title">
                            Nợ cuối kì: <span id="noCuoiKi"><?php echo $response['noCuoiKi']; ?></span>
                            </h3>
                        </div>
                    </div>
                    
                    <div class="panel panel-info">
                        <div class="panel-body" style="padding-bottom: 8px;"> 
                            <div>
                                <h3 class="panel-title" style="width: 90px;">Thanh toán: </h3>
                            </div> 
                            <div style="margin-top: -23px; margin-left: 95px;">
                                <?php
                                    $form->get('phieu-thu')->get('soTien')->setAttribute('value',0);
                                    $form->get('phieu-thu')->get('soTien')->setAttribute('class',' h5a-input form-control input-sm');
                                    if((float)$response['noCuoiKi']<=0)
                                    {
                                        $form->get('phieu-thu')->get('soTien')->setAttribute('disabled','true');
                                    }
                                    echo $this->formElement($form->get('phieu-thu')->get('soTien'));
                                ?>
                            </div>                           
                        </div> 
                    </div>
                
                    <div class="panel panel-info">
                        <div class="panel-body"> 
                            <h3 class="panel-title">
                            Số dư: <span  id="soDu"></span>
                            <?php
                                $congNo->get('duNo')->setAttribute('hidden','true');
                                $congNo->get('duNo')->setAttribute('value',0);
                                echo $this->formHidden($congNo->get('duNo'));  
                            ?>
                            </h3>
                        </div>
                    </div>
                </div> 
                
                <div >
                    <div class="panel-body"> 
                        <button type="submit"  class="full btn h5a-btn btn-success" id="submitbutton"
                        <?php
                            if((float)$response['noCuoiKi']<=0)
                            {
                                echo 'disabled';
                            }
                        ?>
                        ><i class="fa fa-print"></i> Lưu</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<?php
    echo $this->form()->closeTag();
?>
    <!-- /.container -->

    <!-- jQuery -->
    <script src="<?php echo $this->basePath();?>/js/jquery.js"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="<?php echo $this->basePath();?>/js/bootstrap.min.js"></script>

    <!-- DataTables JavaScript -->
    <script src="<?php echo $this->basePath();?>/js/plugins/dataTables/jquery.dataTables.js"></script>

    <!-- Page-Level Demo Scripts - Tables - Use for reference -->
    <script>
    $(document).ready(function() {

        $('#submitbutton').click(function(){
            var soTienThanhToan=parseInt($('#soTien').val());// là số tiền thanh toán nhập zô
            if(soTienThanhToan==0||soTienThanhToan==''||soTienThanhToan==null)
            {
                alert('Bạn chưa nhập số tiền thanh toán!');
                return false;
            }
            return true;
            
        });
               
        $('#soTien').change(function(){   
            var noCuoiKi=parseInt($('#noCuoiKi').text());                  
            var tienThanhToan=parseInt($(this).val());
            if(tienThanhToan<=noCuoiKi)
            {
                $('#duNo').val(noCuoiKi-tienThanhToan);
                $('#soDu').text(noCuoiKi-tienThanhToan);
            }
            else
            {
                alert('Số tiền thanh toán lớn hơn số dư cuối kì');
                $('#duNo').val('');
                $('#soTien').val(0);
                $('#soDu').text(noCuoiKi);
            }
        });
        $('#soTien').keyup(function(){    
            var noCuoiKi=parseInt($('#noCuoiKi').text());                  
            var tienThanhToan=parseInt($(this).val());
            if(tienThanhToan<=noCuoiKi)
            {
                $('#duNo').val(noCuoiKi-tienThanhToan);
                $('#soDu').text(noCuoiKi-tienThanhToan);
            }
            else
            {
                alert('Số tiền thanh toán lớn hơn số dư cuối kì');
                $('#duNo').val('');
                $('#soTien').val(0);
                $('#soDu').text(noCuoiKi);
            }
        });                
               
    });
   
    </script>