<style type="text/css">
    table tr td{
        padding: 0px;
    }
    #notifications{
         width: 215px; 
         margin-left: 20px;
    }
</style>

<div class="khongin">
    <div class="row">
        <div class="col-md-2">
            <div class="h5a-sidebar affix">
                <span class="breadcrumb row">
                    <a href="<?php echo $this->url('hang_hoa/crud',array('action'=>'index'));?>">/ Kho</a>
                    <a href="<?php echo $this->url('cong_no');?>">/ Khách hàng</a>
                     / Thanh toán /
                </span>
                <ul class="nav h5a-sidenav nav-list accordion">
                    <li>
                        <a href="<?php echo $this->url('cong_no/crud',array('action'=>'index'));?>">
                            Khách hàng
                        </a>
                    </li> 
                    <li>
                        <a href="<?php echo $this->url('cong_no/crud',array('action'=>'cong-no-nha-cung-cap'));?>" title="Công nợ nhà cung cấp">
                            Nhà cung cấp
                        </a>
                    </li> 
                    <li>
                        <a href="<?php echo $this->url('cong_no/crud',array('action'=>'lap-phieu-thu'));?>" title="Công nợ nhà cung cấp">
                            Phiếu thu
                        </a>
                    </li> 
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                            Phiếu chi
                        </a>
                         <ul class="dropdown-menu" id="notifications">   
                            <li>
                                <a href="<?php echo $this->url('cong_no/crud',array('action'=>'lap-phieu-chi-nha-cung-cap')); ?>">Lập phiếu chi nhà cung cấp
                                </a>
                                
                            </li>
                            <li class="divider"></li>
                            <li>
                                <a href="<?php echo $this->url('cong_no/crud',array('action'=>'lap-phieu-chi-khach-hang')); ?>">Lập phiếu chi khách hàng
                                </a>
                                
                            </li>
                        </ul>
                    </li>                 
                </ul>
            </div>
        </div>
        <div class="col-md-10" role="main">
            <div class="h5a-docs-section">
                <div class="page-header">
                    <!-- <div class="row">
                        <div class="col-sm-6">
                            <h1>xem phiếu thu</h1>
                        </div>
                        <div class="col-sm-6">
                           
                        </div>
                    </div>  -->
                    <div class="row">
                        <div align="center" style="font-size:13px;">
                            <table width="791px" hieght="567">
                                <tr><td width="400px">CTY CP & TB TRƯỜNG HỌC TRÀ VINH</td><td></td><td width="200px" style="text-align:right;">Mẫu số: 01 - TT</td></tr>
                                <tr><td>3A Trưng Nữ Vương Phường 1 TP .Trà Vinh</td><td></td><td width="200px" style="text-align:right;"></td></tr>
                                <tr><td>Mã số thuế: 2100 290 521</td><td></td><td width="200px" style="text-align:right;"></td></tr>
                                
                            </table>
                            <table width="791px" style="font-size:13px;">
                                <tr><td width="250px">&nbsp;</td><td style="font-size:16px; text-align:center;"><b>PHIẾU THU</b></td><td width="250px"><span >Số: <?php echo $phieuThu->getMaPhieuThu(); ?></span></td></tr>
                            </table>
                            <table width="791px" style="font-size:13px;">
                                <tr>
                                    <td width="541px">
                                        <table >
                                            <tr><td width="240px">&nbsp;</td><td align="center" width="300px">Ngày <?php echo $phieuThu->getNgayThanhToan()->format("d"); ?> tháng <?php echo $phieuThu->getNgayThanhToan()->format("m") ?> năm <?php echo $phieuThu->getNgayThanhToan()->format("Y") ?></td></tr>
                                            <tr><td width="240px">&nbsp;</td><td align="center" width="300px">Liên 1: Lưu</td></tr>
                                            <tr><td colspan="2"><span ><b>Họ tên người nộp tiền:</b> <?php echo $phieuThu->getIdCongNo()->getIdDoiTac()->getHoTen(); ?></span></td></tr>
                                            <tr><td colspan="2"><span ><b>Địa chỉ:</b> <?php echo $phieuThu->getIdCongNo()->getIdDoiTac()->getDiaChi(); ?></span></td></tr>
                                            <tr><td colspan="2"><span ><b>lý do nộp:</b> <div style="margin-top:-18px; margin-bottom:0px; margin-left:70px;" id="lyDoNop"><?php echo $phieuThu->getLyDo(); ?></div></span></td></tr>
                                            <tr><td colspan="2"><span ><b>Số tiền:</b> <span class="soTienBangSo"><?php echo $phieuThu->getSoTien(); ?></span></span></td></tr>
                                            
                                        </table>
                                    </td>
                                    <td width="250px">
                                        <!-- <table border="1" align="right" width="100%" height="200px" style="margin-top:0px; border-width:thin; border-style:dotted">
                                            <tr>
                                                <td height="20px" style="margin-top:0px; border-width:thin; border-style:dotted">TK Có</td><td style="margin-top:0px; border-width:thin; border-style:dotted">Số tiền</td>
                                            </tr>
                                            <tr>
                                                <td style=" border-width:thin; border-style:dotted"><div style="margin-top:-70px;">1311</div></td><td align="right" ><div style="margin-top:-70px;" class="soTienBangSo"></div></td>
                                            </tr> 
                                            
                                        </table>-->
                                    </td>
                                </tr>
                                <tr><td colspan="2"><span><b>Bằng chữ:</b> <div style="margin-top:-18px; margin-bottom:0px; margin-left:70px;" class="soTienBangChu"></div></span></td></tr>
                                <tr><td colspan="2"><span>&nbsp;</span></td></tr>
                                <tr><td colspan="2"><span><i>Kèm theo:.....................................................................................................................................chứng từ gốc.</i></span></td></tr>
                                <tr><td colspan="2"><span><b>Đã nhận đủ:</b> <div style="margin-top:-18px; margin-bottom:0px; margin-left:80px;" class="soTienBangChu"></div></span></td></tr>
                                <tr><td colspan="2" align="right"><span>Ngày <?php echo date("d") ?> tháng <?php echo date("m") ?> năm <?php echo date("Y") ?></span></td></tr>
                            </table>
                            <table width="791px" style="text-align:center;">
                                <tr><td><b>Giám đốc</b></td><td><b>Kế toán trưởng</b></td><td><b>Người nộp tiền</b></td><td><b>Người lập phiếu</b></td><td><b>Thủ quỹ</b></td></tr>
                                <tr><td>(Ký, họ tên, đóng dấu)</td><td>(Ký, họ tên)</td><td>(Ký, họ tên)</td><td>(Ký, họ tên)</td><td>(Ký, họ tên)</td></tr>
                                <tr><td colspan="5" height="50px"></td></tr>
                                <?php 
                                    if($this->zfcUserIdentity()) 
                                    {
                                        $nguoiLapPhieu=$this->zfcUserIdentity()->getHoTen();
                                    }
                                ?>
                                <tr><td><b>Lâm Văn Bạch</b></td><td><b>Phạm Thị Ngọc Ánh</b></td><td><b><?php echo $phieuThu->getIdCongNo()->getIdDoiTac()->getHoTen(); ?></b></td><td><b><?php echo $nguoiLapPhieu; ?></b></td><td><b>Dương Thị Hồng Thắm</b></td></tr>
                            </table>
                        </div>
                    </div>                   
                </div>   
                      
            </div>
        </div>
    </div>
</div>

<!-- /.container -->

<!-- jQuery -->
<script src="<?php echo $this->basePath();?>/js/jquery.js"></script>

<!-- Bootstrap Core JavaScript -->
<script src="<?php echo $this->basePath();?>/js/bootstrap.min.js"></script>

<!-- conver number to string vietnam -->
<script src="<?php echo $this->basePath();?>/js/convernumbertostring.js"></script>

<!-- DataTables JavaScript -->
<script src="<?php echo $this->basePath();?>/js/plugins/dataTables/jquery.dataTables.js"></script>

<!-- Page-Level Demo Scripts - Tables - Use for reference -->
<script type="text/javascript">
    $(document).ready(function(){
        var soTienBangChu=docso(<?php echo $phieuThu->getSoTien(); ?>);
        $('.soTienBangChu').text(soTienBangChu);
    })
        
</script>